"""
IP-SAKTI Backend — Authoritative Statutory Corpus Data
Directly mirrors verified Indian statutory texts with legal hierarchy:
Act -> Chapter -> Section -> Subsection -> Clause.
"""
from typing import Dict, Any, List

STATUTORY_CORPUS: List[Dict[str, Any]] = [
    {
        "id": "PATENTS_ACT_SEC_3P",
        "act_title": "The Patents Act, 1970",
        "title": "The Patents Act, 1970 — Section 3(p)",
        "short_title": "Patents Act 1970 § 3(p)",
        "authority": "Indian Patent Office (CGPDTM), DPIIT, Ministry of Commerce and Industry",
        "source_type": "Act",
        "jurisdiction": "India",
        "section_number": "3(p)",
        "legal_path": "The Patents Act, 1970 > Chapter II > Section 3(p)",
        "publication_date": "1970-09-19",
        "effective_date": "1972-04-20",
        "status": "Active",
        "source_url": "https://www.indiacode.nic.in/handle/123456789/1392",
        "content": "The following are not inventions within the meaning of this Act,— (p) an invention which in effect, is traditional knowledge or which is an aggregation or duplication of known properties of traditionally known component or components.",
        "plain_summary": "Explicit statutory bar preventing the patenting of known traditional Ayurvedic, Siddha, or Unani remedies, or mere mixtures thereof. Requires verifiable technical synergy or novel extraction apparatus.",
    },
    {
        "id": "PATENTS_ACT_SEC_3E",
        "act_title": "The Patents Act, 1970",
        "title": "The Patents Act, 1970 — Section 3(e)",
        "short_title": "Patents Act 1970 § 3(e)",
        "authority": "Indian Patent Office (CGPDTM)",
        "source_type": "Act",
        "jurisdiction": "India",
        "section_number": "3(e)",
        "legal_path": "The Patents Act, 1970 > Chapter II > Section 3(e)",
        "publication_date": "1970-09-19",
        "effective_date": "1972-04-20",
        "status": "Active",
        "source_url": "https://www.indiacode.nic.in/handle/123456789/1392",
        "content": "The following are not inventions within the meaning of this Act,— (e) a substance obtained by a mere admixture resulting only in the aggregation of the properties of the components thereof or a process for producing such substance.",
        "plain_summary": "Polyherbal combinations where each herb merely performs its known individual function without synergistic interaction are rejected under Section 3(e).",
    },
    {
        "id": "PATENTS_ACT_SEC_10_4",
        "act_title": "The Patents Act, 1970",
        "title": "The Patents Act, 1970 — Section 10(4)(ii)(D)",
        "short_title": "Patents Act 1970 § 10(4)(ii)(D)",
        "authority": "Indian Patent Office (CGPDTM)",
        "source_type": "Act",
        "jurisdiction": "India",
        "section_number": "10(4)(ii)(D)",
        "legal_path": "The Patents Act, 1970 > Chapter III > Section 10(4)(ii)(D)",
        "publication_date": "2002-06-25",
        "effective_date": "2003-05-20",
        "status": "Active",
        "source_url": "https://www.indiacode.nic.in/handle/123456789/1392",
        "content": "Every complete specification shall— disclose the source and geographical origin of the biological material in the specification, when used in an invention.",
        "plain_summary": "Mandatory disclosure requirement. Any patent specification utilizing Indian biological resources must truthfully declare geographical origin and obtain National Biodiversity Authority (NBA) approval.",
    },
    {
        "id": "DC_RULES_158B",
        "act_title": "Drugs and Cosmetics Rules, 1945",
        "title": "Drugs and Cosmetics Rules, 1945 — Rule 158B",
        "short_title": "D&C Rules 1945 Rule 158B",
        "authority": "Ministry of Ayush / Central Drugs Standard Control Organisation (CDSCO)",
        "source_type": "Rule",
        "jurisdiction": "India",
        "section_number": "158B",
        "legal_path": "Drugs and Cosmetics Rules, 1945 > Part XVI > Rule 158B",
        "publication_date": "2010-08-10",
        "effective_date": "2010-08-10",
        "status": "Active",
        "source_url": "https://cdsco.gov.in/opencms/opencms/en/Ayush/Ayush-Rules/",
        "content": "Guidelines for issue of license with respect to Ayurveda, Siddha or Unani drugs.— (I) Patent or Proprietary medicine: (A) Published literature (evidence of safety and effectiveness) as defined under clause (h) of section 3 of the Act. (B) Pilot clinical trial study as prescribed.",
        "plain_summary": "Governs licensing conditions for Ayurvedic Proprietary Medicines. Formulations altering classical proportions or introducing novel excipients require Category B proof of clinical safety and efficacy.",
    },
    {
        "id": "BIO_DIVERSITY_ACT_SEC_6",
        "act_title": "Biological Diversity Act, 2002",
        "title": "Biological Diversity Act, 2002 — Section 6",
        "short_title": "Biological Diversity Act 2002 § 6",
        "authority": "National Biodiversity Authority (NBA), MoEFCC",
        "source_type": "Act",
        "jurisdiction": "India",
        "section_number": "6",
        "legal_path": "Biological Diversity Act, 2002 > Chapter II > Section 6",
        "publication_date": "2003-02-05",
        "effective_date": "2004-07-01",
        "status": "Active",
        "source_url": "https://www.indiacode.nic.in/handle/123456789/2046",
        "content": "No person shall apply for any intellectual property right, by whatever name called, in or outside India for any invention based on any research or information on a biological resource obtained from India without obtaining the previous approval of the National Biodiversity Authority before making such application.",
        "plain_summary": "Statutory pre-condition for IPR grants: Prior approval (Form III) from the National Biodiversity Authority is mandatory before grant of patent.",
    },
    {
        "id": "BIO_DIVERSITY_ACT_SEC_7",
        "act_title": "Biological Diversity Act, 2002",
        "title": "Biological Diversity Act, 2002 — Section 7",
        "short_title": "Biological Diversity Act 2002 § 7",
        "authority": "State Biodiversity Boards (SBB), NBA",
        "source_type": "Act",
        "jurisdiction": "India",
        "section_number": "7",
        "legal_path": "Biological Diversity Act, 2002 > Chapter II > Section 7",
        "publication_date": "2003-02-05",
        "effective_date": "2004-07-01",
        "status": "Active",
        "source_url": "https://www.indiacode.nic.in/handle/123456789/2046",
        "content": "Prior intimation to State Biodiversity Board for obtaining biological resource for certain purposes.— No person, who is a citizen of India or a body corporate, association or organisation which is registered in India, shall obtain any biological resource for commercial utilisation, or bio-survey and bio-utilisation for commercial utilisation except after giving prior intimation to the State Biodiversity Board concerned.",
        "plain_summary": "Indian commercial entities harvesting or procuring wild botanical resources must file Form I with the relevant State Biodiversity Board for Access and Benefit Sharing (ABS). Cultivated species may be exempt if source trace is verified.",
    },
    {
        "id": "FSSAI_AYURVEDA_AAHAR_2022",
        "act_title": "Food Safety and Standards (Ayurveda Aahar) Regulations, 2022",
        "title": "Food Safety and Standards (Ayurveda Aahar) Regulations, 2022 — Regulation 3 & 8",
        "short_title": "FSSAI Ayurveda Aahar Regs 2022",
        "authority": "Food Safety and Standards Authority of India (FSSAI), MoHFW",
        "source_type": "Regulation",
        "jurisdiction": "India",
        "section_number": "3 & 8",
        "legal_path": "Food Safety and Standards Act, 2006 > Ayurveda Aahar Regulations, 2022",
        "publication_date": "2022-05-05",
        "effective_date": "2022-05-05",
        "status": "Active",
        "source_url": "https://www.fssai.gov.in/upload/uploadfiles/files/Gazette_Notification_Ayurveda_Aahar_09_05_2022.pdf",
        "content": "Regulation 3 & 8: Food prepared in accordance with the authoritative books specified in Schedule A of these regulations. Strict prohibition: No person shall manufacture or sell Ayurveda Aahar with claims for prevention, mitigation, treatment, or cure of any human disease.",
        "plain_summary": "Governs food and dietary supplements prepared per classical recipes. Products under this category CANNOT make medicinal or therapeutic claims.",
    }
]
