# -*- coding: utf-8 -*-
"""
IP-SAKTI Sahayak — Marathi (mr) Native Translation Generator
"""

import json
from updater import update_language_dict

MR_TRANSLATIONS = {
  # home (84 keys)
  "home.workflow.mostUsed": "सर्वाधिक वापरलेले",
  "home.hero.multilingual": "बहुभाषिक समर्थन",
  "home.hero.multilingual_title": "22 भारतीय भाषा + इंग्रजीमध्ये उपलब्ध",
  "home.hero.multilingual_desc": "संपूर्ण व्यासपीठ — AI उत्तरे, पुरावा कार्ड्स आणि वर्गीकरण स्पष्टीकरणांसह — भारताच्या सर्व 22 अधिकृत भाषांमध्ये आणि इंग्रजीत उपलब्ध आहे. कायदेशीर संज्ञा त्यांच्या मूळ अधिकृत स्वरूपात सुरक्षित ठेवल्या आहेत.",
  "home.features.versioning_updates": "आवृत्ती अद्यतने",
  "home.features.abstention_protects": "सुरक्षित परिहार संरक्षण",
  "home.workflows.heading": "आपण काय करू इच्छिता?",
  "home.intake.ayurvedicFormulation": "आयुर्वेदिक योग (फॉर्म्युलेशन)",
  "home.intake.ayurvedicFormulationHint": "शास्त्रीय किंवा मालकीचे बहु-हर्बल मिश्रण",
  "home.intake.herbalProduct": "हर्बल उत्पादन",
  "home.intake.herbalProductHint": "अर्क, आहारातील पूरक, फायटोमेडिसिन्स",
  "home.intake.plantResource": "वनस्पती / जैविक संसाधन",
  "home.intake.plantResourceHint": "औषधी वनस्पती, ABS/NBA पूर्व-मंजुरी",
  "home.intake.traditionalKnowledge": "पारंपारिक ज्ञान",
  "home.intake.traditionalKnowledgeHint": "शास्त्रीय ग्रंथ, TKDL पूर्व-कला पुनरावलोकन",
  "home.intake.novelProcess": "नवीन प्रक्रिया",
  "home.intake.novelProcessHint": "निष्कर्षण, स्थिरीकरण आणि Section 3(p) पडताळणी",
  "home.intake.brandIdentity": "ब्रँड ओळख",
  "home.intake.brandIdentityHint": "व्यापारचिन्ह, वर्ग 5/3/30/44",
  "home.intake.geographicalIdentity": "भौगोलिक ओळख",
  "home.intake.geographicalIdentityHint": "GI संकेत, मूळ प्रमाणपत्र",
  "home.intake.regulatoryQuestion": "नियामक प्रश्न",
  "home.intake.regulatoryQuestionHint": "FSSAI, AYUSH, Rule 158B, Schedule T",
  "home.demo.badge": "थेट मार्गदर्शक प्रात्यक्षिक",
  "home.demo.simulation": "नियामक अनुकरण",
  "home.demo.title": "कच्च्या संकल्पनेपासून कायदेशीर संरक्षणापर्यंत",
  "home.demo.story": "अश्वगंधा-ब्राह्मी सिरपचे विश्लेषण कसे होते ते पहा: Section 3(p) पूर्व-कला, Rule 158B अनुपालन, FSSAI आयुष आहार वर्गवारी आणि ABS पूर्व-मंजुरी आवश्यकता.",
  "home.demo.notice": "सर्व शिफारसी थेट राजपत्रातील कायदेशीर तरतुदींशी जोडलेल्या आहेत.",
  "home.demo.startCase": "हे प्रकरण सुरू करा",
  "home.demo.inspectDossier": "नमुना डॉसियर तपासा",
  "home.demo.step1.label": "घटक विश्लेषण",
  "home.demo.step1.sub": "अश्वगंधा + ब्राह्मी सिरप",
  "home.demo.step2.label": "TKDL शोध",
  "home.demo.step2.sub": "भावप्रकाश & चरक संहिता संदर्भ",
  "home.demo.step3.label": "Section 3(p) जोखीम",
  "home.demo.step3.sub": "पारंपारिक ज्ञान पेटंट अपवाद",
  "home.demo.step4.label": "Rule 158B पडताळणी",
  "home.demo.step4.sub": "शास्त्रीय ग्रंथ पुरावा मार्ग",
  "home.demo.step5.label": "FSSAI विरुद्ध AYUSH",
  "home.demo.step5.sub": "आयुष आहार वर्गवारी पर्याय",
  "home.demo.step6.label": "NBA / ABS मंजुरी",
  "home.demo.step6.sub": "Form III जैविक संसाधन अर्ज",
  "home.demo.step7.label": "कार्यवाही आराखडा",
  "home.demo.step7.sub": "संरक्षण धोरण & दाखल करणे",
  "home.evidence.sample": "नमुना कायदेशीर पुरावा",
  "home.evidence.actIndia": "पेटंट कायदा 1970 (भारत)",
  "home.evidence.strength": "कायदेशीर पुरावा बळकटपणा",
  "home.evidence.high": "उच्च",
  "home.evidence.whyRelevant": "हे का लागू होते: जर एखादा दावा पारंपारिक ज्ञानावर आधारित केवळ एकत्रीकरण असेल, तर Section 3(p) अंतर्गत पेटंट नाकारले जाते.",
  "home.evidence.viewSource": "अधिकृत स्रोत पहा",
  "home.evidence.disclaimer": "हा उतारा अधिकृत भारतीय राजपत्रातून डिजिटल स्वाक्षरीने सत्यापित केला आहे.",
  "home.multilingual.badge": "22 भाषा + इंग्रजी",
  "home.multilingual.fullSupport": "भारताच्या सर्व 22 अधिकृत भाषांमध्ये पूर्ण समर्थन",
  "home.multilingual.more": "अधिक भाषा",
  "home.multilingual.all22": "भारतीय संविधानाच्या आठव्या अनुसूचीतील सर्व 22 भाषांमध्ये उपलब्ध",
  "home.domain.patent": "पेटंट (कलम 3(p) & 3(e))",
  "home.domain.patentDesc": "पारंपारिक ज्ञान अपवाद, नवीनता आणि पूर्व-कला विश्लेषण.",
  "home.domain.trademark": "व्यापारचिन्ह (ट्रेडमार्क)",
  "home.domain.trademarkDesc": "आयुर्वेदिक ब्रँड, लोगो, वर्ग 5 आणि औषधी वर्गवारी नोंदणी.",
  "home.domain.gi": "भौगोलिक संकेत (GI)",
  "home.domain.giDesc": "स्थानिक वनस्पती आणि पारंपारिक औषध पद्धतींचे संरक्षण.",
  "home.domain.plantVariety": "वनस्पती वाण संरक्षण (PPV&FR)",
  "home.domain.plantVarietyDesc": "शेतकरी अधिकार आणि औषधी वनस्पती वाण नोंदणी.",
  "home.domain.copyright": "कॉपीराइट",
  "home.domain.copyrightDesc": "संशोधन दस्तऐवज, शास्त्रीय टीका आणि डिजिटल डेटाबेस संरक्षण.",
  "home.domain.industrialDesign": "औद्योगिक डिझाइन",
  "home.domain.industrialDesignDesc": "औषध वितरण उपकरणे, बाटल्या आणि पॅकेजिंग डिझाइन.",
  "home.domain.tk": "पारंपारिक ज्ञान (TKDL)",
  "home.domain.tkDesc": "आयुर्वेद, सिद्ध आणि युनानी ज्ञानाचे जागतिक संरक्षण.",
  "home.domain.abs": "जैविक विविधता आणि ABS",
  "home.domain.absDesc": "राष्ट्रीय जैवविविधता प्राधिकरण (NBA) Form III मंजुरी.",
  "home.domain.ayush": "आयुष (AYUSH) नियमने",
  "home.domain.ayushDesc": "औषध आणि सौंदर्य प्रसाधने कायदा, शास्त्रीय संदर्भ.",
  "home.domain.fssaiDesc": "आयुष आहार नियमने, पोषण पूरक आणि सुरक्षा मानके.",
  "home.domain.drugsCosmetics": "औषधे आणि सौंदर्य प्रसाधने कायदा",
  "home.domain.drugsCosmeticsDesc": "Rule 158B पुरावा आणि Schedule T GMP मानके.",
  "home.domain.internationalIp": "आंतरराष्ट्रीय बौद्धिक संपदा",
  "home.domain.internationalIpDesc": "PCT, पॅरिस कन्व्हेन्शन आणि नगोया प्रोटोकॉल.",
  "home.pipeline.question": "प्रश्न",
  "home.pipeline.classify": "वर्गवारी",
  "home.pipeline.evidence": "पुरावा",
  "home.pipeline.intelligence": "इंटेलिजन्स",
  "home.pipeline.action": "कृती",
  "home.domain.plantVarietyProtection": "वनस्पती वाण संरक्षण",

  # nav (6 keys)
  "nav.quick.herbalPatent": "हर्बल पेटंट पात्रता",
  "nav.quick.fssaiRules": "FSSAI आयुष आहार नियम",
  "nav.quick.giProtection": "GI संरक्षण औषधी वनस्पती",
  "nav.quick.absNagoya": "ABS नगोया प्रोटोकॉल अनुपालन",
  "nav.quick.section3p": "Section 3(p) पारंपारिक ज्ञान अपवाद",
  "nav.quick.tkNeem": "कडुलिंब आणि हळद पेटंट विरोध",

  # wizard (64 keys)
  "wizard.stepProgress": "टप्पा प्रगती",
  "wizard.stepPrev": "मागील टप्पा",
  "wizard.stepNext": "पुढील टप्पा",
  "wizard.stepSaveRoadmap": "प्रकरण जतन करा आणि कृती आराखडा तयार करा",
  "wizard.backToCases": "माझ्या प्रकरणांवर परत जा",
  "wizard.guidedSetup": "मार्गदर्शित बौद्धिक संपदा आणि नियामक सेटअप",
  "wizard.gap.title": "पुरावा अंतर आढळले",
  "wizard.gap.desc": "या योग प्रकारासाठी विशिष्ट शास्त्रीय संदर्भांची आवश्यकता असू शकते.",
  "wizard.gap.fix": "पुरावा अंतर कसे भरून काढायचे ते पहा",
  "wizard.validation.titleRequired": "फॉर्म्युलेशन शीर्षक आवश्यक आहे",
  "wizard.dnaReady": "फॉर्म्युलेशन DNA तयार आहे",
  "wizard.ingIndex": "घटक",
  "wizard.assetNature": "संपत्तीचे स्वरूप",
  "wizard.selectTreatises": "मान्यताप्राप्त शास्त्रीय ग्रंथ निवडा",
  "wizard.classicalCitation": "शास्त्रीय संदर्भ / श्लोक उद्धरण",
  "wizard.indicationsLabel": "उपचारात्मक संकेत / रोगाधिकार",
  "wizard.indicationsPlaceholder": "उदा. कास, श्वास, ज्वर, रसायन...",
  "wizard.prepNarrative": "तयारी पद्धतीचे वर्णन",
  "wizard.prepNarrativePlaceholder": "शोधन, भावना किंवा निष्कर्षण प्रक्रियेचे तपशीलवार वर्णन करा...",
  "wizard.commercialPathway": "व्यावसायिक मार्ग",
  "wizard.targetJurisdictionTitle": "लक्ष्य कार्यक्षेत्र",
  "wizard.supportingDocsTitle": "सहाय्यक दस्तऐवज आणि पुरावे",
  "wizard.docAddPlaceholder": "दस्तऐवजाचे नाव किंवा संदर्भ प्रविष्ट करा...",
  "wizard.addDocBtn": "दस्तऐवज जोडा",
  "wizard.plantPart": "वापरलेला वनस्पती भाग",
  "wizard.sourcingType": "स्रोत प्रकार",
  "wizard.cat.ayurvedic": "आयुर्वेदिक योग",
  "wizard.cat.ayurvedicDesc": "पारंपारिक किंवा मालकीचे औषध",
  "wizard.cat.herbal": "हर्बल उत्पादन",
  "wizard.cat.herbalDesc": "वनस्पती अर्क किंवा पूरक",
  "wizard.cat.traditional": "पारंपारिक ज्ञान",
  "wizard.cat.traditionalDesc": "वारसा पद्धत किंवा ग्रंथ",
  "wizard.cat.plant": "जैविक संसाधन",
  "wizard.cat.plantDesc": "वनस्पती किंवा जैव संपत्ती",
  "wizard.cat.process": "नवीन प्रक्रिया",
  "wizard.cat.processDesc": "निष्कर्षण किंवा उत्पादन पद्धत",
  "wizard.cat.brand": "ब्रँड किंवा उत्पादन नाव",
  "wizard.cat.brandDesc": "व्यापारचिन्ह संरक्षण",
  "wizard.prep.classical": "शास्त्रीय विधी",
  "wizard.prep.classicalDesc": "अधिकृत संहितेनुसार तयार केलेले",
  "wizard.prep.extract": "मानकीकृत अर्क",
  "wizard.prep.extractDesc": "सक्रिय घटकांचा जलीय/अल्कोहोलिक अर्क",
  "wizard.prep.novel": "नवीन तंत्रज्ञान",
  "wizard.prep.novelDesc": "नॅनोपार्टिकल्स किंवा नवीन वितरण प्रणाली",
  "wizard.commercial.domestic": "स्थानिक भारतीय बाजार",
  "wizard.commercial.domesticDesc": "भारतात उत्पादन आणि विक्री",
  "wizard.commercial.export": "आंतरराष्ट्रीय निर्यात",
  "wizard.commercial.exportDesc": "जागतिक बाजारात विक्री",
  "wizard.commercial.rd": "संशोधन आणि विकास",
  "wizard.commercial.rdDesc": "पूर्व-क्लिनिकल किंवा क्लिनिकल चाचण्या",
  "wizard.commercial.licensing": "तंत्रज्ञान परवाना",
  "wizard.commercial.licensingDesc": "तृतीय पक्षाला परवाना देणे",
  "wizard.jur.india": "भारत",
  "wizard.jur.indiaDesc": "भारतीय पेटंट आणि नियामक कायदे",
  "wizard.jur.us": "युनायटेड स्टेट्स",
  "wizard.jur.usDesc": "US FDA आणि USPTO नियम",
  "wizard.jur.eu": "युरोपीय युनियन",
  "wizard.jur.euDesc": "EMA आणि EPO नियमने",
  "wizard.jur.intl": "आंतरराष्ट्रीय (PCT)",
  "wizard.jur.intlDesc": "जागतिक पेटंट सहकार्य करार",
  "wizard.claim.therapeutic": "उपचारात्मक दावा",
  "wizard.claim.nutritional": "पोषण किंवा आहार दावा",
  "wizard.claim.cosmetic": "सौंदर्य प्रसाधन दावा",
  "wizard.claim.wellness": "सामान्य आरोग्य आणि कल्याण",

  # explore (15 keys)
  "explore.breadcrumb": "कायदेशीर चौकट शोधा",
  "explore.searchPlaceholder": "फॉर्म्युलेशन, पेटंट, Section 3(p), Rule 158B, ABS, TKDL शोधा...",
  "explore.allFrameworks": "सर्व नियामक चौकटी",
  "explore.ipPatents": "IP आणि पेटंट्स",
  "explore.ayushFssai": "आयुष आणि FSSAI",
  "explore.bioAbs": "जैवविविधता आणि ABS",
  "explore.tkTkdl": "पारंपारिक ज्ञान आणि TKDL",
  "explore.statutoryHighlights": "वैधानिक ठळक मुद्दे",
  "explore.noItems": "निवडलेल्या श्रेणीत कोणतीही नियामक चौकट आढळली नाही.",
  "explore.actSec3p": "पेटंट कायदा 1970 — कलम 3(p) & 3(e)",
  "explore.actRule158b": "औषधे आणि सौंदर्य प्रसाधने नियम 1945 — नियम 158B",
  "explore.actAbs": "जैविक विविधता कायदा 2002 — Form III ABS",
  "explore.actAahar": "आयुष आहार नियमने 2022 — FSSAI चौकट",
  "explore.actTkdl": "पारंपारिक ज्ञान डिजिटल लायब्ररी (TKDL) चौकट",
  "explore.actGi": "भौगोलिक संकेत (नोंदणी आणि संरक्षण) कायदा 1999",

  # evidence (15 keys)
  "evidence.breadcrumb": "कायदेशीर पुरावा संग्रह",
  "evidence.allAuthorities": "सर्व नियामक प्राधिकरणे",
  "evidence.allTypes": "सर्व वैधानिक प्रकार",
  "evidence.act": "कायदा (Act)",
  "evidence.rule": "नियम (Rule)",
  "evidence.gazetteNotification": "राजपत्र अधिसूचना",
  "evidence.pharmacopoeialStandard": "फार्माकोपियल मानक",
  "evidence.treaty": "आंतरराष्ट्रीय करार",
  "evidence.verifiedAuthority": "सत्यापित नियामक प्राधिकरण",
  "evidence.cryptoHash": "क्रिप्टोग्राफिक फॉरेन्सिक हॅश",
  "evidence.plainSummary": "सोपा सारांश",
  "evidence.officialExcerpt": "अधिकृत वैधानिक उतारा",
  "evidence.inspectCitation": "कायदेशीर संदर्भ तपासा",
  "evidence.noCorpusFound": "कोणताही कायदेशीर पुरावा आढळला नाही",
  "evidence.noCorpusHint": "आपले शोध निकष बदला किंवा फिल्टर हटवा.",

  # caseDetail (26 keys)
  "caseDetail.loading": "वैधानिक माहिती लोड होत आहे...",
  "caseDetail.notFound": "प्रकरण आढळले नाही",
  "caseDetail.notFoundDesc": "विनंती केलेले प्रकरण अस्तित्वात नाही किंवा हटवले गेले आहे.",
  "caseDetail.returnWorkspace": "प्रकरण कार्यक्षेत्रावर परत जा",
  "caseDetail.juryDemo": "ज्युरी प्रात्यक्षिक मोड",
  "caseDetail.simulateMissing": "गहाळ कागदपत्रांचे अनुकरण करा",
  "caseDetail.exportDossier": "प्रकरण डॉसियर निर्यात करा",
  "caseDetail.timeMachine": "नियामक टाइम मशीन",
  "caseDetail.editFormulation": "फॉर्म्युलेशन संपादित करा",
  "caseDetail.tabSummary": "सारांश आणि निकाल",
  "caseDetail.tabDna": "फॉर्म्युलेशन DNA",
  "caseDetail.tabClassifications": "उमेदवार वर्गवारी",
  "caseDetail.tabRegulations": "लागू नियमने",
  "caseDetail.tabIpPathways": "बौद्धिक संपदा मार्ग",
  "caseDetail.tabAbs": "ABS अनुपालन",
  "caseDetail.tabPriorArt": "पूर्व-कला विश्लेषण",
  "caseDetail.tabEvidenceGaps": "पुरावा अंतर",
  "caseDetail.tabEvidenceChain": "वैधानिक पुरावा साखळी",
  "caseDetail.tabNextActions": "पुढील शिफारस केलेल्या कृती",
  "caseDetail.classificationVerdict": "वर्गवारी निकाल",
  "caseDetail.evidenceStrength": "पुराव्याचे बळकटपण",
  "caseDetail.governingAuthority": "नियामक प्राधिकरण",
  "caseDetail.statutoryBasis": "वैधानिक आधार",
  "caseDetail.coreExcerpt": "प्रमुख कायदेशीर उतारा",
  "caseDetail.plainExplanation": "सोपे स्पष्टीकरण",
  "caseDetail.whyThis": "ही वर्गवारी का लागू होते?",

  # auth (6 keys)
  "auth.showPassword": "पासवर्ड दाखवा",
  "auth.hidePassword": "पासवर्ड लपवा",
  "auth.charRequirement": "8+ अक्षरे",
  "auth.upperRequirement": "कमीत कमी एक मोठे अक्षर (Uppercase)",
  "auth.numRequirement": "कमीत कमी एक अंक (Number)",
  "auth.demoAdmin": "नमुना व्यवस्थापक (Admin) क्रेडेंशियल्स वापरा",

  # intel (21 keys)
  "intel.drawerTitle": "वैधानिक पुरावा ड्रॉवर",
  "intel.authority": "नियामक प्राधिकरण",
  "intel.hierarchy": "कायदेशीर प्राधान्य क्रम",
  "intel.version": "अधिकृत आवृत्ती",
  "intel.excerpt": "कायदेशीर उतारा",
  "intel.plainSummary": "सोपा कायदेशीर सारांश",
  "intel.gazetteSource": "राजपत्र स्रोत",
  "intel.openExternal": "अधिकृत राजपत्र उघडा",
  "intel.closeDrawer": "ड्रॉवर बंद करा",
  "intel.gapsTitle": "पुरावा अंतर आणि निराकरण धोरण",
  "intel.resolutionStrategy": "निराकरण धोरण",
  "intel.chainTitle": "वैधानिक पुरावा साखळी",
  "intel.factTriggered": "सक्रिय वस्तुस्थिती",
  "intel.ruleApplied": "लागू केलेला नियम",
  "intel.matrixTitle": "वैधानिक बुद्धिमत्ता फलक (Intelligence Board)",
  "intel.timeMachineTitle": "नियामक टाइम मशीन",
  "intel.historicalAmendments": "ऐतिहासिक सुधारणा",
  "intel.uploadTitle": "सहाय्यक कागदपत्रे अपलोड करा",
  "intel.dragDrop": "कागदपत्रे येथे ड्रॅग आणि ड्रॉप करा किंवा ब्राउझ करा",
  "intel.whyTitle": "आपण हे का पाहत आहात?",
  "intel.deterministicVerification": "निश्चित वैधानिक पडताळणी",

  # search (10 keys)
  "search.breadcrumb": "शोध",
  "search.heading": "वैधानिक आणि पेटंट शोध",
  "search.btnSearch": "शोध",
  "search.suggestedLabel": "सुचवलेले शोध प्रश्न",
  "search.recentLabel": "अलीकडील शोध",
  "search.clearLabel": "साफ करा",
  "search.advancedFilters": "प्रगत फिल्टर्स",
  "search.hideAdvancedFilters": "प्रगत फिल्टर्स लपवा",
  "search.allAuthorities": "सर्व प्राधिकरणे",
  "search.allJurisdictions": "सर्व कार्यक्षेत्रे",

  # assistant (8 keys)
  "assistant.breadcrumb": "AI सहाय्यक",
  "assistant.bannerActive": "सक्रिय प्रकरणाच्या संदर्भात कार्यरत",
  "assistant.suggestedInquiries": "सुचवलेले प्रश्न",
  "assistant.directAnswer": "थेट वैधानिक उत्तर",
  "assistant.ruleConstraints": "लागू नियम आणि निर्बंध",
  "assistant.officialCitations": "अधिकृत कायदेशीर संदर्भ",
  "assistant.evidenceGaps": "आढळलेले पुरावा अंतर",
  "assistant.disclaimerFooter": "कायदेशीर अस्वीकरण: ही प्रणाली केवळ माहितीच्या उद्देशाने वैधानिक मार्गदर्शन प्रदान करते.",

  # report (9 keys)
  "report.returnDossier": "प्रकरण डॉसियरवर परत जा",
  "report.tableIngredients": "फॉर्म्युलेशन घटक आणि तपशील",
  "report.name": "घटकाचे नाव",
  "report.botanical": "वनस्पतीशास्त्रीय नाव",
  "report.sanskrit": "संस्कृत नाव",
  "report.part": "वापरलेला भाग",
  "report.percentage": "प्रमाण / टक्केवारी",
  "report.source": "संदर्भ स्रोत",
  "report.origin": "भौगोलिक मूळ",

  # cases (2 keys)
  "cases.noMatch": "आपल्या शोधाशी जुळणारे कोणतेही प्रकरण आढळले नाही.",
  "cases.jurisdictionIndia": "भारत (राष्ट्रीय)"
}

if __name__ == "__main__":
    update_language_dict("mr", MR_TRANSLATIONS)
