# -*- coding: utf-8 -*-
"""
IP-SAKTI Sahayak — Indic Pack 1: Bengali (bn), Gujarati (gu), Punjabi (pa), Odia (or), Assamese (as)
"""

import json
from updater import update_language_dict
from build_marathi import MR_TRANSLATIONS

# Template dictionary keys
KEYS = list(MR_TRANSLATIONS.keys())

BN_MAP = {
  "home.workflow.mostUsed": "সর্বাধিক ব্যবহৃত",
  "home.hero.multilingual": "বহুভাষিক সমর্থন",
  "home.hero.multilingual_title": "২২টি ভারতীয় ভাষা + ইংরেজিতে উপলব্ধ",
  "home.hero.multilingual_desc": "সম্পূর্ণ প্ল্যাটফর্ম — AI উত্তর, প্রমাণ কার্ড এবং শ্রেণিবিন্যাস ব্যাখ্যা সহ — ভারতের সমস্ত ২২টি সরকারি ভাষায় এবং ইংরেজিতে উপলব্ধ। সংবিধিবদ্ধ ও আইনি শর্তাবলী তাদের মূল প্রামাণিক রূপে সংরক্ষিত রয়েছে।",
  "home.features.versioning_updates": "সংস্করণ আপডেট",
  "home.features.abstention_protects": "নিরাপদ বিরত সুরক্ষা",
  "home.workflows.heading": "আপনি কি করতে চান?",
  "home.intake.ayurvedicFormulation": "আয়ুর্বেদিক যোগ (ফর্মুলেশন)",
  "home.intake.ayurvedicFormulationHint": "শাস্ত্রীয় বা মালিকানাধীন বহু-ভেষজ মিশ্রণ",
  "home.intake.herbalProduct": "ভেষজ পণ্য",
  "home.intake.herbalProductHint": "নির্যাস, খাদ্য সম্পূরক, ফাইটোমেডিসিন",
  "home.intake.plantResource": "উদ্ভিদ / জৈব সম্পদ",
  "home.intake.plantResourceHint": "ঔষধি উদ্ভিদ, ABS/NBA পূর্ব-অনুমোদন",
  "home.intake.traditionalKnowledge": "ঐতিহ্যগত জ্ঞান",
  "home.intake.traditionalKnowledgeHint": "শাস্ত্রীয় গ্রন্থ, TKDL পূর্ব-শিল্প পর্যালোচনা",
  "home.intake.novelProcess": "নতুন প্রক্রিয়া",
  "home.intake.novelProcessHint": "নিষ্কাশন, স্থিতিশীলকরণ এবং Section 3(p) যাচাইকরণ",
  "home.intake.brandIdentity": "ব্র্যান্ড পরিচয়",
  "home.intake.brandIdentityHint": "ট্রেডমার্ক, শ্রেণী ৫/৩/৩০/৪৪",
  "home.intake.geographicalIdentity": "ভৌগোলিক পরিচয়",
  "home.intake.geographicalIdentityHint": "GI নির্দেশক, মূল শংসাপত্র",
  "home.intake.regulatoryQuestion": "নিয়ন্ত্রক প্রশ্ন",
  "home.intake.regulatoryQuestionHint": "FSSAI, AYUSH, Rule 158B, Schedule T",
  "home.demo.badge": "লাইভ সংবিধিবদ্ধ মহড়া",
  "home.demo.simulation": "নিয়ন্ত্রক সিমুলেশন",
  "home.demo.title": "কাঁচা ধারণা থেকে আইনি সুরক্ষা পর্যন্ত",
  "home.demo.story": "অশ্বগন্ধা-ব্রাহ্মী সিরাপ কীভাবে বিশ্লেষণ করা হয় তা দেখুন: Section 3(p) পূর্ব-শিল্প, Rule 158B সম্মতি, FSSAI আয়ুষ আহার শ্রেণিবিন্যাস এবং ABS পূর্ব-অনুমোদন প্রয়োজনীয়তা।",
  "home.demo.notice": "সমস্ত সুপারিশ সরাসরি সরকারি গেজেটের আইনি বিধানের সাথে সংযুক্ত।",
  "home.demo.startCase": "এই মামলা শুরু করুন",
  "home.demo.inspectDossier": "নমুনা ডসিয়ার পরীক্ষা করুন",
  "home.demo.step1.label": "উপাদান বিশ্লেষণ",
  "home.demo.step1.sub": "অশ্বগন্ধা + ব্রাহ্মী সিরাপ",
  "home.demo.step2.label": "TKDL অনুসন্ধান",
  "home.demo.step2.sub": "ভাবপ্রকাশ এবং চরক সংহিতা উদ্ধৃতি",
  "home.demo.step3.label": "Section 3(p) ঝুঁকি",
  "home.demo.step3.sub": "ঐতিহ্যগত জ্ঞান পেটেন্ট বর্জন",
  "home.demo.step4.label": "Rule 158B যাচাইকরণ",
  "home.demo.step4.sub": "শাস্ত্রীয় গ্রন্থ প্রমাণ পথ",
  "home.demo.step5.label": "FSSAI বনাম AYUSH",
  "home.demo.step5.sub": "আয়ুষ আহার শ্রেণিবিন্যাস বিকল্প",
  "home.demo.step6.label": "NBA / ABS অনুমোদন",
  "home.demo.step6.sub": "Form III জৈব সম্পদ আবেদন",
  "home.demo.step7.label": "কর্ম পরিকল্পনা",
  "home.demo.step7.sub": "সুরক্ষা কৌশল এবং ফাইলিং",
  "home.evidence.sample": "নমুনা সংবিধিবদ্ধ প্রমাণ",
  "home.evidence.actIndia": "পেটেন্ট আইন ১৯৭০ (ভারত)",
  "home.evidence.strength": "আইনি প্রমাণের শক্তি",
  "home.evidence.high": "উচ্চ",
  "home.evidence.whyRelevant": "কেন এটি প্রযোজ্য: যদি কোনো দাবি ঐতিহ্যগত জ্ঞানের নিছক সমষ্টি হয়, তবে Section 3(p) এর অধীনে পেটেন্ট প্রত্যাখ্যান করা হয়।",
  "home.evidence.viewSource": "সরকারি উৎস দেখুন",
  "home.evidence.disclaimer": "এই অংশটি ডিজিটালভাবে স্বাক্ষরিত ভারত সরকারের গেজেট থেকে যাচাই করা হয়েছে।",
  "home.multilingual.badge": "২২টি ভাষা + ইংরেজি",
  "home.multilingual.fullSupport": "ভারতের সমস্ত ২২টি সরকারি ভাষায় সম্পূর্ণ সমর্থন",
  "home.multilingual.more": "আরও ভাষা",
  "home.multilingual.all22": "ভারতীয় সংবিধানের অষ্টম তফসিলে উল্লেখিত সমস্ত ২২টি ভাষায় উপলব্ধ",
  "home.domain.patent": "পেটেন্ট (ধারা ৩(p) এবং ৩(e))",
  "home.domain.patentDesc": "ঐতিহ্যগত জ্ঞান বর্জন, অভিনবত্ব এবং পূর্ব-শিল্প বিশ্লেষণ।",
  "home.domain.trademark": "ট্রেডমার্ক",
  "home.domain.trademarkDesc": "আয়ুর্বেদিক ব্র্যান্ড, লোগো, ক্লাস ৫ এবং ঔষধি শ্রেণিবিন্যাস নিবন্ধন।",
  "home.domain.gi": "ভৌগোলিক নির্দেশক (GI)",
  "home.domain.giDesc": "স্থানীয় উদ্ভিদ এবং ঐতিহ্যবাহী ঔষধি পদ্ধতির সুরক্ষা।",
  "home.domain.plantVariety": "উদ্ভিদ জাত সুরক্ষা (PPV&FR)",
  "home.domain.plantVarietyDesc": "কৃষক অধিকার এবং ঔষধি উদ্ভিদের জাত নিবন্ধন।",
  "home.domain.copyright": "কপিরাইট",
  "home.domain.copyrightDesc": "গবেষণা নথিপত্র, শাস্ত্রীয় ভাষ্য এবং ডিজিটাল ডাটাবেস সুরক্ষা।",
  "home.domain.industrialDesign": "শিল্প নকশা",
  "home.domain.industrialDesignDesc": "ওষুধ সরবরাহকারী সরঞ্জাম, বোতল এবং প্যাকেজিং ডিজাইন।",
  "home.domain.tk": "ঐতিহ্যগত জ্ঞান (TKDL)",
  "home.domain.tkDesc": "আয়ুর্বেদ, সিদ্ধ ও ইউনানী জ্ঞানের আন্তর্জাতিক সুরক্ষা।",
  "home.domain.abs": "জৈব বৈচিত্র্য ও ABS",
  "home.domain.absDesc": "জাতীয় জীববৈচিত্র্য কর্তৃপক্ষ (NBA) Form III অনুমোদন।",
  "home.domain.ayush": "আয়ুষ (AYUSH) নিয়মকানুন",
  "home.domain.ayushDesc": "ওষুধ ও প্রসাধন সামগ্রী আইন, শাস্ত্রীয় গ্রন্থ রেফারেন্স।",
  "home.domain.fssaiDesc": "আয়ুষ আহার নিয়মকানুন, পুষ্টি সম্পূরক ও নিরাপত্তা মানদণ্ড।",
  "home.domain.drugsCosmetics": "ওষুধ ও প্রসাধন সামগ্রী আইন",
  "home.domain.drugsCosmeticsDesc": "Rule 158B প্রমাণ এবং Schedule T জিএমপি মানদণ্ড।",
  "home.domain.internationalIp": "আন্তর্জাতিক বৌদ্ধিক সম্পদ",
  "home.domain.internationalIpDesc": "PCT, প্যারিস কনভেনশন এবং নাগোয়া প্রটোকল।",
  "home.pipeline.question": "প্রশ্ন",
  "home.pipeline.classify": "শ্রেণিবিন্যাস",
  "home.pipeline.evidence": "প্রমাণ",
  "home.pipeline.intelligence": "ইন্টেলিজেন্স",
  "home.pipeline.action": "পদক্ষেপ",
  "home.domain.plantVarietyProtection": "উদ্ভিদ জাত সুরক্ষা",
  "nav.quick.herbalPatent": "ভেষজ পেটেন্ট যোগ্যতা",
  "nav.quick.fssaiRules": "FSSAI আয়ুষ আহার নিয়ম",
  "nav.quick.giProtection": "ঔষধি উদ্ভিদের GI সুরক্ষা",
  "nav.quick.absNagoya": "ABS নাগোয়া প্রটোকল সম্মতি",
  "nav.quick.section3p": "Section 3(p) ঐতিহ্যগত জ্ঞান বর্জন",
  "nav.quick.tkNeem": "নিম ও হলুদ পেটেন্ট বিরোধিতা",
  "wizard.stepProgress": "ধাপের অগ্রগতি",
  "wizard.stepPrev": "পূর্ববর্তী ধাপ",
  "wizard.stepNext": "পরবর্তী ধাপ",
  "wizard.stepSaveRoadmap": "মামলা সংরক্ষণ করুন এবং রোডম্যাপ তৈরি করুন",
  "wizard.backToCases": "আমার মামলায় ফিরে যান",
  "wizard.guidedSetup": "নির্দেশিত বৌদ্ধিক সম্পদ ও নিয়ন্ত্রক সেটআপ",
  "wizard.gap.title": "প্রমাণের ফাঁক সনাক্ত করা হয়েছে",
  "wizard.gap.desc": "এই যোগ প্রকারের জন্য নির্দিষ্ট শাস্ত্রীয় প্রমাণের প্রয়োজন হতে পারে।",
  "wizard.gap.fix": "কীভাবে প্রমাণের ফাঁক পূরণ করবেন তা দেখুন",
  "wizard.validation.titleRequired": "ফর্মুলেশনের শিরোনাম আবশ্যক",
  "wizard.dnaReady": "ফর্মুলেশন DNA প্রস্তুত",
  "wizard.ingIndex": "উপাদান",
  "wizard.assetNature": "সম্পদের প্রকৃতি",
  "wizard.selectTreatises": "স্বীকৃত শাস্ত্রীয় গ্রন্থ নির্বাচন করুন",
  "wizard.classicalCitation": "শাস্ত্রীয় রেফারেন্স / শ্লোক উদ্ধৃতি",
  "wizard.indicationsLabel": "চিকিৎসা নির্দেশাবলী / রোগাধিকার",
  "wizard.indicationsPlaceholder": "যেমন: কাস, শ্বাস, জ্বর, রসায়ন...",
  "wizard.prepNarrative": "প্রস্তুতি পদ্ধতির বিবরণ",
  "wizard.prepNarrativePlaceholder": "শোধন, ভাবনা বা নিষ্কাশন প্রক্রিয়ার বিস্তারিত বর্ণনা দিন...",
  "wizard.commercialPathway": "বাণিজ্যিক পথ",
  "wizard.targetJurisdictionTitle": "লক্ষ্য এখতিয়ার",
  "wizard.supportingDocsTitle": "সহায়ক নথি এবং প্রমাণ",
  "wizard.docAddPlaceholder": "নথির নাম বা রেফারেন্স লিখুন...",
  "wizard.addDocBtn": "নথি যোগ করুন",
  "wizard.plantPart": "ব্যবহৃত উদ্ভিদের অংশ",
  "wizard.sourcingType": "উৎসের ধরন",
  "wizard.cat.ayurvedic": "আয়ুর্বেদিক যোগ",
  "wizard.cat.ayurvedicDesc": "ঐতিহ্যবাহী বা মালিকানাধীন ওষুধ",
  "wizard.cat.herbal": "ভেষজ পণ্য",
  "wizard.cat.herbalDesc": "উদ্ভিদ নির্যাস বা সম্পূরক",
  "wizard.cat.traditional": "ঐতিহ্যগত জ্ঞান",
  "wizard.cat.traditionalDesc": "ঐতিহ্যবাহী অনুশীলন বা গ্রন্থ",
  "wizard.cat.plant": "জৈব সম্পদ",
  "wizard.cat.plantDesc": "উদ্ভিদ বা জৈব উপাদান",
  "wizard.cat.process": "নতুন প্রক্রিয়া",
  "wizard.cat.processDesc": "নিষ্কাশন বা উৎপাদন পদ্ধতি",
  "wizard.cat.brand": "ব্র্যান্ড বা পণ্যের নাম",
  "wizard.cat.brandDesc": "ট্রেডমার্ক সুরক্ষা",
  "wizard.prep.classical": "শাস্ত্রীয় পদ্ধতি",
  "wizard.prep.classicalDesc": "অনুমোদিত সংহিতা অনুসারে প্রস্তুত",
  "wizard.prep.extract": "মানসম্মত নির্যাস",
  "wizard.prep.extractDesc": "সক্রিয় উপাদানের জলীয় বা অ্যালকোহল নির্যাস",
  "wizard.prep.novel": "নতুন প্রযুক্তি",
  "wizard.prep.novelDesc": "ন্যানোপার্টিকেল বা উন্নত ডেলিভারি সিস্টেম",
  "wizard.commercial.domestic": "গার্হস্থ্য ভারতীয় বাজার",
  "wizard.commercial.domesticDesc": "ভারতে উৎপাদন ও বিক্রয়",
  "wizard.commercial.export": "আন্তর্জাতিক রপ্তানি",
  "wizard.commercial.exportDesc": "বিশ্ববাজারে বিক্রয়",
  "wizard.commercial.rd": "গবেষণা ও উন্নয়ন",
  "wizard.commercial.rdDesc": "প্রাক-ক্লিনিকাল বা ক্লিনিকাল ট্রায়াল",
  "wizard.commercial.licensing": "প্রযুক্তি লাইসেন্সিং",
  "wizard.commercial.licensingDesc": "তৃতীয় পক্ষকে লাইসেন্স প্রদান",
  "wizard.jur.india": "ভারত",
  "wizard.jur.indiaDesc": "ভারতীয় পেটেন্ট ও নিয়ন্ত্রক আইন",
  "wizard.jur.us": "মার্কিন যুক্তরাষ্ট্র",
  "wizard.jur.usDesc": "US FDA এবং USPTO নিয়ম",
  "wizard.jur.eu": "ইউরোপীয় ইউনিয়ন",
  "wizard.jur.euDesc": "EMA এবং EPO নিয়মকানুন",
  "wizard.jur.intl": "আন্তর্জাতিক (PCT)",
  "wizard.jur.intlDesc": "গ্লোবাল পেটেন্ট কোঅপারেশন চুক্তি",
  "wizard.claim.therapeutic": "থেরাপিউটিক দাবি",
  "wizard.claim.nutritional": "পুষ্টি বা খাদ্যতালিকাগত দাবি",
  "wizard.claim.cosmetic": "প্রসাধন দাবি",
  "wizard.claim.wellness": "সাধারণ স্বাস্থ্য ও সুস্থতা",
  "explore.breadcrumb": "নিয়ন্ত্রক কাঠামো অন্বেষণ করুন",
  "explore.searchPlaceholder": "ফর্মুলেশন, পেটেন্ট, Section 3(p), Rule 158B, ABS, TKDL অনুসন্ধান করুন...",
  "explore.allFrameworks": "সমস্ত নিয়ন্ত্রক কাঠামো",
  "explore.ipPatents": "IP এবং পেটেন্টস",
  "explore.ayushFssai": "আয়ুষ এবং FSSAI",
  "explore.bioAbs": "জীববৈচিত্র্য এবং ABS",
  "explore.tkTkdl": "ঐতিহ্যগত জ্ঞান এবং TKDL",
  "explore.statutoryHighlights": "সংবিধিবদ্ধ হাইলাইটস",
  "explore.noItems": "নির্বাচিত বিভাগে কোনো নিয়ন্ত্রক কাঠামো পাওয়া যায়নি।",
  "explore.actSec3p": "পেটেন্ট আইন ১৯৭০ — ধারা ৩(p) এবং ৩(e)",
  "explore.actRule158b": "ওষুধ ও প্রসাধন সামগ্রী বিধি ১৯৪৫ — বিধি ১৫৮B",
  "explore.actAbs": "জৈব বৈচিত্র্য আইন ২০০২ — Form III ABS",
  "explore.actAahar": "আয়ুষ আহার নিয়মকানুন ২০২২ — FSSAI কাঠামো",
  "explore.actTkdl": "ঐতিহ্যগত জ্ঞান ডিজিটাল লাইব্রেরি (TKDL) কাঠামো",
  "explore.actGi": "ভৌগোলিক নির্দেশক (নিবন্ধন ও সুরক্ষা) আইন ১৯৯৯",
  "evidence.breadcrumb": "সংবিধিবদ্ধ প্রমাণ সংগ্রহ",
  "evidence.allAuthorities": "সমস্ত নিয়ন্ত্রক কর্তৃপক্ষ",
  "evidence.allTypes": "সমস্ত সংবিধিবদ্ধ প্রকার",
  "evidence.act": "আইন (Act)",
  "evidence.rule": "বিধি (Rule)",
  "evidence.gazetteNotification": "গেজেট বিজ্ঞপ্তি",
  "evidence.pharmacopoeialStandard": "ফার্মাকোপিয়াল মানদণ্ড",
  "evidence.treaty": "আন্তর্জাতিক চুক্তি",
  "evidence.verifiedAuthority": "যাচাইকৃত নিয়ন্ত্রক কর্তৃপক্ষ",
  "evidence.cryptoHash": "ক্রিপ্টোগ্রাফিক ফরেনসিক হ্যাশ",
  "evidence.plainSummary": "সহজ সারাংশ",
  "evidence.officialExcerpt": "অফিসিয়াল সংবিধিবদ্ধ উদ্ধৃতি",
  "evidence.inspectCitation": "আইনি উদ্ধৃতি পরীক্ষা করুন",
  "evidence.noCorpusFound": "কোনো সংবিধিবদ্ধ প্রমাণ পাওয়া যায়নি",
  "evidence.noCorpusHint": "আপনার অনুসন্ধানের শর্ত পরিবর্তন করুন বা ফিল্টার সাফ করুন।",
  "caseDetail.loading": "সংবিধিবদ্ধ তথ্য লোড হচ্ছে...",
  "caseDetail.notFound": "মামলা পাওয়া যায়নি",
  "caseDetail.notFoundDesc": "অনুরোধ করা মামলার রেকর্ড বিদ্যমান নেই বা সরানো হয়েছে।",
  "caseDetail.returnWorkspace": "মামলা ওয়ার্কস্পেসে ফিরে যান",
  "caseDetail.juryDemo": "জুরি ডেমো মোড",
  "caseDetail.simulateMissing": "অনুপস্থিত নথি অনুকরণ করুন",
  "caseDetail.exportDossier": "মামলা ডসিয়ার রপ্তানি করুন",
  "caseDetail.timeMachine": "নিয়ন্ত্রক টাইম মেশিন",
  "caseDetail.editFormulation": "ফর্মুলেশন সম্পাদনা করুন",
  "caseDetail.tabSummary": "সারসংক্ষেপ ও রায়",
  "caseDetail.tabDna": "ফর্মুলেশন DNA",
  "caseDetail.tabClassifications": "প্রার্থী শ্রেণিবিন্যাস",
  "caseDetail.tabRegulations": "প্রযোজ্য বিধিমালা",
  "caseDetail.tabIpPathways": "আইপি পথ",
  "caseDetail.tabAbs": "ABS সম্মতি",
  "caseDetail.tabPriorArt": "পূর্ব-শিল্প বিশ্লেষণ",
  "caseDetail.tabEvidenceGaps": "প্রমাণের ফাঁক",
  "caseDetail.tabEvidenceChain": "সংবিধিবদ্ধ প্রমাণ শৃঙ্খল",
  "caseDetail.tabNextActions": "পরবর্তী প্রস্তাবিত পদক্ষেপ",
  "caseDetail.classificationVerdict": "শ্রেণিবিন্যাস রায়",
  "caseDetail.evidenceStrength": "প্রমাণের শক্তি",
  "caseDetail.governingAuthority": "নিয়ন্ত্রক কর্তৃপক্ষ",
  "caseDetail.statutoryBasis": "সংবিধিবদ্ধ ভিত্তি",
  "caseDetail.coreExcerpt": "মূল আইনি উদ্ধৃতি",
  "caseDetail.plainExplanation": "সহজ ব্যাখ্যা",
  "caseDetail.whyThis": "কেন এই শ্রেণিবিন্যাস প্রযোজ্য?",
  "auth.showPassword": "পাসওয়ার্ড দেখান",
  "auth.hidePassword": "পাসওয়ার্ড লুকান",
  "auth.charRequirement": "৮+ অক্ষর",
  "auth.upperRequirement": "বড় হাতের অক্ষর (Uppercase)",
  "auth.numRequirement": "সংখ্যা (Number)",
  "auth.demoAdmin": "ডেমো অ্যাডমিন শংসাপত্র ব্যবহার করুন",
  "intel.drawerTitle": "সংবিধিবদ্ধ প্রমাণ ড্রয়ার",
  "intel.authority": "নিয়ন্ত্রক কর্তৃপক্ষ",
  "intel.hierarchy": "আইনি অগ্রাধিকার স্তরক্রম",
  "intel.version": "অফিসিয়াল সংস্করণ",
  "intel.excerpt": "আইনি উদ্ধৃতি",
  "intel.plainSummary": "সহজ আইনি সারাংশ",
  "intel.gazetteSource": "গেজেট উৎস",
  "intel.openExternal": "অফিসিয়াল গেজেট খুলুন",
  "intel.closeDrawer": "ড্রয়ার বন্ধ করুন",
  "intel.gapsTitle": "প্রমাণের ফাঁক ও সমাধান কৌশল",
  "intel.resolutionStrategy": "সমাধান কৌশল",
  "intel.chainTitle": "সংবিধিবদ্ধ প্রমাণ শৃঙ্খল",
  "intel.factTriggered": "সক্রিয় ঘটনা",
  "intel.ruleApplied": "প্রয়োগকৃত বিধি",
  "intel.matrixTitle": "সংবিধিবদ্ধ বুদ্ধিমত্তা বোর্ড (Intelligence Board)",
  "intel.timeMachineTitle": "নিয়ন্ত্রক টাইম মেশিন",
  "intel.historicalAmendments": "ঐতিহাসিক সংশোধনী",
  "intel.uploadTitle": "সহায়ক নথি আপলোড করুন",
  "intel.dragDrop": "নথি এখানে টেনে আনুন বা ব্রাউজ করুন",
  "intel.whyTitle": "আপনি কেন এটি দেখছেন?",
  "intel.deterministicVerification": "নির্ধারিত সংবিধিবদ্ধ যাচাইকরণ",
  "search.breadcrumb": "অনুসন্ধান",
  "search.heading": "সংবিধিবদ্ধ এবং পেটেন্ট অনুসন্ধান",
  "search.btnSearch": "অনুসন্ধান",
  "search.suggestedLabel": "প্রস্তাবিত প্রশ্নাবলী",
  "search.recentLabel": "সাম্প্রতিক অনুসন্ধান",
  "search.clearLabel": "মুছে ফেলুন",
  "search.advancedFilters": "উন্নত ফিল্টার",
  "search.hideAdvancedFilters": "উন্নত ফিল্টার লুকান",
  "search.allAuthorities": "সমস্ত কর্তৃপক্ষ",
  "search.allJurisdictions": "সমস্ত এখতিয়ার",
  "assistant.breadcrumb": "AI সহকারী",
  "assistant.bannerActive": "সক্রিয় মামলার প্রসঙ্গে কর্মরত",
  "assistant.suggestedInquiries": "প্রস্তাবিত অনুসন্ধান",
  "assistant.directAnswer": "সরাসরি সংবিধিবদ্ধ উত্তর",
  "assistant.ruleConstraints": "প্রযোজ্য বিধিনিষেধ",
  "assistant.officialCitations": "অফিসিয়াল আইনি উদ্ধৃতি",
  "assistant.evidenceGaps": "শনাক্ত করা প্রমাণের ফাঁক",
  "assistant.disclaimerFooter": "আইনি দাবিত্যাগ: এই ব্যবস্থা শুধুমাত্র তথ্যের উদ্দেশ্যে সংবিধিবদ্ধ নির্দেশিকা প্রদান করে।",
  "report.returnDossier": "মামলা ডসিয়ারে ফিরে যান",
  "report.tableIngredients": "ফর্মুলেশন উপাদান ও বিবরণ",
  "report.name": "উপাদানের নাম",
  "report.botanical": "উদ্ভিদতাত্ত্বিক নাম",
  "report.sanskrit": "সংস্কৃত নাম",
  "report.part": "ব্যবহৃত অংশ",
  "report.percentage": "অনুপাত / শতাংশ",
  "report.source": "রেফারেন্স উৎস",
  "report.origin": "ভৌগোলিক উৎস",
  "cases.noMatch": "আপনার অনুসন্ধানের সাথে মিলে যাওয়া কোনো মামলা পাওয়া যায়নি।",
  "cases.jurisdictionIndia": "ভারত (জাতীয়)"
}

GU_MAP = {
  "home.workflow.mostUsed": "સૌથી વધુ વપરાયેલ",
  "home.hero.multilingual": "બહુભાષી સમર્થન",
  "home.hero.multilingual_title": "22 ભારતીય ભાષાઓ + અંગ્રેજીમાં ઉપલબ્ધ",
  "home.hero.multilingual_desc": "સંપૂર્ણ પ્લેટફોર્મ — AI જવાબો, પુરાવા કાર્ડ્સ અને વર્ગીકરણ સમજૂતીઓ સાથે — ભારતની તમામ 22 સત્તાવાર ભાષાઓમાં અને અંગ્રેજીમાં ઉપલબ્ધ છે. કાયદાકીય શબ્દો તેમના સત્તાવાર સ્વરૂપમાં સાચવવામાં આવ્યા છે.",
  "home.features.versioning_updates": "આવૃત્તિ અપડેટ્સ",
  "home.features.abstention_protects": "સુરક્ષિત પરિહાર સંરક્ષણ",
  "home.workflows.heading": "તમે શું કરવા માંગો છો?",
  "home.intake.ayurvedicFormulation": "આયુર્વેદિક યોગ (ફોર્મ્યુલેશન)",
  "home.intake.ayurvedicFormulationHint": "શાસ્ત્રીય અથવા માલિકીનું બહુ-હર્બલ મિશ્રણ",
  "home.intake.herbalProduct": "હર્બલ ઉત્પાદન",
  "home.intake.herbalProductHint": "અર્ક, આહાર પૂરવણીઓ, ફાયટોમેડિસિન",
  "home.intake.plantResource": "વનસ્પતિ / જૈવિક સંસાધન",
  "home.intake.plantResourceHint": "ઔષધીય વનસ્પતિ, ABS/NBA પૂર્વ-મંજૂરી",
  "home.intake.traditionalKnowledge": "પરંપરાગત જ્ઞાન",
  "home.intake.traditionalKnowledgeHint": "શાસ્ત્રીય ગ્રંથો, TKDL પૂર્વ-કળા સમીક્ષા",
  "home.intake.novelProcess": "નવીન પ્રક્રિયા",
  "home.intake.novelProcessHint": "નિષ્કર્ષણ, સ્થિરીકરણ અને Section 3(p) ચકાસણી",
  "home.intake.brandIdentity": "બ્રાન્ડ ઓળખ",
  "home.intake.brandIdentityHint": "ટ્રેડમાર્ક, વર્ગ 5/3/30/44",
  "home.intake.geographicalIdentity": "ભૌગોલિક ઓળખ",
  "home.intake.geographicalIdentityHint": "GI નિર્દેશક, મૂળ પ્રમાણપત્ર",
  "home.intake.regulatoryQuestion": "નિયમનકારી પ્રશ્ન",
  "home.intake.regulatoryQuestionHint": "FSSAI, AYUSH, Rule 158B, Schedule T",
  "home.demo.badge": "લાઈવ વૈધાનિક નિદર્શન",
  "home.demo.simulation": "નિયમનકારી સિમ્યુલેશન",
  "home.demo.title": "કાચી વિભાવનાથી કાનૂની સંરક્ષણ સુધી",
  "home.demo.story": "અશ્વગંધા-બ્રાહ્મી સિરપનું વિશ્લેષણ કેવી રીતે થાય છે તે જુઓ: Section 3(p) પૂર્વ-કળા, Rule 158B પાલન, FSSAI આયુષ આહાર વર્ગીકરણ અને ABS પૂર્વ-મંજૂરી જરૂરીયાત.",
  "home.demo.notice": "તમામ ભલામણો સીધી સત્તાવાર સરકારી ગેઝેટની જોગવાઈઓ સાથે જોડાયેલ છે.",
  "home.demo.startCase": "આ કેસ શરૂ કરો",
  "home.demo.inspectDossier": "નમૂના ડોઝિયર તપાસો",
  "home.demo.step1.label": "ઘટક વિશ્લેષણ",
  "home.demo.step1.sub": "અશ્વગંધા + બ્રાહ્મી સિરપ",
  "home.demo.step2.label": "TKDL શોધ",
  "home.demo.step2.sub": "ભાવપ્રકાશ અને ચરક સંહિતા સંદર્ભ",
  "home.demo.step3.label": "Section 3(p) જોખમ",
  "home.demo.step3.sub": "પરંપરાગત જ્ઞાન પેટન્ટ બાકાત",
  "home.demo.step4.label": "Rule 158B ચકાસણી",
  "home.demo.step4.sub": "શાસ્ત્રીય ગ્રંથ પુરાવા માર્ગ",
  "home.demo.step5.label": "FSSAI વિરુદ્ધ AYUSH",
  "home.demo.step5.sub": "આયુષ આહાર વર્ગીકરણ વિકલ્પ",
  "home.demo.step6.label": "NBA / ABS મંજૂરી",
  "home.demo.step6.sub": "Form III જૈવિક સંસાધન અરજી",
  "home.demo.step7.label": "કાર્ય યોજના",
  "home.demo.step7.sub": "સંરક્ષણ વ્યૂહરચના અને ફાઇલિંગ",
  "home.evidence.sample": "નમૂના વૈધાનિક પુરાવો",
  "home.evidence.actIndia": "પેટન્ટ કાયદો 1970 (ભારત)",
  "home.evidence.strength": "કાનૂની પુરાવાની મજબૂતાઈ",
  "home.evidence.high": "ઉચ્ચ",
  "home.evidence.whyRelevant": "આ શા માટે લાગુ પડે છે: જો કોઈ દાવો પરંપરાગત જ્ઞાનનું માત્ર એકત્રીકરણ હોય, તો Section 3(p) હેઠળ પેટન્ટ નકારવામાં આવે છે.",
  "home.evidence.viewSource": "સત્તાવાર સ્ત્રોત જુઓ",
  "home.evidence.disclaimer": "આ અંશ ડિજિટલ રીતે હસ્તાક્ષરિત ભારતના ગેઝેટમાંથી ચકાસાયેલ છે.",
  "home.multilingual.badge": "22 ભાષાઓ + અંગ્રેજી",
  "home.multilingual.fullSupport": "ભારતની તમામ 22 સત્તાવાર ભાષાઓમાં સંપૂર્ણ સમર્થન",
  "home.multilingual.more": "વધુ ભાષાઓ",
  "home.multilingual.all22": "ભારતીય બંધારણની આઠમી અનુસૂચિની તમામ 22 ભાષાઓમાં ઉપલબ્ધ",
  "home.domain.patent": "પેટન્ટ (કલમ 3(p) અને 3(e))",
  "home.domain.patentDesc": "પરંપરાગત જ્ઞાન અપવાદ, નવીનતા અને પૂર્વ-કળા વિશ્લેષણ.",
  "home.domain.trademark": "ટ્રેડમાર્ક",
  "home.domain.trademarkDesc": "આયુર્વેદિક બ્રાન્ડ, લોગો, વર્ગ 5 અને ઔષધીય વર્ગીકરણ નોંધણી.",
  "home.domain.gi": "ભૌગોલિક સંકેત (GI)",
  "home.domain.giDesc": "સ્થાનિક વનસ્પતિ અને પરંપરાગત ઔષધીય પદ્ધતિઓનું સંરક્ષણ.",
  "home.domain.plantVariety": "વનસ્પતિ જાત સંરક્ષણ (PPV&FR)",
  "home.domain.plantVarietyDesc": "ખેડૂત અધિકાર અને ઔષધીય વનસ્પતિ જાતોની નોંધણી.",
  "home.domain.copyright": "કૉપિરાઇટ",
  "home.domain.copyrightDesc": "સંશોધન દસ્તાવેજો, શાસ્ત્રીય ટીકાઓ અને ડિજિટલ ડેટાબેઝ સંરક્ષણ.",
  "home.domain.industrialDesign": "ઔદ્યોગિક ડિઝાઇન",
  "home.domain.industrialDesignDesc": "દવા વિતરણ ઉપકરણો, બોટલ અને પેકેજિંગ ડિઝાઇન.",
  "home.domain.tk": "પરંપરાગત જ્ઞાન (TKDL)",
  "home.domain.tkDesc": "આયુર્વેદ, સિદ્ધ અને યુનાની જ્ઞાનનું આંતરરાષ્ટ્રીય સંરક્ષણ.",
  "home.domain.abs": "જૈવિક વિવિધતા અને ABS",
  "home.domain.absDesc": "રાષ્ટ્રીય જૈવવિવિધતા સત્તામંડળ (NBA) Form III મંજૂરી.",
  "home.domain.ayush": "આયુષ (AYUSH) નિયમો",
  "home.domain.ayushDesc": "દવાઓ અને સૌંદર્ય પ્રસાધનો કાયદો, શાસ્ત્રીય સંદર્ભો.",
  "home.domain.fssaiDesc": "આયુષ આહાર નિયમનો, પોષણ પૂરક અને સલામતી ધોરણો.",
  "home.domain.drugsCosmetics": "દવાઓ અને સૌંદર્ય પ્રસાધન કાયદો",
  "home.domain.drugsCosmeticsDesc": "Rule 158B પુરાવા અને Schedule T GMP ધોરણો.",
  "home.domain.internationalIp": "આંતરરાષ્ટ્રીય બૌદ્ધિક સંપત્તિ",
  "home.domain.internationalIpDesc": "PCT, પેરિસ કન્વેન્શન અને નાગોયા પ્રોટોકોલ.",
  "home.pipeline.question": "પ્રશ્ન",
  "home.pipeline.classify": "વર્ગીકરણ",
  "home.pipeline.evidence": "પુરાવો",
  "home.pipeline.intelligence": "ઇન્ટેલિજન્સ",
  "home.pipeline.action": "પગલું",
  "home.domain.plantVarietyProtection": "વનસ્પતિ જાત સંરક્ષણ",
  "nav.quick.herbalPatent": "હર્બલ પેટન્ટ યોગ્યતા",
  "nav.quick.fssaiRules": "FSSAI આયુષ આહાર નિયમો",
  "nav.quick.giProtection": "ઔષધીય વનસ્પતિઓનું GI સંરક્ષણ",
  "nav.quick.absNagoya": "ABS નાગોયા પ્રોટોકોલ પાલન",
  "nav.quick.section3p": "Section 3(p) પરંપરાગત જ્ઞાન અપવાદ",
  "nav.quick.tkNeem": "લીમડો અને હળદર પેટન્ટ વિરોધ",
  "wizard.stepProgress": "તબક્કાની પ્રગતિ",
  "wizard.stepPrev": "પાછલો તબક્કો",
  "wizard.stepNext": "આગળનો તબક્કો",
  "wizard.stepSaveRoadmap": "કેસ સાચવો અને રોડમેપ બનાવો",
  "wizard.backToCases": "મારા કેસ પર પાછા જાઓ",
  "wizard.guidedSetup": "માર્ગદર્શિત બૌદ્ધિક સંપત્તિ અને નિયમનકારી સેટઅપ",
  "wizard.gap.title": "પુરાવાનું અંતર મળ્યું",
  "wizard.gap.desc": "આ યોગ પ્રકાર માટે ચોક્કસ શાસ્ત્રીય સંદર્ભોની જરૂર પડી શકે છે.",
  "wizard.gap.fix": "પુરાવાનું અંતર કેવી રીતે ભરવું તે જુઓ",
  "wizard.validation.titleRequired": "ફોર્મ્યુલેશન શીર્ષક જરૂરી છે",
  "wizard.dnaReady": "ફોર્મ્યુલેશન DNA તૈયાર છે",
  "wizard.ingIndex": "ઘટક",
  "wizard.assetNature": "સંપત્તિનું સ્વરૂપ",
  "wizard.selectTreatises": "માન્ય શાસ્ત્રીય ગ્રંથો પસંદ કરો",
  "wizard.classicalCitation": "શાસ્ત્રીય સંદર્ભ / શ્લોક અવતરણ",
  "wizard.indicationsLabel": "ઉપચારાત્મક સંકેતો / રોગાધિકાર",
  "wizard.indicationsPlaceholder": "દા.ત. કાસ, શ્વાસ, જ્વર, રસાયન...",
  "wizard.prepNarrative": "બનાવવાની પદ્ધતિનું વર્ણન",
  "wizard.prepNarrativePlaceholder": "શોધન, ભાવના અથવા નિષ્કર્ષણ પ્રક્રિયાનું વિગતવાર વર્ણન કરો...",
  "wizard.commercialPathway": "વ્યાપારી માર્ગ",
  "wizard.targetJurisdictionTitle": "લક્ષ્ય અધિકારક્ષેત્ર",
  "wizard.supportingDocsTitle": "સહાયક દસ્તાવેજો અને પુરાવા",
  "wizard.docAddPlaceholder": "દસ્તાવેજનું નામ અથવા સંદર્ભ દાખલ કરો...",
  "wizard.addDocBtn": "દસ્તાવેજ ઉમેરો",
  "wizard.plantPart": "વપરાયેલ વનસ્પતિ ભાગ",
  "wizard.sourcingType": "સ્ત્રોત પ્રકાર",
  "wizard.cat.ayurvedic": "આયુર્વેદિક યોગ",
  "wizard.cat.ayurvedicDesc": "પરંપરાગત અથવા માલિકીની દવા",
  "wizard.cat.herbal": "હર્બલ ઉત્પાદન",
  "wizard.cat.herbalDesc": "વનસ્પતિ અર્ક અથવા પૂરક",
  "wizard.cat.traditional": "પરંપરાગત જ્ઞાન",
  "wizard.cat.traditionalDesc": "વારસાગત પદ્ધતિ અથવા ગ્રંથ",
  "wizard.cat.plant": "જૈવિક સંસાધન",
  "wizard.cat.plantDesc": "વનસ્પતિ અથવા જૈવ સામગ્રી",
  "wizard.cat.process": "નવીન પ્રક્રિયા",
  "wizard.cat.processDesc": "નિષ્કર્ષણ અથવા ઉત્પાદન પદ્ધતિ",
  "wizard.cat.brand": "બ્રાન્ડ અથવા ઉત્પાદન નામ",
  "wizard.cat.brandDesc": "ટ્રેડમાર્ક સંરક્ષણ",
  "wizard.prep.classical": "શાસ્ત્રીય વિધિ",
  "wizard.prep.classicalDesc": "સત્તાવાર સંહિતા અનુસાર બનાવેલ",
  "wizard.prep.extract": "પ્રમાણિત અર્ક",
  "wizard.prep.extractDesc": "સક્રિય ઘટકોનો જલીય/આલ્કોહોલિક અર્ક",
  "wizard.prep.novel": "નવીન ટેકનોલોજી",
  "wizard.prep.novelDesc": "નેનોપાર્ટિકલ્સ અથવા અદ્યતન ડિલિવરી સિસ્ટમ",
  "wizard.commercial.domestic": "સ્થાનિક ભારતીય બજાર",
  "wizard.commercial.domesticDesc": "ભારતમાં ઉત્પાદન અને વેચાણ",
  "wizard.commercial.export": "આંતરરાષ્ટ્રીય નિકાસ",
  "wizard.commercial.exportDesc": "વૈશ્વિક બજારમાં વેચાણ",
  "wizard.commercial.rd": "સંશોધન અને વિકાસ",
  "wizard.commercial.rdDesc": "પૂર્વ-ક્લિનિકલ અથવા ક્લિનિકલ ટ્રાયલ્સ",
  "wizard.commercial.licensing": "ટેકનોલોજી લાઇસન્સિંગ",
  "wizard.commercial.licensingDesc": "તૃતીય પક્ષને લાઇસન્સ આપવું",
  "wizard.jur.india": "ભારત",
  "wizard.jur.indiaDesc": "ભારતીય પેટન્ટ અને નિયમનકારી કાયદાઓ",
  "wizard.jur.us": "યુનાઇટેડ સ્ટેટ્સ",
  "wizard.jur.usDesc": "US FDA અને USPTO નિયમો",
  "wizard.jur.eu": "યુરોપિયન યુનિયન",
  "wizard.jur.euDesc": "EMA અને EPO નિયમો",
  "wizard.jur.intl": "આંતરરાષ્ટ્રીય (PCT)",
  "wizard.jur.intlDesc": "ગ્લોબલ પેટન્ટ સહકાર સંધિ",
  "wizard.claim.therapeutic": "ઉપચારાત્મક દાવો",
  "wizard.claim.nutritional": "પોષણ અથવા આહાર દાવો",
  "wizard.claim.cosmetic": "સૌંદર્ય પ્રસાધન દાવો",
  "wizard.claim.wellness": "સામાન્ય આરોગ્ય અને સુખાકારી",
  "explore.breadcrumb": "નિયમનકારી માળખું શોધો",
  "explore.searchPlaceholder": "ફોર્મ્યુલેશન, પેટન્ટ, Section 3(p), Rule 158B, ABS, TKDL શોધો...",
  "explore.allFrameworks": "તમામ નિયમનકારી માળખાં",
  "explore.ipPatents": "IP અને પેટન્ટ્સ",
  "explore.ayushFssai": "આયુષ અને FSSAI",
  "explore.bioAbs": "જૈવવિવિધતા અને ABS",
  "explore.tkTkdl": "પરંપરાગત જ્ઞાન અને TKDL",
  "explore.statutoryHighlights": "વૈધાનિક હાઇલાઇટ્સ",
  "explore.noItems": "પસંદ કરેલ શ્રેણીમાં કોઈ નિયમનકારી માળખું મળ્યું નથી.",
  "explore.actSec3p": "પેટન્ટ કાયદો 1970 — કલમ 3(p) અને 3(e)",
  "explore.actRule158b": "દવાઓ અને સૌંદર્ય પ્રસાધનો નિયમો 1945 — નિયમ 158B",
  "explore.actAbs": "જૈવિક વિવિધતા કાયદો 2002 — Form III ABS",
  "explore.actAahar": "આયુષ આહાર નિયમનો 2022 — FSSAI માળખું",
  "explore.actTkdl": "પરંપરાગત જ્ઞાન ડિજિટલ લાઇબ્રેરી (TKDL) માળખું",
  "explore.actGi": "ભૌગોલિક સંકેત (નોંધણી અને સંરક્ષણ) કાયદો 1999",
  "evidence.breadcrumb": "વૈધાનિક પુરાવા સંગ્રહ",
  "evidence.allAuthorities": "તમામ નિયમનકારી સત્તામંડળો",
  "evidence.allTypes": "તમામ વૈધાનિક પ્રકારો",
  "evidence.act": "કાયદો (Act)",
  "evidence.rule": "નિયમ (Rule)",
  "evidence.gazetteNotification": "ગેઝેટ જાહેરનામું",
  "evidence.pharmacopoeialStandard": "ફાર્માકોપિયલ ધોરણ",
  "evidence.treaty": "આંતરરાષ્ટ્રીય સંધિ",
  "evidence.verifiedAuthority": "ચકાસાયેલ નિયમનકારી સત્તામંડળ",
  "evidence.cryptoHash": "ક્રિપ્ટોગ્રાફિક ફોરેન્સિક હેશ",
  "evidence.plainSummary": "સરળ સારાંશ",
  "evidence.officialExcerpt": "સત્તાવાર વૈધાનિક અંશ",
  "evidence.inspectCitation": "કાનૂની સંદર્ભ તપાસો",
  "evidence.noCorpusFound": "કોઈ વૈધાનિક પુરાવો મળ્યો નથી",
  "evidence.noCorpusHint": "તમારા શોધ માપદંડ બદલો અથવા ફિલ્ટર્સ દૂર કરો.",
  "caseDetail.loading": "વૈધાનિક માહિતી લોડ થઈ રહી છે...",
  "caseDetail.notFound": "કેસ મળ્યો નથી",
  "caseDetail.notFoundDesc": "વિનંતી કરેલ કેસ રેકોર્ડ અસ્તિત્વમાં નથી અથવા દૂર કરવામાં આવ્યો છે.",
  "caseDetail.returnWorkspace": "કેસ વર્કસ્પેસ પર પાછા જાઓ",
  "caseDetail.juryDemo": "જ્યુરી ડેમો મોડ",
  "caseDetail.simulateMissing": "ગુમ થયેલ દસ્તાવેજોનું અનુકરણ કરો",
  "caseDetail.exportDossier": "કેસ ડોઝિયર નિકાસ કરો",
  "caseDetail.timeMachine": "નિયમનકારી ટાઇમ મશીન",
  "caseDetail.editFormulation": "ફોર્મ્યુલેશન સંપાદિત કરો",
  "caseDetail.tabSummary": "સારાંશ અને ચુકાદો",
  "caseDetail.tabDna": "ફોર્મ્યુલેશન DNA",
  "caseDetail.tabClassifications": "ઉમેદવાર વર્ગીકરણ",
  "caseDetail.tabRegulations": "લાગુ નિયમનો",
  "caseDetail.tabIpPathways": "બૌદ્ધિક સંપત્તિ માર્ગો",
  "caseDetail.tabAbs": "ABS પાલન",
  "caseDetail.tabPriorArt": "પૂર્વ-કળા વિશ્લેષણ",
  "caseDetail.tabEvidenceGaps": "પુરાવાનું અંતર",
  "caseDetail.tabEvidenceChain": "વૈધાનિક પુરાવા સાંકળ",
  "caseDetail.tabNextActions": "આગામી ભલામણ કરેલ પગલાં",
  "caseDetail.classificationVerdict": "વર્ગીકરણ ચુકાદો",
  "caseDetail.evidenceStrength": "પુરાવાની મજબૂતાઈ",
  "caseDetail.governingAuthority": "નિયમનકારી સત્તામંડળ",
  "caseDetail.statutoryBasis": "વૈધાનિક આધાર",
  "caseDetail.coreExcerpt": "મુખ્ય કાનૂની અંશ",
  "caseDetail.plainExplanation": "સરળ સમજૂતી",
  "caseDetail.whyThis": "આ વર્ગીકરણ શા માટે લાગુ પડે છે?",
  "auth.showPassword": "પાસવર્ડ બતાવો",
  "auth.hidePassword": "પાસવર્ડ છુપાવો",
  "auth.charRequirement": "8+ અક્ષરો",
  "auth.upperRequirement": "ઓછામાં ઓછો એક કેપિટલ અક્ષર (Uppercase)",
  "auth.numRequirement": "ઓછામાં ઓછો એક અંક (Number)",
  "auth.demoAdmin": "ડેમો એડમિન ઓળખપત્રો વાપરો",
  "intel.drawerTitle": "વૈધાનિક પુરાવા ડ્રોઅર",
  "intel.authority": "નિયમનકારી સત્તામંડળ",
  "intel.hierarchy": "કાનૂની અગ્રતા ક્રમ",
  "intel.version": "સત્તાવાર આવૃત્તિ",
  "intel.excerpt": "કાનૂની અંશ",
  "intel.plainSummary": "સરળ કાનૂની સારાંશ",
  "intel.gazetteSource": "ગેઝેટ સ્ત્રોત",
  "intel.openExternal": "સત્તાવાર ગેઝેટ ખોલો",
  "intel.closeDrawer": "ડ્રોઅર બંધ કરો",
  "intel.gapsTitle": "પુરાવાનું અંતર અને ઉકેલ વ્યૂહરચના",
  "intel.resolutionStrategy": "ઉકેલ વ્યૂહરચના",
  "intel.chainTitle": "વૈધાનિક પુરાવા સાંકળ",
  "intel.factTriggered": "સક્રિય હકીકત",
  "intel.ruleApplied": "લાગુ કરેલ નિયમ",
  "intel.matrixTitle": "વૈધાનિક ઇન્ટેલિજન્સ બોર્ડ",
  "intel.timeMachineTitle": "નિયમનકારી ટાઇમ મશીન",
  "intel.historicalAmendments": "ઐતિહાસિક સુધારા",
  "intel.uploadTitle": "સહાયક દસ્તાવેજો અપલોડ કરો",
  "intel.dragDrop": "દસ્તાવેજો અહીં ખેંચો અને મૂકો અથવા બ્રાઉઝ કરો",
  "intel.whyTitle": "તમે આ શા માટે જોઈ રહ્યા છો?",
  "intel.deterministicVerification": "ચોક્કસ વૈધાનિક ચકાસણી",
  "search.breadcrumb": "શોધ",
  "search.heading": "વૈધાનિક અને પેટન્ટ શોધ",
  "search.btnSearch": "શોધો",
  "search.suggestedLabel": "સૂચવેલા પ્રશ્નો",
  "search.recentLabel": "તાજેતરની શોધો",
  "search.clearLabel": "સાફ કરો",
  "search.advancedFilters": "અદ્યતન ફિલ્ટર્સ",
  "search.hideAdvancedFilters": "અદ્યતન ફિલ્ટર્સ છુપાવો",
  "search.allAuthorities": "તમામ સત્તામંડળો",
  "search.allJurisdictions": "તમામ અધિકારક્ષેત્રો",
  "assistant.breadcrumb": "AI સહાયક",
  "assistant.bannerActive": "સક્રિય કેસના સંદર્ભમાં કાર્યરત",
  "assistant.suggestedInquiries": "સૂચવેલા પ્રશ્નો",
  "assistant.directAnswer": "સીધો વૈધાનિક જવાબ",
  "assistant.ruleConstraints": "લાગુ નિયમો અને મર્યાદાઓ",
  "assistant.officialCitations": "સત્તાવાર કાનૂની સંદર્ભો",
  "assistant.evidenceGaps": "મળેલા પુરાવાના અંતરો",
  "assistant.disclaimerFooter": "કાનૂની અસ્વીકરણ: આ સિસ્ટમ માત્ર માહિતીના હેતુ માટે વૈધાનિક માર્ગદર્શન પૂરું પાડે છે.",
  "report.returnDossier": "કેસ ડોઝિયર પર પાછા જાઓ",
  "report.tableIngredients": "ફોર્મ્યુલેશન ઘટકો અને વિગતો",
  "report.name": "ઘટકનું નામ",
  "report.botanical": "વનસ્પતિશાસ્ત્રીય નામ",
  "report.sanskrit": "સંસ્કૃત નામ",
  "report.part": "વપરાયેલ ભાગ",
  "report.percentage": "પ્રમાણ / ટકાવારી",
  "report.source": "સંદર્ભ સ્ત્રોત",
  "report.origin": "ભૌગોલિક મૂળ",
  "cases.noMatch": "તમારી શોધ સાથે મેળ ખાતો કોઈ કેસ મળ્યો નથી.",
  "cases.jurisdictionIndia": "ભારત (રાષ્ટ્રીય)"
}

PA_MAP = {
  "home.workflow.mostUsed": "ਸਭ ਤੋਂ ਵੱਧ ਵਰਤਿਆ ਗਿਆ",
  "home.hero.multilingual": "ਬਹੁਭਾਸ਼ਾਈ ਸਹਾਇਤਾ",
  "home.hero.multilingual_title": "22 ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ + ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਉਪਲਬਧ",
  "home.hero.multilingual_desc": "ਪੂਰਾ ਪਲੇਟਫਾਰਮ — AI ਜਵਾਬਾਂ, ਸਬੂਤ ਕਾਰਡਾਂ ਅਤੇ ਵਰਗੀਕਰਨ ਸਪੱਸ਼ਟੀਕਰਨਾਂ ਸਮੇਤ — ਭਾਰਤ ਦੀਆਂ ਸਾਰੀਆਂ 22 ਅਧਿਕਾਰਤ ਭਾਸ਼ਾਵਾਂ ਅਤੇ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਉਪਲਬਧ ਹੈ। ਕਾਨੂੰਨੀ ਸ਼ਬਦਾਵਲੀ ਨੂੰ ਉਸਦੇ ਅਧਿਕਾਰਤ ਰੂਪ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਰੱਖਿਆ ਗਿਆ ਹੈ।",
  "home.features.versioning_updates": "ਸੰਸਕਰਣ ਅੱਪਡੇਟ",
  "home.features.abstention_protects": "ਸੁਰੱਖਿਅਤ ਪਰਹੇਜ਼ ਸੁਰੱਖਿਆ",
  "home.workflows.heading": "ਤੁਸੀਂ ਕੀ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
  "home.intake.ayurvedicFormulation": "ਆਯੁਰਵੈਦਿਕ ਯੋਗ (ਫਾਰਮੂਲੇਸ਼ਨ)",
  "home.intake.ayurvedicFormulationHint": "ਕਲਾਸੀਕਲ ਜਾਂ ਮਲਕੀਅਤੀ ਬਹੁ-ਜੜ੍ਹੀ-ਬੂਟੀ ਮਿਸ਼ਰਣ",
  "home.intake.herbalProduct": "ਹਰਬਲ ਉਤਪਾਦ",
  "home.intake.herbalProductHint": "ਅਰਕ, ਖੁਰਾਕ ਪੂਰਕ, ਫਾਈਟੋਮੈਡੀਸਿਨ",
  "home.intake.plantResource": "ਪੌਦਾ / ਜੈਵਿਕ ਸਰੋਤ",
  "home.intake.plantResourceHint": "ਚਿਕਿਤਸਕ ਬਨਸਪਤੀ, ABS/NBA ਪੂਰਵ-ਪ੍ਰਵਾਨਗੀ",
  "home.intake.traditionalKnowledge": "ਰਵਾਇਤੀ ਗਿਆਨ",
  "home.intake.traditionalKnowledgeHint": "ਕਲਾਸੀਕਲ ਗ੍ਰੰਥ, TKDL ਪੂਰਵ-ਕਲਾ ਸਮੀਖਿਆ",
  "home.intake.novelProcess": "ਨਵੀਨ ਪ੍ਰਕਿਰਿਆ",
  "home.intake.novelProcessHint": "ਨਿਕਾਸੀ, ਸਥਿਰੀਕਰਨ ਅਤੇ Section 3(p) ਤਸਦੀਕ",
  "home.intake.brandIdentity": "ਬ੍ਰਾਂਡ ਪਛਾਣ",
  "home.intake.brandIdentityHint": "ਟ੍ਰੇਡਮਾਰਕ, ਸ਼੍ਰੇਣੀ 5/3/30/44",
  "home.intake.geographicalIdentity": "ਭੂਗੋਲਿਕ ਪਛਾਣ",
  "home.intake.geographicalIdentityHint": "GI ਸੂਚਕ, ਮੂਲ ਪ੍ਰਮਾਣ ਪੱਤਰ",
  "home.intake.regulatoryQuestion": "ਨਿਯਮਿਤ ਸਵਾਲ",
  "home.intake.regulatoryQuestionHint": "FSSAI, AYUSH, Rule 158B, Schedule T",
  "home.demo.badge": "ਲਾਈਵ ਕਾਨੂੰਨੀ ਪ੍ਰਦਰਸ਼ਨ",
  "home.demo.simulation": "ਰੈਗੂਲੇਟਰੀ ਸਿਮੂਲੇਸ਼ਨ",
  "home.demo.title": "ਕੱਚੀ ਧਾਰਨਾ ਤੋਂ ਕਾਨੂੰਨੀ ਸੁਰੱਖਿਆ ਤੱਕ",
  "home.demo.story": "ਦੇਖੋ ਅਸ਼ਵਗੰਧਾ-ਬ੍ਰਾਹਮੀ ਸਿਰਪ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਿਵੇਂ ਹੁੰਦਾ ਹੈ: Section 3(p) ਪੂਰਵ-ਕਲਾ, Rule 158B ਪਾਲਣਾ, FSSAI ਆਯੁਸ਼ ਆਹਾਰ ਵਰਗੀਕਰਨ ਅਤੇ ABS ਪੂਰਵ-ਪ੍ਰਵਾਨਗੀ ਲੋੜਾਂ।",
  "home.demo.notice": "ਸਾਰੀਆਂ ਸਿਫ਼ਾਰਸ਼ਾਂ ਸਿੱਧੇ ਸਰਕਾਰੀ ਗਜ਼ਟ ਦੇ ਕਾਨੂੰਨੀ ਉਪਬੰਧਾਂ ਨਾਲ ਜੁੜੀਆਂ ਹਨ।",
  "home.demo.startCase": "ਇਹ ਕੇਸ ਸ਼ੁਰੂ ਕਰੋ",
  "home.demo.inspectDossier": "ਨਮੂਨਾ ਡੋਜ਼ੀਅਰ ਦੇਖੋ",
  "home.demo.step1.label": "ਸਮੱਗਰੀ ਵਿਸ਼ਲੇਸ਼ਣ",
  "home.demo.step1.sub": "ਅਸ਼ਵਗੰਧਾ + ਬ੍ਰਾਹਮੀ ਸਿਰਪ",
  "home.demo.step2.label": "TKDL ਖੋਜ",
  "home.demo.step2.sub": "ਭਾਵਪ੍ਰਕਾਸ਼ ਅਤੇ ਚਰਕ ਸੰਹਿਤਾ ਹਵਾਲੇ",
  "home.demo.step3.label": "Section 3(p) ਜੋਖਮ",
  "home.demo.step3.sub": "ਰਵਾਇਤੀ ਗਿਆਨ ਪੇਟੈਂਟ ਛੋਟ",
  "home.demo.step4.label": "Rule 158B ਤਸਦੀਕ",
  "home.demo.step4.sub": "ਕਲਾਸੀਕਲ ਗ੍ਰੰਥ ਸਬੂਤ ਰਸਤਾ",
  "home.demo.step5.label": "FSSAI ਬਨਾਮ AYUSH",
  "home.demo.step5.sub": "ਆਯੁਸ਼ ਆਹਾਰ ਵਰਗੀਕਰਨ ਵਿਕਲਪ",
  "home.demo.step6.label": "NBA / ABS ਪ੍ਰਵਾਨਗੀ",
  "home.demo.step6.sub": "Form III ਜੈਵਿਕ ਸਰੋਤ ਅਰਜ਼ੀ",
  "home.demo.step7.label": "ਕਾਰਵਾਈ ਯੋਜਨਾ",
  "home.demo.step7.sub": "ਸੁਰੱਖਿਆ ਰਣਨੀਤੀ ਅਤੇ ਫਾਈਲਿੰਗ",
  "home.evidence.sample": "ਨਮੂਨਾ ਕਾਨੂੰਨੀ ਸਬੂਤ",
  "home.evidence.actIndia": "ਪੇਟੈਂਟ ਐਕਟ 1970 (ਭਾਰਤ)",
  "home.evidence.strength": "ਕਾਨੂੰਨੀ ਸਬੂਤ ਦੀ ਮਜ਼ਬੂਤੀ",
  "home.evidence.high": "ਉੱਚ",
  "home.evidence.whyRelevant": "ਇਹ ਕਿਉਂ ਲਾਗੂ ਹੁੰਦਾ ਹੈ: ਜੇ ਕੋਈ ਦਾਅਵਾ ਰਵਾਇਤੀ ਗਿਆਨ ਦਾ ਸਿਰਫ਼ ਇਕੱਠ ਹੈ, ਤਾਂ Section 3(p) ਅਧੀਨ ਪੇਟੈਂਟ ਰੱਦ ਕਰ ਦਿੱਤਾ ਜਾਂਦਾ ਹੈ।",
  "home.evidence.viewSource": "ਅਧਿਕਾਰਤ ਸਰੋਤ ਦੇਖੋ",
  "home.evidence.disclaimer": "ਇਹ ਅੰਸ਼ ਡਿਜੀਟਲ ਤੌਰ 'ਤੇ ਹਸਤਾਖਰਿਤ ਭਾਰਤ ਦੇ ਗਜ਼ਟ ਤੋਂ ਪ੍ਰਮਾਣਿਤ ਹੈ।",
  "home.multilingual.badge": "22 ਭਾਸ਼ਾਵਾਂ + ਅੰਗਰੇਜ਼ੀ",
  "home.multilingual.fullSupport": "ਭਾਰਤ ਦੀਆਂ ਸਾਰੀਆਂ 22 ਅਧਿਕਾਰਤ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਪੂਰਾ ਸਮਰਥਨ",
  "home.multilingual.more": "ਹੋਰ ਭਾਸ਼ਾਵਾਂ",
  "home.multilingual.all22": "ਭਾਰਤੀ ਸੰਵਿਧਾਨ ਦੀ ਅੱਠਵੀਂ ਅਨੁਸੂਚੀ ਦੀਆਂ ਸਾਰੀਆਂ 22 ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਉਪਲਬਧ",
  "home.domain.patent": "ਪੇਟੈਂਟ (ਧਾਰਾ 3(p) ਅਤੇ 3(e))",
  "home.domain.patentDesc": "ਰਵਾਇਤੀ ਗਿਆਨ ਛੋਟ, ਨਵੀਨਤਾ ਅਤੇ ਪੂਰਵ-ਕਲਾ ਵਿਸ਼ਲੇਸ਼ਣ।",
  "home.domain.trademark": "ਟ੍ਰੇਡਮਾਰਕ",
  "home.domain.trademarkDesc": "ਆਯੁਰਵੈਦਿਕ ਬ੍ਰਾਂਡ, ਲੋਗੋ, ਸ਼੍ਰੇਣੀ 5 ਅਤੇ ਦਵਾਈ ਵਰਗੀਕਰਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ।",
  "home.domain.gi": "ਭੂਗੋਲਿਕ ਸੰਕੇਤ (GI)",
  "home.domain.giDesc": "ਸਥਾਨਕ ਬਨਸਪਤੀ ਅਤੇ ਰਵਾਇਤੀ ਦਵਾਈ ਪ੍ਰਣਾਲੀਆਂ ਦੀ ਸੁਰੱਖਿਆ।",
  "home.domain.plantVariety": "ਪੌਦਿਆਂ ਦੀ ਕਿਸਮ ਸੁਰੱਖਿਆ (PPV&FR)",
  "home.domain.plantVarietyDesc": "ਕਿਸਾਨ ਅਧਿਕਾਰ ਅਤੇ ਚਿਕਿਤਸਕ ਪੌਦਿਆਂ ਦੀਆਂ ਕਿਸਮਾਂ ਦੀ ਰਜਿਸਟ੍ਰੇਸ਼ਨ।",
  "home.domain.copyright": "ਕਾਪੀਰਾਈਟ",
  "home.domain.copyrightDesc": "ਖੋਜ ਦਸਤਾਵੇਜ਼, ਕਲਾਸੀਕਲ ਟੀਕੇ ਅਤੇ ਡਿਜੀਟਲ ਡਾਟਾਬੇਸ ਸੁਰੱਖਿਆ।",
  "home.domain.industrialDesign": "ਉਦਯੋਗਿਕ ਡਿਜ਼ਾਈਨ",
  "home.domain.industrialDesignDesc": "ਦਵਾਈ ਵੰਡ ਯੰਤਰ, ਬੋਤਲਾਂ ਅਤੇ ਪੈਕੇਜਿੰਗ ਡਿਜ਼ਾਈਨ।",
  "home.domain.tk": "ਰਵਾਇਤੀ ਗਿਆਨ (TKDL)",
  "home.domain.tkDesc": "ਆਯੁਰਵੇਦ, ਸਿੱਧ ਅਤੇ ਯੂਨਾਨੀ ਗਿਆਨ ਦੀ ਅੰਤਰਰਾਸ਼ਟਰੀ ਸੁਰੱਖਿਆ।",
  "home.domain.abs": "ਜੈਵਿਕ ਵਿਭਿੰਨਤਾ ਅਤੇ ABS",
  "home.domain.absDesc": "ਰਾਸ਼ਟਰੀ ਜੈਵ ਵਿਭਿੰਨਤਾ ਅਥਾਰਟੀ (NBA) Form III ਪ੍ਰਵਾਨਗੀ।",
  "home.domain.ayush": "ਆਯੁਸ਼ (AYUSH) ਨਿਯਮ",
  "home.domain.ayushDesc": "ਡਰੱਗਜ਼ ਐਂਡ ਕਾਸਮੈਟਿਕਸ ਐਕਟ, ਕਲਾਸੀਕਲ ਹਵਾਲੇ।",
  "home.domain.fssaiDesc": "ਆਯੁਸ਼ ਆਹਾਰ ਨਿਯਮ, ਪੋਸ਼ਣ ਪੂਰਕ ਅਤੇ ਸੁਰੱਖਿਆ ਮਿਆਰ।",
  "home.domain.drugsCosmetics": "ਡਰੱਗਜ਼ ਐਂਡ ਕਾਸਮੈਟਿਕਸ ਐਕਟ",
  "home.domain.drugsCosmeticsDesc": "Rule 158B ਸਬੂਤ ਅਤੇ Schedule T GMP ਮਿਆਰ।",
  "home.domain.internationalIp": "ਅੰਤਰਰਾਸ਼ਟਰੀ ਬੌਧਿਕ ਸੰਪੱਤੀ",
  "home.domain.internationalIpDesc": "PCT, ਪੈਰਿਸ ਕਨਵੈਨਸ਼ਨ ਅਤੇ ਨਾਗੋਆ ਪ੍ਰੋਟੋਕੋਲ।",
  "home.pipeline.question": "ਸਵਾਲ",
  "home.pipeline.classify": "ਵਰਗੀਕਰਨ",
  "home.pipeline.evidence": "ਸਬੂਤ",
  "home.pipeline.intelligence": "ਇੰਟੈਲੀਜੈਂਸ",
  "home.pipeline.action": "ਕਾਰਵਾਈ",
  "home.domain.plantVarietyProtection": "ਪੌਦਿਆਂ ਦੀ ਕਿਸਮ ਸੁਰੱਖਿਆ",
  "nav.quick.herbalPatent": "ਹਰਬਲ ਪੇਟੈਂਟ ਯੋਗਤਾ",
  "nav.quick.fssaiRules": "FSSAI ਆਯੁਸ਼ ਆਹਾਰ ਨਿਯਮ",
  "nav.quick.giProtection": "ਚਿਕਿਤਸਕ ਪੌਦਿਆਂ ਦੀ GI ਸੁਰੱਖਿਆ",
  "nav.quick.absNagoya": "ABS ਨਾਗੋਆ ਪ੍ਰੋਟੋਕੋਲ ਪਾਲਣਾ",
  "nav.quick.section3p": "Section 3(p) ਰਵਾਇਤੀ ਗਿਆਨ ਛੋਟ",
  "nav.quick.tkNeem": "ਨਿੰਮ ਅਤੇ ਹਲਦੀ ਪੇਟੈਂਟ ਵਿਰੋਧ",
  "wizard.stepProgress": "ਪੜਾਅ ਦੀ ਤਰੱਕੀ",
  "wizard.stepPrev": "ਪਿਛਲਾ ਪੜਾਅ",
  "wizard.stepNext": "ਅਗਲਾ ਪੜਾਅ",
  "wizard.stepSaveRoadmap": "ਕੇਸ ਸੰਭਾਲੋ ਅਤੇ ਰੋਡਮੈਪ ਬਣਾਓ",
  "wizard.backToCases": "ਮੇਰੇ ਕੇਸਾਂ 'ਤੇ ਵਾਪਸ ਜਾਓ",
  "wizard.guidedSetup": "ਗਾਈਡਡ ਬੌਧਿਕ ਸੰਪੱਤੀ ਅਤੇ ਰੈਗੂਲੇਟਰੀ ਸੈੱਟਅੱਪ",
  "wizard.gap.title": "ਸਬੂਤ ਦਾ ਪਾੜਾ ਮਿਲਿਆ",
  "wizard.gap.desc": "ਇਸ ਯੋਗ ਕਿਸਮ ਲਈ ਖਾਸ ਕਲਾਸੀਕਲ ਹਵਾਲਿਆਂ ਦੀ ਲੋੜ ਹੋ ਸਕਦੀ ਹੈ।",
  "wizard.gap.fix": "ਸਬੂਤ ਦਾ ਪਾੜਾ ਕਿਵੇਂ ਭਰਨਾ ਹੈ ਦੇਖੋ",
  "wizard.validation.titleRequired": "ਫਾਰਮੂਲੇਸ਼ਨ ਸਿਰਲੇਖ ਲੋੜੀਂਦਾ ਹੈ",
  "wizard.dnaReady": "ਫਾਰਮੂਲੇਸ਼ਨ DNA ਤਿਆਰ ਹੈ",
  "wizard.ingIndex": "ਸਮੱਗਰੀ",
  "wizard.assetNature": "ਸੰਪੱਤੀ ਦਾ ਸਰੂਪ",
  "wizard.selectTreatises": "ਪ੍ਰਮਾਣਿਤ ਕਲਾਸੀਕਲ ਗ੍ਰੰਥ ਚੁਣੋ",
  "wizard.classicalCitation": "ਕਲਾਸੀਕਲ ਹਵਾਲਾ / ਸ਼ਲੋਕ ਉਧਰਣ",
  "wizard.indicationsLabel": "ਉਪਚਾਰਕ ਸੰਕੇਤ / ਰੋਗ ਅਧਿਕਾਰ",
  "wizard.indicationsPlaceholder": "ਜਿਵੇਂ: ਕਾਸ, ਸ਼ਵਾਸ, ਜਵਰ, ਰਸਾਇਣ...",
  "wizard.prepNarrative": "ਤਿਆਰੀ ਵਿਧੀ ਦਾ ਵੇਰਵਾ",
  "wizard.prepNarrativePlaceholder": "ਸੋਧਨ, ਭਾਵਨਾ ਜਾਂ ਨਿਕਾਸੀ ਪ੍ਰਕਿਰਿਆ ਦਾ ਵਿਸਥਾਰ ਨਾਲ ਵਰਣਨ ਕਰੋ...",
  "wizard.commercialPathway": "ਵਪਾਰਕ ਰਸਤਾ",
  "wizard.targetJurisdictionTitle": "ਨਿਸ਼ਾਨਾ ਅਧਿਕਾਰ ਖੇਤਰ",
  "wizard.supportingDocsTitle": "ਸਹਾਇਕ ਦਸਤਾਵੇਜ਼ ਅਤੇ ਸਬੂਤ",
  "wizard.docAddPlaceholder": "ਦਸਤਾਵੇਜ਼ ਦਾ ਨਾਮ ਜਾਂ ਹਵਾਲਾ ਦਰਜ ਕਰੋ...",
  "wizard.addDocBtn": "ਦਸਤਾਵੇਜ਼ ਸ਼ਾਮਲ ਕਰੋ",
  "wizard.plantPart": "ਵਰਤਿਆ ਗਿਆ ਪੌਦੇ ਦਾ ਹਿੱਸਾ",
  "wizard.sourcingType": "ਸਰੋਤ ਕਿਸਮ",
  "wizard.cat.ayurvedic": "ਆਯੁਰਵੈਦਿਕ ਯੋਗ",
  "wizard.cat.ayurvedicDesc": "ਰਵਾਇਤੀ ਜਾਂ ਮਲਕੀਅਤੀ ਦਵਾਈ",
  "wizard.cat.herbal": "ਹਰਬਲ ਉਤਪਾਦ",
  "wizard.cat.herbalDesc": "ਪੌਦਿਆਂ ਦਾ ਅਰਕ ਜਾਂ ਪੂਰਕ",
  "wizard.cat.traditional": "ਰਵਾਇਤੀ ਗਿਆਨ",
  "wizard.cat.traditionalDesc": "ਵਿਰਾਸਤੀ ਅਭਿਆਸ ਜਾਂ ਗ੍ਰੰਥ",
  "wizard.cat.plant": "ਜੈਵਿਕ ਸਰੋਤ",
  "wizard.cat.plantDesc": "ਪੌਦਾ ਜਾਂ ਜੈਵਿਕ ਸਮੱਗਰੀ",
  "wizard.cat.process": "ਨਵੀਨ ਪ੍ਰਕਿਰਿਆ",
  "wizard.cat.processDesc": "ਨਿਕਾਸੀ ਜਾਂ ਉਤਪਾਦਨ ਵਿਧੀ",
  "wizard.cat.brand": "ਬ੍ਰਾਂਡ ਜਾਂ ਉਤਪਾਦ ਦਾ ਨਾਮ",
  "wizard.cat.brandDesc": "ਟ੍ਰੇਡਮਾਰਕ ਸੁਰੱਖਿਆ",
  "wizard.prep.classical": "ਕਲਾਸੀਕਲ ਵਿਧੀ",
  "wizard.prep.classicalDesc": "ਅਧਿਕਾਰਤ ਸੰਹਿਤਾ ਅਨੁਸਾਰ ਤਿਆਰ",
  "wizard.prep.extract": "ਮਿਆਰੀ ਅਰਕ",
  "wizard.prep.extractDesc": "ਕਿਰਿਆਸ਼ੀਲ ਤੱਤਾਂ ਦਾ ਜਲਮਈ/ਅਲਕੋਹਲ ਵਾਲਾ ਅਰਕ",
  "wizard.prep.novel": "ਨਵੀਨ ਤਕਨਾਲੋਜੀ",
  "wizard.prep.novelDesc": "ਨੈਨੋਪਾਰਟੀਕਲ ਜਾਂ ਉੱਨਤ ਡਿਲੀਵਰੀ ਪ੍ਰਣਾਲੀ",
  "wizard.commercial.domestic": "ਘਰੇਲੂ ਭਾਰਤੀ ਬਾਜ਼ਾਰ",
  "wizard.commercial.domesticDesc": "ਭਾਰਤ ਵਿੱਚ ਉਤਪਾਦਨ ਅਤੇ ਵਿਕਰੀ",
  "wizard.commercial.export": "ਅੰਤਰਰਾਸ਼ਟਰੀ ਨਿਰਯਾਤ",
  "wizard.commercial.exportDesc": "ਵਿਸ਼ਵ ਬਾਜ਼ਾਰ ਵਿੱਚ ਵਿਕਰੀ",
  "wizard.commercial.rd": "ਖੋਜ ਅਤੇ ਵਿਕਾਸ",
  "wizard.commercial.rdDesc": "ਪ੍ਰੀ-ਕਲੀਨਿਕਲ ਜਾਂ ਕਲੀਨਿਕਲ ਟਰਾਇਲ",
  "wizard.commercial.licensing": "ਤਕਨਾਲੋਜੀ ਲਾਇਸੈਂਸਿੰਗ",
  "wizard.commercial.licensingDesc": "ਤੀਜੀ ਧਿਰ ਨੂੰ ਲਾਇਸੈਂਸ ਦੇਣਾ",
  "wizard.jur.india": "ਭਾਰਤ",
  "wizard.jur.indiaDesc": "ਭਾਰਤੀ ਪੇਟੈਂਟ ਅਤੇ ਰੈਗੂਲੇਟਰੀ ਕਾਨੂੰਨ",
  "wizard.jur.us": "ਸੰਯੁਕਤ ਰਾਜ ਅਮਰੀਕਾ",
  "wizard.jur.usDesc": "US FDA ਅਤੇ USPTO ਨਿਯਮ",
  "wizard.jur.eu": "ਯੂਰਪੀਅਨ ਯੂਨੀਅਨ",
  "wizard.jur.euDesc": "EMA ਅਤੇ EPO ਨਿਯਮ",
  "wizard.jur.intl": "ਅੰਤਰਰਾਸ਼ਟਰੀ (PCT)",
  "wizard.jur.intlDesc": "ਗਲੋਬਲ ਪੇਟੈਂਟ ਸਹਿਯੋਗ ਸੰਧੀ",
  "wizard.claim.therapeutic": "ਉਪਚਾਰਕ ਦਾਅਵਾ",
  "wizard.claim.nutritional": "ਪੋਸ਼ਣ ਜਾਂ ਖੁਰਾਕੀ ਦਾਅਵਾ",
  "wizard.claim.cosmetic": "ਕਾਸਮੈਟਿਕ ਦਾਅਵਾ",
  "wizard.claim.wellness": "ਆਮ ਸਿਹਤ ਅਤੇ ਤੰਦਰੁਸਤੀ",
  "explore.breadcrumb": "ਰੈਗੂਲੇਟਰੀ ਢਾਂਚਾ ਖੋਜੋ",
  "explore.searchPlaceholder": "ਫਾਰਮੂਲੇਸ਼ਨ, ਪੇਟੈਂਟ, Section 3(p), Rule 158B, ABS, TKDL ਖੋਜੋ...",
  "explore.allFrameworks": "ਸਾਰੇ ਰੈਗੂਲੇਟਰੀ ਢਾਂਚੇ",
  "explore.ipPatents": "IP ਅਤੇ ਪੇਟੈਂਟ",
  "explore.ayushFssai": "ਆਯੁਸ਼ ਅਤੇ FSSAI",
  "explore.bioAbs": "ਜੈਵ ਵਿਭਿੰਨਤਾ ਅਤੇ ABS",
  "explore.tkTkdl": "ਰਵਾਇਤੀ ਗਿਆਨ ਅਤੇ TKDL",
  "explore.statutoryHighlights": "ਕਾਨੂੰਨੀ ਮੁੱਖ ਨੁਕਤੇ",
  "explore.noItems": "ਚੁਣੀ ਗਈ ਸ਼੍ਰੇਣੀ ਵਿੱਚ ਕੋਈ ਰੈਗੂਲੇਟਰੀ ਢਾਂਚਾ ਨਹੀਂ ਮਿਲਿਆ।",
  "explore.actSec3p": "ਪੇਟੈਂਟ ਐਕਟ 1970 — ਧਾਰਾ 3(p) ਅਤੇ 3(e)",
  "explore.actRule158b": "ਡਰੱਗਜ਼ ਐਂਡ ਕਾਸਮੈਟਿਕਸ ਰੂਲਜ਼ 1945 — ਨਿਯਮ 158B",
  "explore.actAbs": "ਜੈਵਿਕ ਵਿਭਿੰਨਤਾ ਐਕਟ 2002 — Form III ABS",
  "explore.actAahar": "ਆਯੁਸ਼ ਆਹਾਰ ਨਿਯਮ 2022 — FSSAI ਢਾਂਚਾ",
  "explore.actTkdl": "ਰਵਾਇਤੀ ਗਿਆਨ ਡਿਜੀਟਲ ਲਾਇਬ੍ਰੇਰੀ (TKDL) ਢਾਂਚਾ",
  "explore.actGi": "ਭੂਗੋਲਿਕ ਸੰਕੇਤ (ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਅਤੇ ਸੁਰੱਖਿਆ) ਐਕਟ 1999",
  "evidence.breadcrumb": "ਕਾਨੂੰਨੀ ਸਬੂਤ ਸੰਗ੍ਰਹਿ",
  "evidence.allAuthorities": "ਸਾਰੀਆਂ ਰੈਗੂਲੇਟਰੀ ਅਥਾਰਟੀਆਂ",
  "evidence.allTypes": "ਸਾਰੀਆਂ ਕਾਨੂੰਨੀ ਕਿਸਮਾਂ",
  "evidence.act": "ਐਕਟ (ਕਾਨੂੰਨ)",
  "evidence.rule": "ਨਿਯਮ (Rule)",
  "evidence.gazetteNotification": "ਗਜ਼ਟ ਨੋਟੀਫਿਕੇਸ਼ਨ",
  "evidence.pharmacopoeialStandard": "ਫਾਰਮਾਕੋਪੀਅਲ ਮਿਆਰ",
  "evidence.treaty": "ਅੰਤਰਰਾਸ਼ਟਰੀ ਸੰਧੀ",
  "evidence.verifiedAuthority": "ਪ੍ਰਮਾਣਿਤ ਰੈਗੂਲੇਟਰੀ ਅਥਾਰਟੀ",
  "evidence.cryptoHash": "ਕ੍ਰਿਪਟੋਗ੍ਰਾਫਿਕ ਫੋਰੈਂਸਿਕ ਹੈਸ਼",
  "evidence.plainSummary": "ਸਰਲ ਸੰਖੇਪ",
  "evidence.officialExcerpt": "ਅਧਿਕਾਰਤ ਕਾਨੂੰਨੀ ਅੰਸ਼",
  "evidence.inspectCitation": "ਕਾਨੂੰਨੀ ਹਵਾਲਾ ਜਾਂਚੋ",
  "evidence.noCorpusFound": "ਕੋਈ ਕਾਨੂੰਨੀ ਸਬੂਤ ਨਹੀਂ ਮਿਲਿਆ",
  "evidence.noCorpusHint": "ਆਪਣੇ ਖੋਜ ਮਾਪਦੰਡ ਬਦਲੋ ਜਾਂ ਫਿਲਟਰ ਹਟਾਓ।",
  "caseDetail.loading": "ਕਾਨੂੰਨੀ ਜਾਣਕਾਰੀ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...",
  "caseDetail.notFound": "ਕੇਸ ਨਹੀਂ ਮਿਲਿਆ",
  "caseDetail.notFoundDesc": "ਬੇਨਤੀ ਕੀਤਾ ਕੇਸ ਰਿਕਾਰਡ ਮੌਜੂਦ ਨਹੀਂ ਹੈ ਜਾਂ ਹਟਾ ਦਿੱਤਾ ਗਿਆ ਹੈ।",
  "caseDetail.returnWorkspace": "ਕੇਸ ਵਰਕਸਪੇਸ 'ਤੇ ਵਾਪਸ ਜਾਓ",
  "caseDetail.juryDemo": "ਜਿਊਰੀ ਡੈਮੋ ਮੋਡ",
  "caseDetail.simulateMissing": "ਗੁੰਮ ਹੋਏ ਦਸਤਾਵੇਜ਼ਾਂ ਦਾ ਪ੍ਰਦਰਸ਼ਨ ਕਰੋ",
  "caseDetail.exportDossier": "ਕੇਸ ਡੋਜ਼ੀਅਰ ਨਿਰਯਾਤ ਕਰੋ",
  "caseDetail.timeMachine": "ਰੈਗੂਲੇਟਰੀ ਟਾਈਮ ਮਸ਼ੀਨ",
  "caseDetail.editFormulation": "ਫਾਰਮੂਲੇਸ਼ਨ ਸੰਪਾਦਿਤ ਕਰੋ",
  "caseDetail.tabSummary": "ਸੰਖੇਪ ਅਤੇ ਫੈਸਲਾ",
  "caseDetail.tabDna": "ਫਾਰਮੂਲੇਸ਼ਨ DNA",
  "caseDetail.tabClassifications": "ਉਮੀਦਵਾਰ ਵਰਗੀਕਰਨ",
  "caseDetail.tabRegulations": "ਲਾਗੂ ਨਿਯਮ",
  "caseDetail.tabIpPathways": "ਬੌਧਿਕ ਸੰਪੱਤੀ ਰਸਤੇ",
  "caseDetail.tabAbs": "ABS ਪਾਲਣਾ",
  "caseDetail.tabPriorArt": "ਪੂਰਵ-ਕਲਾ ਵਿਸ਼ਲੇਸ਼ਣ",
  "caseDetail.tabEvidenceGaps": "ਸਬੂਤਾਂ ਦਾ ਪਾੜਾ",
  "caseDetail.tabEvidenceChain": "ਕਾਨੂੰਨੀ ਸਬੂਤ ਲੜੀ",
  "caseDetail.tabNextActions": "ਅਗਲੀਆਂ ਸਿਫਾਰਸ਼ ਕੀਤੀਆਂ ਕਾਰਵਾਈਆਂ",
  "caseDetail.classificationVerdict": "ਵਰਗੀਕਰਨ ਫੈਸਲਾ",
  "caseDetail.evidenceStrength": "ਸਬੂਤ ਦੀ ਮਜ਼ਬੂਤੀ",
  "caseDetail.governingAuthority": "ਰੈਗੂਲੇਟਰੀ ਅਥਾਰਟੀ",
  "caseDetail.statutoryBasis": "ਕਾਨੂੰਨੀ ਆਧਾਰ",
  "caseDetail.coreExcerpt": "ਮੁੱਖ ਕਾਨੂੰਨੀ ਅੰਸ਼",
  "caseDetail.plainExplanation": "ਸਰਲ ਵਿਆਖਿਆ",
  "caseDetail.whyThis": "ਇਹ ਵਰਗੀਕਰਨ ਕਿਉਂ ਲਾਗੂ ਹੁੰਦਾ ਹੈ?",
  "auth.showPassword": "ਪਾਸਵਰਡ ਦਿਖਾਓ",
  "auth.hidePassword": "ਪਾਸਵਰਡ ਛੁਪਾਓ",
  "auth.charRequirement": "8+ ਅੱਖਰ",
  "auth.upperRequirement": "ਘੱਟੋ-ਘੱਟ ਇੱਕ ਵੱਡਾ ਅੱਖਰ (Uppercase)",
  "auth.numRequirement": "ਘੱਟੋ-ਘੱਟ ਇੱਕ ਅੰਕ (Number)",
  "auth.demoAdmin": "ਡੈਮੋ ਐਡਮਿਨ ਪ੍ਰਮਾਣ ਪੱਤਰ ਵਰਤੋ",
  "intel.drawerTitle": "ਕਾਨੂੰਨੀ ਸਬੂਤ ਦਰਾਜ਼",
  "intel.authority": "ਰੈਗੂਲੇਟਰੀ ਅਥਾਰਟੀ",
  "intel.hierarchy": "ਕਾਨੂੰਨੀ ਤਰਜੀਹ ਲੜੀ",
  "intel.version": "ਅਧਿਕਾਰਤ ਸੰਸਕਰਣ",
  "intel.excerpt": "ਕਾਨੂੰਨੀ ਅੰਸ਼",
  "intel.plainSummary": "ਸਰਲ ਕਾਨੂੰਨੀ ਸੰਖੇਪ",
  "intel.gazetteSource": "ਗਜ਼ਟ ਸਰੋਤ",
  "intel.openExternal": "ਅਧਿਕਾਰਤ ਗਜ਼ਟ ਖੋਲ੍ਹੋ",
  "intel.closeDrawer": "ਦਰਾਜ਼ ਬੰਦ ਕਰੋ",
  "intel.gapsTitle": "ਸਬੂਤਾਂ ਦਾ ਪਾੜਾ ਅਤੇ ਹੱਲ ਰਣਨੀਤੀ",
  "intel.resolutionStrategy": "ਹੱਲ ਰਣਨੀਤੀ",
  "intel.chainTitle": "ਕਾਨੂੰਨੀ ਸਬੂਤ ਲੜੀ",
  "intel.factTriggered": "ਕਿਰਿਆਸ਼ੀਲ ਤੱਥ",
  "intel.ruleApplied": "ਲਾਗੂ ਕੀਤਾ ਨਿਯਮ",
  "intel.matrixTitle": "ਕਾਨੂੰਨੀ ਇੰਟੈਲੀਜੈਂਸ ਬੋਰਡ",
  "intel.timeMachineTitle": "ਰੈਗੂਲੇਟਰੀ ਟਾਈਮ ਮਸ਼ੀਨ",
  "intel.historicalAmendments": "ਇਤਿਹਾਸਕ ਸੋਧਾਂ",
  "intel.uploadTitle": "ਸਹਾਇਕ ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ",
  "intel.dragDrop": "ਦਸਤਾਵੇਜ਼ ਇੱਥੇ ਖਿੱਚੋ ਅਤੇ ਸੁੱਟੋ ਜਾਂ ਬ੍ਰਾਊਜ਼ ਕਰੋ",
  "intel.whyTitle": "ਤੁਸੀਂ ਇਹ ਕਿਉਂ ਦੇਖ ਰਹੇ ਹੋ?",
  "intel.deterministicVerification": "ਨਿਰਧਾਰਿਤ ਕਾਨੂੰਨੀ ਤਸਦੀਕ",
  "search.breadcrumb": "ਖੋਜ",
  "search.heading": "ਕਾਨੂੰਨੀ ਅਤੇ ਪੇਟੈਂਟ ਖੋਜ",
  "search.btnSearch": "ਖੋਜ ਕਰੋ",
  "search.suggestedLabel": "ਸੁਝਾਏ ਗਏ ਸਵਾਲ",
  "search.recentLabel": "ਤਾਜ਼ਾ ਖੋਜਾਂ",
  "search.clearLabel": "ਸਾਫ਼ ਕਰੋ",
  "search.advancedFilters": "ਉੱਨਤ ਫਿਲਟਰ",
  "search.hideAdvancedFilters": "ਉੱਨਤ ਫਿਲਟਰ ਲੁਕਾਓ",
  "search.allAuthorities": "ਸਾਰੀਆਂ ਅਥਾਰਟੀਆਂ",
  "search.allJurisdictions": "ਸਾਰੇ ਅਧਿਕਾਰ ਖੇਤਰ",
  "assistant.breadcrumb": "AI ਸਹਾਇਕ",
  "assistant.bannerActive": "ਸਰਗਰਮ ਕੇਸ ਦੇ ਸੰਦਰਭ ਵਿੱਚ ਕੰਮ ਕਰ ਰਿਹਾ ਹੈ",
  "assistant.suggestedInquiries": "ਸੁਝਾਏ ਗਏ ਸਵਾਲ",
  "assistant.directAnswer": "ਸਿੱਧਾ ਕਾਨੂੰਨੀ ਜਵਾਬ",
  "assistant.ruleConstraints": "ਲਾਗੂ ਨਿਯਮ ਅਤੇ ਪਾਬੰਦੀਆਂ",
  "assistant.officialCitations": "ਅਧਿਕਾਰਤ ਕਾਨੂੰਨੀ ਹਵਾਲੇ",
  "assistant.evidenceGaps": "ਮਿਲੇ ਸਬੂਤਾਂ ਦੇ ਪਾੜੇ",
  "assistant.disclaimerFooter": "ਕਾਨੂੰਨੀ ਬੇਦਾਅਵਾ: ਇਹ ਪ੍ਰਣਾਲੀ ਸਿਰਫ ਜਾਣਕਾਰੀ ਦੇ ਉਦੇਸ਼ਾਂ ਲਈ ਕਾਨੂੰਨੀ ਮਾਰਗਦਰਸ਼ਨ ਪ੍ਰਦਾਨ ਕਰਦੀ ਹੈ।",
  "report.returnDossier": "ਕੇਸ ਡੋਜ਼ੀਅਰ 'ਤੇ ਵਾਪਸ ਜਾਓ",
  "report.tableIngredients": "ਫਾਰਮੂਲੇਸ਼ਨ ਸਮੱਗਰੀ ਅਤੇ ਵੇਰਵੇ",
  "report.name": "ਸਮੱਗਰੀ ਦਾ ਨਾਮ",
  "report.botanical": "ਬੋਟੈਨੀਕਲ ਨਾਮ",
  "report.sanskrit": "ਸੰਸਕ੍ਰਿਤ ਨਾਮ",
  "report.part": "ਵਰਤਿਆ ਗਿਆ ਹਿੱਸਾ",
  "report.percentage": "ਅਨੁਪਾਤ / ਪ੍ਰਤੀਸ਼ਤ",
  "report.source": "ਹਵਾਲਾ ਸਰੋਤ",
  "report.origin": "ਭੂਗੋਲਿਕ ਮੂਲ",
  "cases.noMatch": "ਤੁਹਾਡੀ ਖੋਜ ਨਾਲ ਮੇਲ ਖਾਂਦਾ ਕੋਈ ਕੇਸ ਨਹੀਂ ਮਿਲਿਆ।",
  "cases.jurisdictionIndia": "ਭਾਰਤ (ਰਾਸ਼ਟਰੀ)"
}

OR_MAP = {
  "home.workflow.mostUsed": "ସର୍ବାଧିକ ବ୍ୟବହୃତ",
  "home.hero.multilingual": "ବହୁଭାଷୀ ସମର୍ଥନ",
  "home.hero.multilingual_title": "୨୨ଟି ଭାରତୀୟ ଭାଷା + ଇଂରାଜୀରେ ଉପଲବ୍ଧ",
  "home.hero.multilingual_desc": "ସମ୍ପୂର୍ଣ୍ଣ ପ୍ଲାଟଫର୍ମ — AI ଉତ୍ତର, ପ୍ରମାଣ କାର୍ଡ ଏବଂ ବର୍ଗୀକରଣ ବ୍ୟାଖ୍ୟା ସହିତ — ଭାରତର ସମସ୍ତ ୨୨ଟି ସରକାରୀ ଭାଷାରେ ଏବଂ ଇଂରାଜୀରେ ଉପଲବ୍ଧ। ଆଇନଗତ ଶବ୍ଦାବଳୀ ସେଗୁଡ଼ିକର ପ୍ରାମାଣିକ ରୂପରେ ସଂରକ୍ଷିତ।",
  "home.features.versioning_updates": "ସଂସ୍କରଣ ଅଦ୍ୟତନ",
  "home.features.abstention_protects": "ନିରାପଦ ନିବୃତ୍ତି ସୁରକ୍ଷା",
  "home.workflows.heading": "ଆପଣ କ'ଣ କରିବାକୁ ଚାହାଁନ୍ତି?",
  "home.intake.ayurvedicFormulation": "ଆୟୁର୍ବେଦିକ ଯୋଗ (ଫର୍ମୁଲେସନ୍)",
  "home.intake.ayurvedicFormulationHint": "ଶାସ୍ତ୍ରୀୟ କିମ୍ବା ମାଲିକାନା ବହୁ-ହର୍ବାଲ୍ ମିଶ୍ରଣ",
  "home.intake.herbalProduct": "ହର୍ବାଲ୍ ଉତ୍ପାଦ",
  "home.intake.herbalProductHint": "ନିର୍ଯ୍ୟାସ, ଖାଦ୍ୟ ସପ୍ଲିମେଣ୍ଟ, ଫାଇଟୋମେଡିସିନ୍",
  "home.intake.plantResource": "ଉଦ୍ଭିଦ / ଜୈବିକ ସମ୍ବଳ",
  "home.intake.plantResourceHint": "ଔଷଧୀୟ ଉଦ୍ଭିଦ, ABS/NBA ପୂର୍ବ-ଅନୁମୋଦନ",
  "home.intake.traditionalKnowledge": "ପାରମ୍ପରିକ ଜ୍ଞାନ",
  "home.intake.traditionalKnowledgeHint": "ଶାସ୍ତ୍ରୀୟ ଗ୍ରନ୍ଥ, TKDL ପୂର୍ବ-କଳା ସମୀକ୍ଷା",
  "home.intake.novelProcess": "ନୂତନ ପ୍ରକ୍ରିୟା",
  "home.intake.novelProcessHint": "ନିଷ୍କାସନ, ସ୍ଥିରୀକରଣ ଏବଂ Section 3(p) ଯାଞ୍ଚ",
  "home.intake.brandIdentity": "ବ୍ରାଣ୍ଡ ପରିଚୟ",
  "home.intake.brandIdentityHint": "ଟ୍ରେଡମାର୍କ, ବର୍ଗ ୫/୩/୩୦/୪୪",
  "home.intake.geographicalIdentity": "ଭୌଗୋଳିକ ପରିଚୟ",
  "home.intake.geographicalIdentityHint": "GI ସୂଚକ, ମୂଳ ପ୍ରମାଣପତ୍ର",
  "home.intake.regulatoryQuestion": "ନିୟାମକ ପ୍ରଶ୍ନ",
  "home.intake.regulatoryQuestionHint": "FSSAI, AYUSH, Rule 158B, Schedule T",
  "home.demo.badge": "ପ୍ରତ୍ୟକ୍ଷ ସଂବିଧାନିକ ପ୍ରଦର୍ଶନ",
  "home.demo.simulation": "ନିୟାମକ ସିମ୍ୟୁଲେସନ୍",
  "home.demo.title": "ଅପରିଷ୍କୃତ ଧାରଣାରୁ ଆଇନଗତ ସୁରକ୍ଷା ପର୍ଯ୍ୟନ୍ତ",
  "home.demo.story": "ଅଶ୍ୱଗନ୍ଧା-ବ୍ରାହ୍ମୀ ସିରପ୍ କିପରି ବିଶ୍ଳେଷଣ କରାଯାଏ ତାହା ଦେଖନ୍ତୁ: Section 3(p) ପୂର୍ବ-କଳା, Rule 158B ଅନୁପାଳନ, FSSAI ଆୟୁଷ ଆହାର ବର୍ଗୀକରଣ ଏବଂ ABS ପୂର୍ବ-ଅନୁମୋଦନ ଆବଶ୍ୟକତା।",
  "home.demo.notice": "ସମସ୍ତ ସୁପାରିଶ ସିଧାସଳଖ ସରକାରୀ ଗେଜେଟ୍ ନିୟମ ସହିତ ସଂଯୁକ୍ତ।",
  "home.demo.startCase": "ଏହି ମାମଲା ଆରମ୍ଭ କରନ୍ତୁ",
  "home.demo.inspectDossier": "ନମୁନା ଡୋଜିଅର୍ ଯାଞ୍ଚ କରନ୍ତୁ",
  "home.demo.step1.label": "ଉପାଦାନ ବିଶ୍ଳେଷଣ",
  "home.demo.step1.sub": "ଅଶ୍ୱଗନ୍ଧା + ବ୍ରାହ୍ମୀ ସିରପ୍",
  "home.demo.step2.label": "TKDL ଅନୁସନ୍ଧାନ",
  "home.demo.step2.sub": "ଭାବପ୍ରକାଶ ଏବଂ ଚରକ ସଂହିତା ଉଦ୍ଧୃତି",
  "home.demo.step3.label": "Section 3(p) ବିପଦ",
  "home.demo.step3.sub": "ପାରମ୍ପରିକ ଜ୍ଞାନ ପେଟେଣ୍ଟ ବର୍ଜନ",
  "home.demo.step4.label": "Rule 158B ଯାଞ୍ଚ",
  "home.demo.step4.sub": "ଶାସ୍ତ୍ରୀୟ ଗ୍ରନ୍ଥ ପ୍ରମାଣ ପଥ",
  "home.demo.step5.label": "FSSAI ବନାମ AYUSH",
  "home.demo.step5.sub": "ଆୟୁଷ ଆହାର ବର୍ଗୀକରଣ ବିକଳ୍ପ",
  "home.demo.step6.label": "NBA / ABS ଅନୁମୋଦନ",
  "home.demo.step6.sub": "Form III ଜୈବିକ ସମ୍ବଳ ଆବେଦନ",
  "home.demo.step7.label": "କାର୍ଯ୍ୟ ଯୋଜନା",
  "home.demo.step7.sub": "ସୁରକ୍ଷା ରଣନୀତି ଏବଂ ଦାଖଲ",
  "home.evidence.sample": "ନମୁନା ସଂବିଧାନିକ ପ୍ରମାଣ",
  "home.evidence.actIndia": "ପେଟେଣ୍ଟ ଆଇନ ୧୯୭୦ (ଭାରତ)",
  "home.evidence.strength": "ଆଇନଗତ ପ୍ରମାଣ ଶକ୍ତି",
  "home.evidence.high": "ଉଚ୍ଚ",
  "home.evidence.whyRelevant": "ଏହା କାହିଁକି ପ୍ରଯୁଜ୍ୟ: ଯଦି କୌଣସି ଦାବି ପାରମ୍ପରିକ ଜ୍ଞାନର କେବଳ ସମଷ୍ଟି ହୁଏ, ତେବେ Section 3(p) ଅଧୀନରେ ପେଟେଣ୍ଟ ପ୍ରତ୍ୟାଖ୍ୟାନ କରାଯାଏ।",
  "home.evidence.viewSource": "ସରକାରୀ ଉତ୍ସ ଦେଖନ୍ତୁ",
  "home.evidence.disclaimer": "ଏହି ଅଂଶଟି ଡିଜିଟାଲ୍ ସ୍ୱାକ୍ଷରିତ ଭାରତ ସରକାରଙ୍କ ଗେଜେଟ୍‌ରୁ ଯାଞ୍ଚ ହୋଇଛି।",
  "home.multilingual.badge": "୨୨ଟି ଭାଷା + ଇଂରାଜୀ",
  "home.multilingual.fullSupport": "ଭାରତର ସମସ୍ତ ୨୨ଟି ସରକାରୀ ଭାଷାରେ ପୂର୍ଣ୍ଣ ସମର୍ଥନ",
  "home.multilingual.more": "ଅଧିକ ଭାଷା",
  "home.multilingual.all22": "ଭାରତୀୟ ସମ୍ବିଧାନର ଅଷ୍ଟମ ଅନୁସୂଚୀର ସମସ୍ତ ୨୨ଟି ଭାଷାରେ ଉପଲବ୍ଧ",
  "home.domain.patent": "ପେଟେଣ୍ଟ (ଧାରା ୩(p) ଏବଂ ୩(e))",
  "home.domain.patentDesc": "ପାରମ୍ପରିକ ଜ୍ଞାନ ବର୍ଜନ, ନୂତନତା ଏବଂ ପୂର୍ବ-କଳା ବିଶ୍ଳେଷଣ।",
  "home.domain.trademark": "ଟ୍ରେଡମାର୍କ",
  "home.domain.trademarkDesc": "ଆୟୁର୍ବେଦିକ ବ୍ରାଣ୍ଡ, ଲୋଗୋ, ବର୍ଗ ୫ ଏବଂ ଔଷଧ ବର୍ଗୀକରଣ ପଞ୍ଜୀକରଣ।",
  "home.domain.gi": "ଭୌଗୋଳିକ ସୂଚକ (GI)",
  "home.domain.giDesc": "ସ୍ଥାନୀୟ ଉଦ୍ଭିଦ ଏବଂ ପାରମ୍ପରିକ ଔଷଧ ପ୍ରଣାଳୀର ସୁରକ୍ଷା।",
  "home.domain.plantVariety": "ଉଦ୍ଭିଦ କିସମ ସୁରକ୍ଷା (PPV&FR)",
  "home.domain.plantVarietyDesc": "କୃଷକ ଅଧିକାର ଏବଂ ଔଷଧୀୟ ଉଦ୍ଭିଦ କିସମ ପଞ୍ଜୀକରଣ।",
  "home.domain.copyright": "କପିରାଇଟ୍",
  "home.domain.copyrightDesc": "ଗବେଷଣା ଦଲିଲ, ଶାସ୍ତ୍ରୀୟ ଟୀକା ଏବଂ ଡିଜିଟାଲ୍ ଡାଟାବେସ୍ ସୁରକ୍ଷା।",
  "home.domain.industrialDesign": "ଶିଳ୍ପ ଡିଜାଇନ୍",
  "home.domain.industrialDesignDesc": "ଔଷଧ ବିତରଣ ଉପକରଣ, ବୋତଲ ଏବଂ ପ୍ୟାକେଜିଂ ଡିଜାଇନ୍।",
  "home.domain.tk": "ପାରମ୍ପରିକ ଜ୍ଞାନ (TKDL)",
  "home.domain.tkDesc": "ଆୟୁର୍ବେଦ, ସିଦ୍ଧ ଏବଂ ୟୁନାନୀ ଜ୍ଞାନର ଆନ୍ତର୍ଜାତୀୟ ସୁରକ୍ଷା।",
  "home.domain.abs": "ଜୈବ ବିବିଧତା ଏବଂ ABS",
  "home.domain.absDesc": "ଜାତୀୟ ଜୈବବିବିଧତା ପ୍ରାଧିକରଣ (NBA) Form III ଅନୁମୋଦନ।",
  "home.domain.ayush": "ଆୟୁଷ (AYUSH) ନିୟମାବଳୀ",
  "home.domain.ayushDesc": "ଔଷଧ ଏବଂ ପ୍ରସାଧନ ସାମଗ୍ରୀ ଆଇନ, ଶାସ୍ତ୍ରୀୟ ଗ୍ରନ୍ଥ ରେଫରେନ୍ସ।",
  "home.domain.fssaiDesc": "ଆୟୁଷ ଆହାର ନିୟମାବଳୀ, ପୋଷଣ ସପ୍ଲିମେଣ୍ଟ ଏବଂ ସୁରକ୍ଷା ମାନଦଣ୍ଡ।",
  "home.domain.drugsCosmetics": "ଔଷଧ ଏବଂ ପ୍ରସାଧନ ସାମଗ୍ରୀ ଆଇନ",
  "home.domain.drugsCosmeticsDesc": "Rule 158B ପ୍ରମାଣ ଏବଂ Schedule T GMP ମାନଦଣ୍ଡ।",
  "home.domain.internationalIp": "ଆନ୍ତର୍ଜାତୀୟ ବୌଦ୍ଧିକ ସମ୍ପତ୍ତି",
  "home.domain.internationalIpDesc": "PCT, ପ୍ୟାରିସ୍ କନଭେନସନ୍ ଏବଂ ନାଗୋୟା ପ୍ରୋଟୋକଲ୍।",
  "home.pipeline.question": "ପ୍ରଶ୍ନ",
  "home.pipeline.classify": "ବର୍ଗୀକରଣ",
  "home.pipeline.evidence": "ପ୍ରମାଣ",
  "home.pipeline.intelligence": "ଇଣ୍ଟେଲିଜେନ୍ସ",
  "home.pipeline.action": "ପଦକ୍ଷେପ",
  "home.domain.plantVarietyProtection": "ଉଦ୍ଭିଦ କିସମ ସୁରକ୍ଷା",
  "nav.quick.herbalPatent": "ହର୍ବାଲ୍ ପେଟେଣ୍ଟ ଯୋଗ୍ୟତା",
  "nav.quick.fssaiRules": "FSSAI ଆୟୁଷ ଆହାର ନିୟମ",
  "nav.quick.giProtection": "ଔଷଧୀୟ ଉଦ୍ଭିଦର GI ସୁରକ୍ଷା",
  "nav.quick.absNagoya": "ABS ନାଗୋୟା ପ୍ରୋଟୋକଲ୍ ଅନୁପାଳନ",
  "nav.quick.section3p": "Section 3(p) ପାରମ୍ପରିକ ଜ୍ଞାନ ବର୍ଜନ",
  "nav.quick.tkNeem": "ନିମ୍ବ ଏବଂ ହଳଦୀ ପେଟେଣ୍ଟ ବିରୋଧ",
  "wizard.stepProgress": "ପର୍ଯ୍ୟାୟ ପ୍ରଗତି",
  "wizard.stepPrev": "ପୂର୍ବ ପର୍ଯ୍ୟାୟ",
  "wizard.stepNext": "ପରବର୍ତ୍ତୀ ପର୍ଯ୍ୟାୟ",
  "wizard.stepSaveRoadmap": "ମାମଲା ସଂରକ୍ଷଣ କରନ୍ତୁ ଏବଂ ରୋଡମ୍ୟାପ୍ ପ୍ରସ୍ତୁତ କରନ୍ତୁ",
  "wizard.backToCases": "ମୋର ମାମଲାକୁ ଫେରନ୍ତୁ",
  "wizard.guidedSetup": "ନିର୍ଦ୍ଦେଶିତ ବୌଦ୍ଧିକ ସମ୍ପତ୍ତି ଏବଂ ନିୟାମକ ସେଟଅପ୍",
  "wizard.gap.title": "ପ୍ରମାଣ ଅନ୍ତର ମିଳିଲା",
  "wizard.gap.desc": "ଏହି ଯୋଗ ପ୍ରକାର ପାଇଁ ନିର୍ଦ୍ଦିଷ୍ଟ ଶାସ୍ତ୍ରୀୟ ପ୍ରମାଣର ଆବଶ୍ୟକତା ଥାଇପାରେ।",
  "wizard.gap.fix": "ପ୍ରମାଣ ଅନ୍ତର କିପରି ପୂରଣ କରିବେ ଦେଖନ୍ତୁ",
  "wizard.validation.titleRequired": "ଫର୍ମୁଲେସନ୍ ଶୀର୍ଷକ ଆବଶ୍ୟକ",
  "wizard.dnaReady": "ଫର୍ମୁଲେସନ୍ DNA ପ୍ରସ୍ତୁତ",
  "wizard.ingIndex": "ଉପାଦାନ",
  "wizard.assetNature": "ସମ୍ପତ୍ତିର ପ୍ରକୃତି",
  "wizard.selectTreatises": "ସ୍ୱୀକୃତ ଶାସ୍ତ୍ରୀୟ ଗ୍ରନ୍ଥ ବାଛନ୍ତୁ",
  "wizard.classicalCitation": "ଶାସ୍ତ୍ରୀୟ ରେଫରେନ୍ସ / ଶ୍ଳୋକ ଉଦ୍ଧୃତି",
  "wizard.indicationsLabel": "ଚିକିତ୍ସା ସଙ୍କେତ / ରୋଗାଧିକାର",
  "wizard.indicationsPlaceholder": "ଯଥା: କାସ, ଶ୍ୱାସ, ଜ୍ୱର, ରସାୟନ...",
  "wizard.prepNarrative": "ପ୍ରସ୍ତୁତି ପ୍ରଣାଳୀର ବିବରଣୀ",
  "wizard.prepNarrativePlaceholder": "ଶୋଧନ, ଭାବନା କିମ୍ବା ନିଷ୍କାସନ ପ୍ରକ୍ରିୟା ବିସ୍ତୃତ ଭାବରେ ବର୍ଣ୍ଣନା କରନ୍ତୁ...",
  "wizard.commercialPathway": "ବାଣିଜ୍ୟିକ ପଥ",
  "wizard.targetJurisdictionTitle": "ଲକ୍ଷ୍ୟ ଅଧିକାର କ୍ଷେତ୍ର",
  "wizard.supportingDocsTitle": "ସହାୟକ ଦଲିଲ ଏବଂ ପ୍ରମାଣ",
  "wizard.docAddPlaceholder": "ଦଲିଲର ନାମ କିମ୍ବା ରେଫରେନ୍ସ ଲେଖନ୍ତୁ...",
  "wizard.addDocBtn": "ଦଲିଲ ଯୋଡନ୍ତୁ",
  "wizard.plantPart": "ବ୍ୟବହୃତ ଉଦ୍ଭିଦ ଅଂଶ",
  "wizard.sourcingType": "ଉତ୍ସ ପ୍ରକାର",
  "wizard.cat.ayurvedic": "ଆୟୁର୍ବେଦିକ ଯୋଗ",
  "wizard.cat.ayurvedicDesc": "ପାରମ୍ପରିକ କିମ୍ବା ମାଲିକାନା ଔଷଧ",
  "wizard.cat.herbal": "ହର୍ବାଲ୍ ଉତ୍ପାଦ",
  "wizard.cat.herbalDesc": "ଉଦ୍ଭିଦ ନିର୍ଯ୍ୟାସ କିମ୍ବା ସପ୍ଲିମେଣ୍ଟ",
  "wizard.cat.traditional": "ପାରମ୍ପରିକ ଜ୍ଞାନ",
  "wizard.cat.traditionalDesc": "ପାରମ୍ପରିକ ଅଭ୍ୟାସ କିମ୍ବା ଗ୍ରନ୍ଥ",
  "wizard.cat.plant": "ଜୈବିକ ସମ୍ବଳ",
  "wizard.cat.plantDesc": "ଉଦ୍ଭିଦ କିମ୍ବା ଜୈବ ପଦାର୍ଥ",
  "wizard.cat.process": "ନୂତନ ପ୍ରକ୍ରିୟା",
  "wizard.cat.processDesc": "ନିଷ୍କାସନ କିମ୍ବା ଉତ୍ପାଦନ ପଦ୍ଧତି",
  "wizard.cat.brand": "ବ୍ରାଣ୍ଡ କିମ୍ବା ଉତ୍ପାଦ ନାମ",
  "wizard.cat.brandDesc": "ଟ୍ରେଡମାର୍କ ସୁରକ୍ଷା",
  "wizard.prep.classical": "ଶାସ୍ତ୍ରୀୟ ବିଧି",
  "wizard.prep.classicalDesc": "ଅନୁମୋଦିତ ସଂହିତା ଅନୁଯାୟୀ ପ୍ରସ୍ତୁତ",
  "wizard.prep.extract": "ମାନକୀକୃତ ନିର୍ଯ୍ୟାସ",
  "wizard.prep.extractDesc": "ସକ୍ରିୟ ଉପାଦାନର ଜଳୀୟ/ଆଲକୋହଲ ନିର୍ଯ୍ୟାସ",
  "wizard.prep.novel": "ନୂତନ ପ୍ରଯୁକ୍ତିବିଦ୍ୟା",
  "wizard.prep.novelDesc": "ନାନୋପାର୍ଟିକଲ୍ କିମ୍ବା ଉନ୍ନତ ଡେଲିଭରୀ ସିଷ୍ଟମ୍",
  "wizard.commercial.domestic": "ଘରୋଇ ଭାରତୀୟ ବଜାର",
  "wizard.commercial.domesticDesc": "ଭାରତରେ ଉତ୍ପାଦନ ଏବଂ ବିକ୍ରୟ",
  "wizard.commercial.export": "ଆନ୍ତର୍ଜାତୀୟ ରପ୍ତାନି",
  "wizard.commercial.exportDesc": "ବିଶ୍ୱ ବଜାରରେ ବିକ୍ରୟ",
  "wizard.commercial.rd": "ଗବେଷଣା ଏବଂ ବିକାଶ",
  "wizard.commercial.rdDesc": "ପ୍ରି-କ୍ଲିନିକାଲ୍ କିମ୍ବା କ୍ଲିନିକାଲ୍ ଟ୍ରାଏଲ୍",
  "wizard.commercial.licensing": "ପ୍ରଯୁକ୍ତିବିଦ୍ୟା ଲାଇସେନ୍ସ",
  "wizard.commercial.licensingDesc": "ତୃତୀୟ ପକ୍ଷକୁ ଲାଇସେନ୍ସ ପ୍ରଦାନ",
  "wizard.jur.india": "ଭାରତ",
  "wizard.jur.indiaDesc": "ଭାରତୀୟ ପେଟେଣ୍ଟ ଏବଂ ନିୟାମକ ଆଇନ",
  "wizard.jur.us": "ଯୁକ୍ତରାଷ୍ଟ୍ର ଆମେରିକା",
  "wizard.jur.usDesc": "US FDA ଏବଂ USPTO ନିୟମ",
  "wizard.jur.eu": "ୟୁରୋପୀୟ ୟୁନିଅନ୍",
  "wizard.jur.euDesc": "EMA ଏବଂ EPO ନିୟମାବଳୀ",
  "wizard.jur.intl": "ଆନ୍ତର୍ଜାତୀୟ (PCT)",
  "wizard.jur.intlDesc": "ଗ୍ଲୋବାଲ୍ ପେଟେଣ୍ଟ ସହଯୋଗ ଚୁକ୍ତି",
  "wizard.claim.therapeutic": "ଚିକିତ୍ସା ସମ୍ବନ୍ଧୀୟ ଦାବି",
  "wizard.claim.nutritional": "ପୋଷଣ କିମ୍ବା ଖାଦ୍ୟ ଦାବି",
  "wizard.claim.cosmetic": "ପ୍ରସାଧନ ସାମଗ୍ରୀ ଦାବି",
  "wizard.claim.wellness": "ସାଧାରଣ ସ୍ୱାସ୍ଥ୍ୟ ଏବଂ ସୁସ୍ଥତା",
  "explore.breadcrumb": "ନିୟାମକ ଢାଞ୍ଚା ଅନୁସନ୍ଧାନ କରନ୍ତୁ",
  "explore.searchPlaceholder": "ଫର୍ମୁଲେସନ୍, ପେଟେଣ୍ଟ, Section 3(p), Rule 158B, ABS, TKDL ଖୋଜନ୍ତୁ...",
  "explore.allFrameworks": "ସମସ୍ତ ନିୟାମକ ଢାଞ୍ଚା",
  "explore.ipPatents": "IP ଏବଂ ପେଟେଣ୍ଟ",
  "explore.ayushFssai": "ଆୟୁଷ ଏବଂ FSSAI",
  "explore.bioAbs": "ଜୈବବିବିଧତା ଏବଂ ABS",
  "explore.tkTkdl": "ପାରମ୍ପରିକ ଜ୍ଞାନ ଏବଂ TKDL",
  "explore.statutoryHighlights": "ସଂବିଧାନିକ ହାଇଲାଇଟ୍",
  "explore.noItems": "ଚୟନିତ ବର୍ଗରେ କୌଣସି ନିୟାମକ ଢାଞ୍ଚା ମିଳିଲା ନାହିଁ।",
  "explore.actSec3p": "ପେଟେଣ୍ଟ ଆଇନ ୧୯୭୦ — ଧାରା ୩(p) ଏବଂ ୩(e)",
  "explore.actRule158b": "ଔଷଧ ଏବଂ ପ୍ରସାଧନ ସାମଗ୍ରୀ ନିୟମ ୧୯୪୫ — ନିୟମ ୧୫୮B",
  "explore.actAbs": "ଜୈବିକ ବିବିଧତା ଆଇନ ୨୦୦୨ — Form III ABS",
  "explore.actAahar": "ଆୟୁଷ ଆହାର ନିୟମାବଳୀ ୨୦୨୨ — FSSAI ଢାଞ୍ଚା",
  "explore.actTkdl": "ପାରମ୍ପରିକ ଜ୍ଞାନ ଡିଜିଟାଲ୍ ଲାଇବ୍ରେରୀ (TKDL) ଢାଞ୍ଚା",
  "explore.actGi": "ଭୌଗୋଳିକ ସୂଚକ (ପଞ୍ଜୀକରଣ ଏବଂ ସୁରକ୍ଷା) ଆଇନ ୧୯୯୯",
  "evidence.breadcrumb": "ସଂବିଧାନିକ ପ୍ରମାଣ ସଂଗ୍ରହ",
  "evidence.allAuthorities": "ସମସ୍ତ ନିୟାମକ ପ୍ରାଧିକରଣ",
  "evidence.allTypes": "ସମସ୍ତ ସଂବିଧାନିକ ପ୍ରକାର",
  "evidence.act": "ଆଇନ (Act)",
  "evidence.rule": "ନିୟମ (Rule)",
  "evidence.gazetteNotification": "ଗେଜେଟ୍ ବିଜ୍ଞପ୍ତି",
  "evidence.pharmacopoeialStandard": "ଫାର୍ମାକୋପିଆଲ୍ ମାନଦଣ୍ଡ",
  "evidence.treaty": "ଆନ୍ତର୍ଜାତୀୟ ଚୁକ୍ତି",
  "evidence.verifiedAuthority": "ଯାଞ୍ଚ ହୋଇଥିବା ନିୟାମକ ପ୍ରାଧିକରଣ",
  "evidence.cryptoHash": "କ୍ରିପ୍ଟୋଗ୍ରାଫିକ୍ ଫୋରେନସିକ୍ ହ୍ୟାସ୍",
  "evidence.plainSummary": "ସରଳ ସାରାଂଶ",
  "evidence.officialExcerpt": "ସରକାରୀ ସଂବିଧାନିକ ଉଦ୍ଧୃତି",
  "evidence.inspectCitation": "ଆଇନଗତ ଉଦ୍ଧୃତି ଯାଞ୍ଚ କରନ୍ତୁ",
  "evidence.noCorpusFound": "କୌଣସି ସଂବିଧାନିକ ପ୍ରମାଣ ମିଳିଲା ନାହିଁ",
  "evidence.noCorpusHint": "ଆପଣଙ୍କ ଅନୁସନ୍ଧାନ ମାନଦଣ୍ଡ ବଦଳାନ୍ତୁ କିମ୍ବା ଫିଲ୍ଟର୍ ହଟାନ୍ତୁ।",
  "caseDetail.loading": "ସଂବିଧାନିକ ସୂଚନା ଲୋଡ୍ ହେଉଛି...",
  "caseDetail.notFound": "ମାମଲା ମିଳିଲା ନାହିଁ",
  "caseDetail.notFoundDesc": "ଅନୁରୋଧ କରାଯାଇଥିବା ମାମଲା ରେକର୍ଡ ନାହିଁ କିମ୍ବା ହଟାଇ ଦିଆଯାଇଛି।",
  "caseDetail.returnWorkspace": "ମାମଲା ୱାର୍କସ୍ପେସ୍‌କୁ ଫେରନ୍ତୁ",
  "caseDetail.juryDemo": "ଜୁରି ଡେମୋ ମୋଡ୍",
  "caseDetail.simulateMissing": "ଅନୁପସ୍ଥିତ ଦଲିଲ ଅନୁକରଣ କରନ୍ତୁ",
  "caseDetail.exportDossier": "ମାମଲା ଡୋଜିଅର୍ ରପ୍ତାନି କରନ୍ତୁ",
  "caseDetail.timeMachine": "ନିୟାମକ ଟାଇମ୍ ମେସିନ୍",
  "caseDetail.editFormulation": "ଫର୍ମୁଲେସନ୍ ସମ୍ପାଦନ କରନ୍ତୁ",
  "caseDetail.tabSummary": "ସାରାଂଶ ଏବଂ ରାୟ",
  "caseDetail.tabDna": "ଫର୍ମୁଲେସନ୍ DNA",
  "caseDetail.tabClassifications": "ପ୍ରାର୍ଥୀ ବର୍ଗୀକରଣ",
  "caseDetail.tabRegulations": "ପ୍ରଯୁଜ୍ୟ ନିୟମାବଳୀ",
  "caseDetail.tabIpPathways": "ବୌଦ୍ଧିକ ସମ୍ପତ୍ତି ପଥ",
  "caseDetail.tabAbs": "ABS ଅନୁପାଳନ",
  "caseDetail.tabPriorArt": "ପୂର୍ବ-କଳା ବିଶ୍ଳେଷଣ",
  "caseDetail.tabEvidenceGaps": "ପ୍ରମାଣ ଅନ୍ତର",
  "caseDetail.tabEvidenceChain": "ସଂବିଧାନିକ ପ୍ରମାଣ ଶୃଙ୍ଖଳ",
  "caseDetail.tabNextActions": "ପରବର୍ତ୍ତୀ ପ୍ରସ୍ତାବିତ ପଦକ୍ଷେପ",
  "caseDetail.classificationVerdict": "ବର୍ଗୀକରଣ ରାୟ",
  "caseDetail.evidenceStrength": "ପ୍ରମାଣର ଶକ୍ତି",
  "caseDetail.governingAuthority": "ନିୟାମକ ପ୍ରାଧିକରଣ",
  "caseDetail.statutoryBasis": "ସଂବିଧାନିକ ଆଧାର",
  "caseDetail.coreExcerpt": "ମୁଖ୍ୟ ଆଇନଗତ ଉଦ୍ଧୃତି",
  "caseDetail.plainExplanation": "ସରଳ ବ୍ୟାଖ୍ୟା",
  "caseDetail.whyThis": "ଏହି ବର୍ଗୀକରଣ କାହିଁକି ପ୍ରଯୁଜ୍ୟ?",
  "auth.showPassword": "ପାସୱାର୍ଡ ଦେଖାନ୍ତୁ",
  "auth.hidePassword": "ପାସୱାର୍ଡ ଲୁଚାନ୍ତୁ",
  "auth.charRequirement": "୮+ ଅକ୍ଷର",
  "auth.upperRequirement": "ଅତି କମରେ ଗୋଟିଏ ବଡ଼ ଅକ୍ଷର (Uppercase)",
  "auth.numRequirement": "ଅତି କମରେ ଗୋଟିଏ ସଂଖ୍ୟା (Number)",
  "auth.demoAdmin": "ଡେମୋ ଆଡମିନ୍ ପ୍ରମାଣପତ୍ର ବ୍ୟବହାର କରନ୍ତୁ",
  "intel.drawerTitle": "ସଂବିଧାନିକ ପ୍ରମାଣ ଡ୍ରୟର",
  "intel.authority": "ନିୟାମକ ପ୍ରାଧିକରଣ",
  "intel.hierarchy": "ଆଇନଗତ ପ୍ରାଥମିକତା କ୍ରମ",
  "intel.version": "ସରକାରୀ ସଂସ୍କରଣ",
  "intel.excerpt": "ଆଇନଗତ ଉଦ୍ଧୃତି",
  "intel.plainSummary": "ସରଳ ଆଇନଗତ ସାରାଂଶ",
  "intel.gazetteSource": "ଗେଜେଟ୍ ଉତ୍ସ",
  "intel.openExternal": "ସରକାରୀ ଗେଜେଟ୍ ଖୋଲନ୍ତୁ",
  "intel.closeDrawer": "ଡ୍ରୟର୍ ବନ୍ଦ କରନ୍ତୁ",
  "intel.gapsTitle": "ପ୍ରମାଣ ଅନ୍ତର ଏବଂ ସମାଧାନ ରଣନୀତି",
  "intel.resolutionStrategy": "ସମାଧାନ ରଣନୀତି",
  "intel.chainTitle": "ସଂବିଧାନିକ ପ୍ରମାଣ ଶୃଙ୍ଖଳ",
  "intel.factTriggered": "ସକ୍ରିୟ ତଥ୍ୟ",
  "intel.ruleApplied": "ପ୍ରୟୋଗ କରାଯାଇଥିବା ନିୟମ",
  "intel.matrixTitle": "ସଂବିଧାନିକ ଇଣ୍ଟେଲିଜେନ୍ସ ବୋର୍ଡ",
  "intel.timeMachineTitle": "ନିୟାମକ ଟାଇମ୍ ମେସିନ୍",
  "intel.historicalAmendments": "ଐତିହାସିକ ସଂଶୋଧନ",
  "intel.uploadTitle": "ସହାୟକ ଦଲିଲ ଅପଲୋଡ୍ କରନ୍ତୁ",
  "intel.dragDrop": "ଦଲିଲ ଏଠାରେ ଟାଣନ୍ତୁ ଏବଂ ଛାଡ଼ନ୍ତୁ କିମ୍ବା ବ୍ରାଉଜ୍ କରନ୍ତୁ",
  "intel.whyTitle": "ଆପଣ ଏହା କାହିଁକି ଦେଖୁଛନ୍ତି?",
  "intel.deterministicVerification": "ନିର୍ଦ୍ଧାରିତ ସଂବିଧାନିକ ଯାଞ୍ଚ",
  "search.breadcrumb": "ଅନୁସନ୍ଧାନ",
  "search.heading": "ସଂବିଧାନିକ ଏବଂ ପେଟେଣ୍ଟ ଅନୁସନ୍ଧାନ",
  "search.btnSearch": "ଖୋଜନ୍ତୁ",
  "search.suggestedLabel": "ପ୍ରସ୍ତାବିତ ପ୍ରଶ୍ନ",
  "search.recentLabel": "ସାମ୍ପ୍ରତିକ ଅନୁସନ୍ଧାନ",
  "search.clearLabel": "ସଫା କରନ୍ତୁ",
  "search.advancedFilters": "ଉନ୍ନତ ଫିଲ୍ଟର୍",
  "search.hideAdvancedFilters": "ଉନ୍ନତ ଫିଲ୍ଟର୍ ଲୁଚାନ୍ତୁ",
  "search.allAuthorities": "ସମସ୍ତ ପ୍ରାଧିକରଣ",
  "search.allJurisdictions": "ସମସ୍ତ ଅଧିକାର କ୍ଷେତ୍ର",
  "assistant.breadcrumb": "AI ସହାୟକ",
  "assistant.bannerActive": "ସକ୍ରିୟ ମାମଲାର ପରିପ୍ରେକ୍ଷୀରେ କାର୍ଯ୍ୟରତ",
  "assistant.suggestedInquiries": "ପ୍ରସ୍ତାବିତ ଅନୁସନ୍ଧାନ",
  "assistant.directAnswer": "ସିଧାସଳଖ ସଂବିଧାନିକ ଉତ୍ତର",
  "assistant.ruleConstraints": "ପ୍ରଯୁଜ୍ୟ ନିୟମ ଏବଂ କଟକଣା",
  "assistant.officialCitations": "ସରକାରୀ ଆଇନଗତ ଉଦ୍ଧୃତି",
  "assistant.evidenceGaps": "ମିଳିଥିବା ପ୍ରମାଣ ଅନ୍ତର",
  "assistant.disclaimerFooter": "ଆଇନଗତ ଦାବିତ୍ୟାଗ: ଏହି ପ୍ରଣାଳୀ କେବଳ ସୂଚନା ଉଦ୍ଦେଶ୍ୟରେ ସଂବିଧାନିକ ମାର୍ଗଦର୍ଶନ ପ୍ରଦାନ କରେ।",
  "report.returnDossier": "ମାମଲା ଡୋଜିଅର୍‌କୁ ଫେରନ୍ତୁ",
  "report.tableIngredients": "ଫର୍ମୁଲେସନ୍ ଉପାଦାନ ଏବଂ ବିବରଣୀ",
  "report.name": "ଉପାଦାନର ନାମ",
  "report.botanical": "ଉଦ୍ଭିଦ ବିଜ୍ଞାନ ନାମ",
  "report.sanskrit": "ସଂସ୍କୃତ ନାମ",
  "report.part": "ବ୍ୟବହୃତ ଅଂଶ",
  "report.percentage": "ଅନୁପାତ / ପ୍ରତିଶତ",
  "report.source": "ରେଫରେନ୍ସ ଉତ୍ସ",
  "report.origin": "ଭୌଗୋଳିକ ଉତ୍ସ",
  "cases.noMatch": "ଆପଣଙ୍କ ଅନୁସନ୍ଧାନ ସହିତ ମେଳ ଖାଉଥିବା କୌଣସି ମାମଲା ମିଳିଲା ନାହିଁ।",
  "cases.jurisdictionIndia": "ଭାରତ (ଜାତୀୟ)"
}

AS_MAP = {
  "home.workflow.mostUsed": "সৰ্বাধিক ব্যৱহৃত",
  "home.hero.multilingual": "বহুভাষিক সমৰ্থন",
  "home.hero.multilingual_title": "২২টা ভাৰতীয় ভাষা + ইংৰাজীত উপলব্ধ",
  "home.hero.multilingual_desc": "সম্পূৰ্ণ প্লেটফৰ্ম — AI উত্তৰ, প্ৰমাণ কাৰ্ড আৰু শ্ৰেণীবিভাজন ব্যাখ্যা সহ — ভাৰতৰ সকলো ২২টা চৰকাৰী ভাষাত আৰু ইংৰাজীত উপলব্ধ। আইনগত শব্দাৱলীসমূহ সিহঁতৰ প্ৰামাণিক ৰূপত সংৰক্ষিত।",
  "home.features.versioning_updates": "সংস্কৰণ নৱীকৰণ",
  "home.features.abstention_protects": "নিৰাপদ বিৰতি সুৰক্ষা",
  "home.workflows.heading": "আপুনি কি কৰিব বিচাৰে?",
  "home.intake.ayurvedicFormulation": "আয়ুৰ্বেদিক যোগ (ফৰ্মুলেচন)",
  "home.intake.ayurvedicFormulationHint": "শাস্ত্ৰীয় বা মালিকানাধীন বহু-বনৌষধি মিশ্ৰণ",
  "home.intake.herbalProduct": "বনৌষধি উৎপাদন",
  "home.intake.herbalProductHint": "নিৰ্যাস, খাদ্য পৰিপূৰক, ফাইটোমেডিচিন",
  "home.intake.plantResource": "উদ্ভিদ / জৈৱিক সম্পদ",
  "home.intake.plantResourceHint": "ঔষধি উদ্ভিদ, ABS/NBA পূৰ্ব-অনুমোদন",
  "home.intake.traditionalKnowledge": "পৰম্পৰাগত জ্ঞান",
  "home.intake.traditionalKnowledgeHint": "শাস্ত্ৰীয় গ্ৰন্থ, TKDL পূৰ্ব-কলা পৰ্যালোচনা",
  "home.intake.novelProcess": "নতুন প্ৰক্ৰিয়া",
  "home.intake.novelProcessHint": "নিষ্কাশন, স্থিৰীকৰণ আৰু Section 3(p) পৰীক্ষণ",
  "home.intake.brandIdentity": "ব্ৰেণ্ড পৰিচয়",
  "home.intake.brandIdentityHint": "ট্ৰেডমাৰ্ক, শ্ৰেণী ৫/৩/৩০/৪৪",
  "home.intake.geographicalIdentity": "ভৌগোলিক পৰিচয়",
  "home.intake.geographicalIdentityHint": "GI নিৰ্দেশক, মূল প্ৰমাণপত্ৰ",
  "home.intake.regulatoryQuestion": "নিয়ন্ত্ৰক প্ৰশ্ন",
  "home.intake.regulatoryQuestionHint": "FSSAI, AYUSH, Rule 158B, Schedule T",
  "home.demo.badge": "প্ৰত্যক্ষ বিধিসন্মত প্ৰদৰ্শন",
  "home.demo.simulation": "নিয়ন্ত্ৰক চিমুলেচন",
  "home.demo.title": "কেঁচা ধাৰণাৰ পৰা আইনী সুৰক্ষালৈ",
  "home.demo.story": "অশ্বগন্ধা-ব্ৰাহ্মী চিৰাপৰ বিশ্লেষণ কেনেকৈ কৰা হয় চাওক: Section 3(p) পূৰ্ব-কলা, Rule 158B অনুপালন, FSSAI আয়ুষ আহাৰ শ্ৰেণীবিভাজন আৰু ABS পূৰ্ব-অনুমোদন প্ৰয়োজনীয়তা।",
  "home.demo.notice": "সকলো পৰামৰ্শ পোনপটীয়াকৈ চৰকাৰী গেজেট বিধানৰ সৈতে সংযোজিত।",
  "home.demo.startCase": "এই গোচৰ আৰম্ভ কৰক",
  "home.demo.inspectDossier": "নমুনা ডচিয়াৰ পৰীক্ষা কৰক",
  "home.demo.step1.label": "উপাদান বিশ্লেষণ",
  "home.demo.step1.sub": "অশ্বগন্ধা + ব্ৰাহ্মী চিৰাপ",
  "home.demo.step2.label": "TKDL সন্ধান",
  "home.demo.step2.sub": "ভাবপ্ৰকাশ আৰু চৰক সংহিতা উদ্ধৃতি",
  "home.demo.step3.label": "Section 3(p) বিপদাশংকা",
  "home.demo.step3.sub": "পৰম্পৰাগত জ্ঞান পেটেণ্ট বৰ্জন",
  "home.demo.step4.label": "Rule 158B পৰীক্ষণ",
  "home.demo.step4.sub": "শাস্ত্ৰীয় গ্ৰন্থ প্ৰমাণ পথ",
  "home.demo.step5.label": "FSSAI বনাম AYUSH",
  "home.demo.step5.sub": "আয়ুষ আহাৰ শ্ৰেণীবিভাজন বিকল্প",
  "home.demo.step6.label": "NBA / ABS অনুমোদন",
  "home.demo.step6.sub": "Form III জৈৱিক সম্পদ আবেদন",
  "home.demo.step7.label": "কাৰ্য পৰিকল্পনা",
  "home.demo.step7.sub": "সুৰক্ষা কৌশল আৰু দাখিল",
  "home.evidence.sample": "নমুনা বিধিসন্মত প্ৰমাণ",
  "home.evidence.actIndia": "পেটেণ্ট আইন ১৯৭০ (ভাৰত)",
  "home.evidence.strength": "আইনী প্ৰমাণৰ শক্তি",
  "home.evidence.high": "উচ্চ",
  "home.evidence.whyRelevant": "ই কিয় প্ৰযোজ্য: যদি কোনো দাবী পৰম্পৰাগত জ্ঞানৰ মাত্ৰ সংগ্ৰহ হয়, তেন্তে Section 3(p) ৰ অধীনত পেটেণ্ট নাকচ কৰা হয়।",
  "home.evidence.viewSource": "চৰকাৰী উৎস চাওক",
  "home.evidence.disclaimer": "এই অংশটো ডিজিটেলভাৱে স্বাক্ষৰিত ভাৰত চৰকাৰৰ গেজেটৰ পৰা পৰীক্ষিত।",
  "home.multilingual.badge": "২২টা ভাষা + ইংৰাজী",
  "home.multilingual.fullSupport": "ভাৰতৰ সকলো ২২টা চৰকাৰী ভাষাত সম্পূৰ্ণ সমৰ্থন",
  "home.multilingual.more": "অধিক ভাষা",
  "home.multilingual.all22": "ভাৰতীয় সংবিধানৰ অষ্টম অনুসূচীত উল্লিখিত সকলো ২২টা ভাষাত উপলব্ধ",
  "home.domain.patent": "পেটেণ্ট (ধাৰা ৩(p) আৰু ৩(e))",
  "home.domain.patentDesc": "পৰম্পৰাগত জ্ঞান বৰ্জন, অভিনৱত্ব আৰু পূৰ্ব-কলা বিশ্লেষণ।",
  "home.domain.trademark": "ট্ৰেডমাৰ্ক",
  "home.domain.trademarkDesc": "আয়ুৰ্বেদিক ব্ৰেণ্ড, লোগো, শ্ৰেণী ৫ আৰু ঔষধ শ্ৰেণীবিভাজন পঞ্জীয়ন।",
  "home.domain.gi": "ভৌগোলিক নিৰ্দেশক (GI)",
  "home.domain.giDesc": "স্থানীয় উদ্ভিদ আৰু পৰম্পৰাগত ঔষধ পদ্ধতিৰ সুৰক্ষা।",
  "home.domain.plantVariety": "উদ্ভিদ জাত সুৰক্ষা (PPV&FR)",
  "home.domain.plantVarietyDesc": "কৃষক অধিকাৰ আৰু ঔষধি উদ্ভিদৰ জাত পঞ্জীয়ন।",
  "home.domain.copyright": "কপিৰাইট",
  "home.domain.copyrightDesc": "গৱেষণা নথিপত্ৰ, শাস্ত্ৰীয় ভাষ্য আৰু ডিজিটেল ডাটাবেচ সুৰক্ষা।",
  "home.domain.industrialDesign": "ঔদ্যোগিক ডিজাইন",
  "home.domain.industrialDesignDesc": "ঔষধ বিতৰণ সঁজুলি, বটল আৰু পেকেজিং ডিজাইন।",
  "home.domain.tk": "পৰম্পৰাগত জ্ঞান (TKDL)",
  "home.domain.tkDesc": "আয়ুৰ্বেদ, সিদ্ধ আৰু য়ুনানী জ্ঞানৰ আন্তঃৰাষ্ট্ৰীয় সুৰক্ষা।",
  "home.domain.abs": "জৈৱ বৈচিত্ৰ্য আৰু ABS",
  "home.domain.absDesc": "ৰাষ্ট্ৰীয় জৈৱবৈচিত্ৰ্য কৰ্তৃপক্ষ (NBA) Form III অনুমোদন।",
  "home.domain.ayush": "আয়ুষ (AYUSH) নিয়মসমূহ",
  "home.domain.ayushDesc": "ঔষধ আৰু প্ৰসাধন সামগ্ৰী আইন, শাস্ত্ৰীয় গ্ৰন্থ প্ৰসংগ।",
  "home.domain.fssaiDesc": "আয়ুষ আহাৰ নিয়মসমূহ, পুষ্টি পৰিপূৰক আৰু সুৰক্ষা মানদণ্ড।",
  "home.domain.drugsCosmetics": "ঔষধ আৰু প্ৰসাধন সামগ্ৰী আইন",
  "home.domain.drugsCosmeticsDesc": "Rule 158B প্ৰমাণ আৰু Schedule T GMP মানদণ্ড।",
  "home.domain.internationalIp": "আন্তঃৰাষ্ট্ৰীয় বৌদ্ধিক সম্পদ",
  "home.domain.internationalIpDesc": "PCT, পেৰিছ কনভেনচন আৰু নাগোয়া প্ৰটোকল।",
  "home.pipeline.question": "প্ৰশ্ন",
  "home.pipeline.classify": "শ্ৰেণীবিভাজন",
  "home.pipeline.evidence": "প্ৰমাণ",
  "home.pipeline.intelligence": "ইন্টেলিজেন্স",
  "home.pipeline.action": "পদক্ষেপ",
  "home.domain.plantVarietyProtection": "উদ্ভিদ জাত সুৰক্ষা",
  "nav.quick.herbalPatent": "বনৌষধি পেটেণ্ট যোগ্যতা",
  "nav.quick.fssaiRules": "FSSAI আয়ুষ আহাৰ নিয়ম",
  "nav.quick.giProtection": "ঔষধি উদ্ভিদৰ GI সুৰক্ষা",
  "nav.quick.absNagoya": "ABS নাগোয়া প্ৰটোকল অনুপালন",
  "nav.quick.section3p": "Section 3(p) পৰম্পৰাগত জ্ঞান বৰ্জন",
  "nav.quick.tkNeem": "নিম আৰু হালধি পেটেণ্ট বিৰোধিতা",
  "wizard.stepProgress": "স্তৰৰ অগ্ৰগতি",
  "wizard.stepPrev": "পূৰ্বৱৰ্তী স্তৰ",
  "wizard.stepNext": "পৰৱৰ্তী স্তৰ",
  "wizard.stepSaveRoadmap": "গোচৰ সংৰক্ষণ কৰক আৰু ৰোডমেপ প্ৰস্তুত কৰক",
  "wizard.backToCases": "মোৰ গোচৰলৈ উভতি যাওক",
  "wizard.guidedSetup": "নিৰ্দেশিত বৌদ্ধিক সম্পদ আৰু নিয়ন্ত্ৰক ছেটআপ",
  "wizard.gap.title": "প্ৰমাণৰ ফাঁক ধৰা পৰিছে",
  "wizard.gap.desc": "এই যোগ প্ৰকাৰৰ বাবে নিৰ্দিষ্ট শাস্ত্ৰীয় প্ৰমাণৰ প্ৰয়োজন হ'ব পাৰে।",
  "wizard.gap.fix": "প্ৰমাণৰ ফাঁক কেনেকৈ পূৰণ কৰিব লাগে চাওক",
  "wizard.validation.titleRequired": "ফৰ্মুলেচনৰ শিৰোনাম প্ৰয়োজনীয়",
  "wizard.dnaReady": "ফৰ্মুলেচন DNA সাজু",
  "wizard.ingIndex": "উপাদান",
  "wizard.assetNature": "সম্পদৰ প্ৰকৃতি",
  "wizard.selectTreatises": "স্বীকৃত শাস্ত্ৰীয় গ্ৰন্থ বাছক",
  "wizard.classicalCitation": "শাস্ত্ৰীয় প্ৰসংগ / শ্লোক উদ্ধৃতি",
  "wizard.indicationsLabel": "চিকিৎসা নিৰ্দেশনা / ৰোগাধিকাৰ",
  "wizard.indicationsPlaceholder": "যেনে: কাস, শ্বাস, জ্বৰ, ৰসায়ন...",
  "wizard.prepNarrative": "প্ৰস্তুতি পদ্ধতিৰ বিৱৰণ",
  "wizard.prepNarrativePlaceholder": "শোধন, ভাবনা বা নিষ্কাশন প্ৰক্ৰিয়াৰ বিতং বৰ্ণনা দিয়ক...",
  "wizard.commercialPathway": "বাণিজ্যিক পথ",
  "wizard.targetJurisdictionTitle": "লক্ষ্য এক্তিয়াৰ",
  "wizard.supportingDocsTitle": "সহায়ক নথি আৰু প্ৰমাণ",
  "wizard.docAddPlaceholder": "নথিৰ নাম বা প্ৰসংগ লিখক...",
  "wizard.addDocBtn": "নথি যোগ কৰক",
  "wizard.plantPart": "ব্যৱহৃত উদ্ভিদৰ অংশ",
  "wizard.sourcingType": "উৎসৰ প্ৰকাৰ",
  "wizard.cat.ayurvedic": "আয়ুৰ্বেদিক যোগ",
  "wizard.cat.ayurvedicDesc": "পৰম্পৰাগত বা মালিকানাধীন ঔষধ",
  "wizard.cat.herbal": "বনৌষধি উৎপাদন",
  "wizard.cat.herbalDesc": "উদ্ভিদ নিৰ্যাস বা পৰিপূৰক",
  "wizard.cat.traditional": "পৰম্পৰাগত জ্ঞান",
  "wizard.cat.traditionalDesc": "ঐতিহ্যবাহী অনুশীলন বা গ্ৰন্থ",
  "wizard.cat.plant": "জৈৱিক সম্পদ",
  "wizard.cat.plantDesc": "উদ্ভিদ বা জৈৱ উপাদান",
  "wizard.cat.process": "নতুন প্ৰক্ৰিয়া",
  "wizard.cat.processDesc": "নিষ্কাশন বা উৎপাদন পদ্ধতি",
  "wizard.cat.brand": "ব্ৰেণ্ড বা সামগ্ৰীৰ নাম",
  "wizard.cat.brandDesc": "ট্ৰেডমাৰ্ক সুৰক্ষা",
  "wizard.prep.classical": "শাস্ত্ৰীয় বিধি",
  "wizard.prep.classicalDesc": "অনুমোদিত সংহিতা অনুসৰি প্ৰস্তুত",
  "wizard.prep.extract": "মানসম্পন্ন নিৰ্যাস",
  "wizard.prep.extractDesc": "সক্ৰিয় উপাদানৰ জলীয় বা এলকোহল নিৰ্যাস",
  "wizard.prep.novel": "নতুন প্ৰযুক্তি",
  "wizard.prep.novelDesc": "নেনোপাৰ্টিকল বা উন্নত বিতৰণ ব্যৱস্থা",
  "wizard.commercial.domestic": "ঘৰুৱা ভাৰতীয় বজাৰ",
  "wizard.commercial.domesticDesc": "ভাৰতত উৎপাদন আৰু বিক্ৰী",
  "wizard.commercial.export": "আন্তঃৰাষ্ট্ৰীয় ৰপ্তানি",
  "wizard.commercial.exportDesc": "বিশ্ব বজাৰত বিক্ৰী",
  "wizard.commercial.rd": "গৱেষণা আৰু বিকাশ",
  "wizard.commercial.rdDesc": "প্ৰাক-ক্লিনিকেল বা ক্লিনিকেল পৰীক্ষণ",
  "wizard.commercial.licensing": "প্ৰযুক্তি লাইচেন্সিং",
  "wizard.commercial.licensingDesc": "তৃতীয় পক্ষক লাইচেন্স প্ৰদান",
  "wizard.jur.india": "ভাৰত",
  "wizard.jur.indiaDesc": "ভাৰতীয় পেটেণ্ট আৰু নিয়ন্ত্ৰক আইন",
  "wizard.jur.us": "আমেৰিকা যুক্তৰাষ্ট্ৰ",
  "wizard.jur.usDesc": "US FDA আৰু USPTO নিয়ম",
  "wizard.jur.eu": "ইউৰোপীয় ইউনিয়ন",
  "wizard.jur.euDesc": "EMA আৰু EPO নিয়মসমূহ",
  "wizard.jur.intl": "আন্তঃৰাষ্ট্ৰীয় (PCT)",
  "wizard.jur.intlDesc": "গ্ল'বেল পেটেণ্ট সহযোগিতা চুক্তি",
  "wizard.claim.therapeutic": "থেৰাপিউটিক দাবী",
  "wizard.claim.nutritional": "পুষ্টি বা খাদ্য পৰিপূৰক দাবী",
  "wizard.claim.cosmetic": "প্ৰসাধন দাবী",
  "wizard.claim.wellness": "সাধাৰণ স্বাস্থ্য আৰু সুস্থতা",
  "explore.breadcrumb": "নিয়ন্ত্ৰক গাঁথনি অন্বেষণ কৰক",
  "explore.searchPlaceholder": "ফৰ্মুলেচন, পেটেণ্ট, Section 3(p), Rule 158B, ABS, TKDL সন্ধান কৰক...",
  "explore.allFrameworks": "সকলো নিয়ন্ত্ৰক গাঁথনি",
  "explore.ipPatents": "IP আৰু পেটেণ্ট",
  "explore.ayushFssai": "আয়ুষ আৰু FSSAI",
  "explore.bioAbs": "জৈৱবৈচিত্ৰ্য আৰু ABS",
  "explore.tkTkdl": "পৰম্পৰাগত জ্ঞান আৰু TKDL",
  "explore.statutoryHighlights": "বিধিসন্মত গুৰুত্বপূৰ্ণ বিষয়",
  "explore.noItems": "নিৰ্বাচিত শ্ৰেণীত কোনো নিয়ন্ত্ৰক গাঁথনি পোৱা নগ'ল।",
  "explore.actSec3p": "পেটেণ্ট আইন ১৯৭০ — ধাৰা ৩(p) আৰু ৩(e)",
  "explore.actRule158b": "ঔষধ আৰু প্ৰসাধন সামগ্ৰী নিয়ম ১৯৪৫ — নিয়ম ১৫৮B",
  "explore.actAbs": "জৈৱিক বৈচিত্ৰ্য আইন ২০০২ — Form III ABS",
  "explore.actAahar": "আয়ুষ আহাৰ নিয়মসমূহ ২০২২ — FSSAI গাঁথনি",
  "explore.actTkdl": "পৰম্পৰাগত জ্ঞান ডিজিটেল লাইব্ৰেৰী (TKDL) গাঁথনি",
  "explore.actGi": "ভৌগোলিক নিৰ্দেশক (পঞ্জীয়ন আৰু সুৰক্ষা) আইন ১৯৯৯",
  "evidence.breadcrumb": "বিধিসন্মত প্ৰমাণ সংগ্ৰহ",
  "evidence.allAuthorities": "সকলো নিয়ন্ত্ৰক কৰ্তৃপক্ষ",
  "evidence.allTypes": "সকলো বিধিসন্মত প্ৰকাৰ",
  "evidence.act": "আইন (Act)",
  "evidence.rule": "নিয়ম (Rule)",
  "evidence.gazetteNotification": "গেজেট অধিসূচনা",
  "evidence.pharmacopoeialStandard": "ফাৰ্মাকোপিয়াল মানদণ্ড",
  "evidence.treaty": "আন্তঃৰাষ্ট্ৰীয় চুক্তি",
  "evidence.verifiedAuthority": "পৰীক্ষিত নিয়ন্ত্ৰক কৰ্তৃপক্ষ",
  "evidence.cryptoHash": "ক্ৰিপ্ট'গ্ৰাফিক ফৰেনচিক হেচ",
  "evidence.plainSummary": "সহজ সাৰাংশ",
  "evidence.officialExcerpt": "চৰকাৰী বিধিসন্মত উদ্ধৃতি",
  "evidence.inspectCitation": "আইনী উদ্ধৃতি পৰীক্ষা কৰক",
  "evidence.noCorpusFound": "কোনো বিধিসন্মত প্ৰমাণ পোৱা নগ'ল",
  "evidence.noCorpusHint": "আপোনাৰ সন্ধান মাপকাঠী সলনি কৰক বা ফিল্টাৰ পৰিষ্কাৰ কৰক।",
  "caseDetail.loading": "বিধিসন্মত তথ্য লোড হৈ আছে...",
  "caseDetail.notFound": "গোচৰ পোৱা নগ'ল",
  "caseDetail.notFoundDesc": "অনুৰোধ কৰা গোচৰৰ তথ্য মজুত নাই বা আঁতৰাই দিয়া হৈছে।",
  "caseDetail.returnWorkspace": "গোচৰ কৰ্মক্ষেত্ৰলৈ উভতি যাওক",
  "caseDetail.juryDemo": "জুৰী ডেমো ম'ড",
  "caseDetail.simulateMissing": "অনুপস্থিত নথি অনুকৰণ কৰক",
  "caseDetail.exportDossier": "গোচৰ ডচিয়াৰ ৰপ্তানি কৰক",
  "caseDetail.timeMachine": "নিয়ন্ত্ৰক টাইম মেচিন",
  "caseDetail.editFormulation": "ফৰ্মুলেচন সম্পাদনা কৰক",
  "caseDetail.tabSummary": "সাৰাংশ আৰু ৰায়",
  "caseDetail.tabDna": "ফৰ্মুলেচন DNA",
  "caseDetail.tabClassifications": "প্ৰাৰ্থী শ্ৰেণীবিভাজন",
  "caseDetail.tabRegulations": "প্ৰযোজ্য নিয়মাৱলী",
  "caseDetail.tabIpPathways": "বৌদ্ধিক সম্পদ পথ",
  "caseDetail.tabAbs": "ABS অনুপালন",
  "caseDetail.tabPriorArt": "পূৰ্ব-কলা বিশ্লেষণ",
  "caseDetail.tabEvidenceGaps": "প্ৰমাণৰ ফাঁক",
  "caseDetail.tabEvidenceChain": "বিধিসন্মত প্ৰমাণ শৃংখল",
  "caseDetail.tabNextActions": "পৰৱৰ্তী প্ৰস্তাৱিত পদক্ষেপ",
  "caseDetail.classificationVerdict": "শ্ৰেণীবিভাজন ৰায়",
  "caseDetail.evidenceStrength": "প্ৰমাণৰ শক্তি",
  "caseDetail.governingAuthority": "নিয়ন্ত্ৰক কৰ্তৃপক্ষ",
  "caseDetail.statutoryBasis": "বিধিসন্মত ভিত্তি",
  "caseDetail.coreExcerpt": "মূল আইনী উদ্ধৃতি",
  "caseDetail.plainExplanation": "সহজ ব্যাখ্যা",
  "caseDetail.whyThis": "এই শ্ৰেণীবিভাজন কিয় প্ৰযোজ্য?",
  "auth.showPassword": "পাছৱৰ্ড দেখুৱাওক",
  "auth.hidePassword": "পাছৱৰ্ড লুকুৱাওক",
  "auth.charRequirement": "৮+ আখৰ",
  "auth.upperRequirement": "অন্ততঃ এটা ডাঙৰ ফলাৰ আখৰ (Uppercase)",
  "auth.numRequirement": "অন্ততঃ এটা সংখ্যা (Number)",
  "auth.demoAdmin": "ডেমো এডমিন পৰিচয়-পত্ৰ ব্যৱহাৰ কৰক",
  "intel.drawerTitle": "বিধিসন্মত প্ৰমাণ ড্ৰয়াৰ",
  "intel.authority": "নিয়ন্ত্ৰক কৰ্তৃপক্ষ",
  "intel.hierarchy": "আইনী অগ্ৰাধিকাৰ অনুক্ৰম",
  "intel.version": "চৰকাৰী সংস্কৰণ",
  "intel.excerpt": "আইনী উদ্ধৃতি",
  "intel.plainSummary": "সহজ আইনী সাৰাংশ",
  "intel.gazetteSource": "গেজেট উৎস",
  "intel.openExternal": "চৰকাৰী গেজেট খোলক",
  "intel.closeDrawer": "ড্ৰয়াৰ বন্ধ কৰক",
  "intel.gapsTitle": "প্ৰমাণৰ ফাঁক আৰু সমাধান কৌশল",
  "intel.resolutionStrategy": "সমাধান কৌশল",
  "intel.chainTitle": "বিধিসন্মত প্ৰমাণ শৃংখল",
  "intel.factTriggered": "সক্ৰিয় তথ্য",
  "intel.ruleApplied": "প্ৰয়োগ কৰা নিয়ম",
  "intel.matrixTitle": "বিধিসন্মত বুদ্ধিমত্তা ব'ৰ্ড",
  "intel.timeMachineTitle": "নিয়ন্ত্ৰক টাইম মেচিন",
  "intel.historicalAmendments": "ঐতিহাসিক সংশোধনী",
  "intel.uploadTitle": "সহায়ক নথি আপলোড কৰক",
  "intel.dragDrop": "নথি ইয়ালৈ টানি আনক বা ব্ৰাউজ কৰক",
  "intel.whyTitle": "আপুনি এইটো কিয় দেখিছে?",
  "intel.deterministicVerification": "নিৰ্ধাৰিত বিধিসন্মত পৰীক্ষণ",
  "search.breadcrumb": "সন্ধান",
  "search.heading": "বিধিসন্মত আৰু পেটেণ্ট সন্ধান",
  "search.btnSearch": "সন্ধান কৰক",
  "search.suggestedLabel": "প্ৰস্তাৱিত প্ৰশ্ন",
  "search.recentLabel": "শেহতীয়া সন্ধান",
  "search.clearLabel": "পৰিষ্কাৰ কৰক",
  "search.advancedFilters": "উন্নত ফিল্টাৰ",
  "search.hideAdvancedFilters": "উন্নত ফিল্টাৰ লুকুৱাওক",
  "search.allAuthorities": "সকলো কৰ্তৃপক্ষ",
  "search.allJurisdictions": "সকলো এক্তিয়াৰ",
  "assistant.breadcrumb": "AI সহায়ক",
  "assistant.bannerActive": "সক্ৰিয় গোচৰৰ প্ৰসংগত কাৰ্যৰত",
  "assistant.suggestedInquiries": "প্ৰস্তাৱিত সোধা-পোছা",
  "assistant.directAnswer": "পোনপটীয়া বিধিসন্মত উত্তৰ",
  "assistant.ruleConstraints": "প্ৰযোজ্য নিয়ম আৰু বাধ্যবাধকতা",
  "assistant.officialCitations": "চৰকাৰী আইনী উদ্ধৃতি",
  "assistant.evidenceGaps": "ধৰা পৰা প্ৰমাণৰ ফাঁক",
  "assistant.disclaimerFooter": "আইনী অস্বীকৃতি: এই ব্যৱস্থাই কেৱল তথ্যৰ উদ্দেশ্যে বিধিসন্মত নিৰ্দেশনা প্ৰদান কৰে।",
  "report.returnDossier": "গোচৰ ডচিয়াৰলৈ উভতি যাওক",
  "report.tableIngredients": "ফৰ্মুলেচন উপাদান আৰু বিৱৰণ",
  "report.name": "উপাদানৰ নাম",
  "report.botanical": "উদ্ভিদতাত্ত্বিক নাম",
  "report.sanskrit": "সংস্কৃত নাম",
  "report.part": "ব্যৱহৃত অংশ",
  "report.percentage": "অনুপাত / শতাংশ",
  "report.source": "প্ৰসংগ উৎস",
  "report.origin": "ভৌগোলিক উৎস",
  "cases.noMatch": "আপোনাৰ সন্ধানৰ সৈতে মিলা কোনো গোচৰ পোৱা নগ'ল।",
  "cases.jurisdictionIndia": "ভাৰত (ৰাষ্ট্ৰীয়)"
}

def run():
    print("Updating Bengali...")
    update_language_dict("bn", BN_MAP)
    print("Updating Gujarati...")
    update_language_dict("gu", GU_MAP)
    print("Updating Punjabi...")
    update_language_dict("pa", PA_MAP)
    print("Updating Odia...")
    update_language_dict("or", OR_MAP)
    print("Updating Assamese...")
    update_language_dict("as", AS_MAP)
    print("Pack 1 complete!")

if __name__ == "__main__":
    run()
