import os
import json

# Python script to build the complete, robust application-wide translation catalog for IP-SAKTI Sahayak

catalog_path = r"c:\Users\akash\OneDrive\Desktop\SAKTHI-SIH\frontend\src\i18n\translations\index.ts"

content = '''/**
 * IP-SAKTI Sahayak — Application-Wide Multilingual Translation Catalog
 * SIH26045 | Eighth Schedule of the Constitution of India + English
 * 
 * Rules:
 * 1. Statutory identifiers (Section 3(p), Rule 158B, Form III, Schedule T) are canonical Gazette identifiers.
 * 2. All user-facing UI text across Home, Navbar, Cases, Wizard, Dossier, Evidence, Assistant,
 *    Search, Explore, Auth, and Footer dynamically responds to selected language.
 * 3. Parameter interpolation {name}, {count}, {id} is fully supported.
 */

import { LanguageCode } from '../languages';

export type TranslationDict = Record<string, string>;

export const EN_TRANSLATIONS: TranslationDict = {
  // Navigation
  'nav.home': 'Home',
  'nav.explore': 'Explore',
  'nav.cases': 'My Cases',
  'nav.evidence': 'Statutory Corpus',
  'nav.assistant': 'AI Assistant',
  'nav.search': 'Search',
  'nav.login': 'Sign In',
  'nav.register': 'Create Account',
  'nav.logout': 'Sign Out',
  'nav.admin': 'Admin Panel',
  'nav.language': 'Language',
  'nav.searchPlaceholder': 'Search laws, patents, regulations, evidence...',
  'nav.startCase': 'Start Case',
  'nav.trySearching': 'Try searching for',
  'nav.pressEnter': 'Press Enter to search',
  'nav.searchScope': 'Search covers laws, patents, regulations, evidence',

  // Common UI
  'common.loading': 'Loading...',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.continue': 'Continue',
  'common.back': 'Back',
  'common.next': 'Next Step',
  'common.search': 'Search',
  'common.submit': 'Submit',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.view': 'View',
  'common.download': 'Download',
  'common.print': 'Print / Save as PDF',
  'common.returnHome': 'Return to Home',
  'common.optional': 'Optional',
  'common.required': 'Required',
  'common.status': 'Status',
  'common.jurisdiction': 'Jurisdiction',
  'common.all': 'All',
  'common.none': 'None',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.clear': 'Clear',

  // Actions
  'action.analyzeProduct': 'Analyze My Product',
  'action.protectInnovation': 'Protect My Innovation',
  'action.checkRegulations': 'Check Regulations',
  'action.searchEvidence': 'Search Evidence',
  'action.askAI': 'Ask IP-SAKTI AI',
  'action.generateReport': 'Generate Case Dossier',
  'action.timeMachine': 'Regulatory Time Machine',
  'action.newCase': 'New Case',
  'action.createAccount': 'Create Account',

  // Home Hero & Content
  'home.hero.badge': 'SIH26045 • Ministry of AYUSH & Patent Office Intelligence',
  'home.hero.title': 'Protect Innovation. Understand Regulation. Verify Evidence.',
  'home.hero.subtitle': 'Case-centered intellectual property and regulatory intelligence for Ayurvedic innovators, researchers, and MSMEs across Bharat.',
  'home.hero.cta_start': 'Start Formulation Assessment',
  'home.hero.cta_search': 'Search Statutory Corpus',
  'home.hero.or_search': 'or explore official gazette corpus',
  'home.features.rules_constrain': 'Rules Constrain',
  'home.features.rag_grounds': 'RAG Grounds',
  'home.features.ai_explains': 'AI Explains',
  'home.features.citations_prove': 'Citations Prove',
  'home.features.rules_desc': 'Deterministic logic prevents AI speculation',
  'home.features.rag_desc': 'Hybrid retrieval from official Gazette text',
  'home.features.ai_desc': 'Plain-language guidance in 22 languages',
  'home.features.citations_desc': 'Every claim linked to section & authority',
  
  'home.workflows.title': 'How Can We Assist You Today?',
  'home.workflows.subtitle': 'Select a guided pathway to evaluate your innovation, verify regulations, or ask questions.',
  'home.workflow.analyze.title': 'Analyze My Product',
  'home.workflow.analyze.desc': 'Enter a formulation or innovation and receive an evidence-grounded classification, applicable regulations, and IP overview.',
  'home.workflow.protect.title': 'Protect My Innovation',
  'home.workflow.protect.desc': 'Map your formula, brand, design, or traditional knowledge to the relevant IP pathways with evidence-backed guidance.',
  'home.workflow.regulations.title': 'Check Regulations',
  'home.workflow.regulations.desc': 'Understand which AYUSH, FSSAI, Drug & Cosmetics, or international regulatory frameworks apply to your product.',
  'home.workflow.evidence.title': 'Search Evidence',
  'home.workflow.evidence.desc': 'Explore a curated library of authoritative laws, regulations, treaties, notifications, and traditional knowledge sources.',
  'home.workflow.assistant.title': 'Ask IP-SAKTI AI',
  'home.workflow.assistant.desc': 'Ask complex questions about IP, regulations, or traditional knowledge. Every answer is grounded in authoritative evidence.',

  'home.howItWorks.title': 'How IP-SAKTI Sahayak Operates',
  'home.howItWorks.subtitle': 'A structured, 4-step pipeline that ensures every recommendation is verifiable and grounded in law.',
  'home.howItWorks.step1.title': 'Enter your formulation or query',
  'home.howItWorks.step1.desc': 'Describe your Ayurvedic product, innovation, or regulatory question through a guided workflow or intelligent search.',
  'home.howItWorks.step2.title': 'Rules classify. Evidence grounds.',
  'home.howItWorks.step2.desc': 'Deterministic rules identify the applicable classification. Hybrid retrieval pulls authoritative sources from the curated legal corpus.',
  'home.howItWorks.step3.title': 'AI explains with citations',
  'home.howItWorks.step3.desc': 'The AI interprets the evidence and explains what applies to you — with every claim linked to a specific law, section, and authority.',
  'home.howItWorks.step4.title': 'Understand. Verify. Act.',
  'home.howItWorks.step4.desc': 'Review the evidence chain, click through to source documents, and receive a clear action plan with next steps.',

  'home.trust.title': 'Rigorous Verification Built In',
  'home.trust.subtitle': 'Designed for compliance, legal safety, and evidence auditability.',
  'home.trust.point1': 'Every answer cites a specific law, section, and authority',
  'home.trust.point2': 'Sources are versioned — you see when a regulation changed',
  'home.trust.point3': 'AI abstains when evidence is insufficient',
  'home.trust.point4': 'Classified using deterministic rules, not LLM guesswork',
  'home.trust.point5': 'Prompt injection protection prevents document manipulation',
  'home.trust.point6': 'Documents are stored privately with signed-URL access only',

  'home.domains.title': '12 Covered Legal & Regulatory Domains',
  'home.domains.subtitle': 'Comprehensive coverage across Indian and international intellectual property and regulatory regimes.',
  'home.cta.title': 'Ready to Evaluate Your Formulation?',
  'home.cta.subtitle': 'Start a structured case assessment or search the authoritative statutory corpus right now.',
  'home.cta.button': 'Start Assessment Now',

  // Authentication
  'auth.welcomeBack': 'Welcome back',
  'auth.signInDesc': 'Sign in to your IP-SAKTI account',
  'auth.email': 'Email address',
  'auth.emailPlaceholder': 'you@example.com',
  'auth.password': 'Password',
  'auth.passwordPlaceholder': '••••••••',
  'auth.fullName': 'Full Name',
  'auth.namePlaceholder': 'Dr. Vaidya Sharma',
  'auth.preferredLanguage': 'Preferred Language',
  'auth.signIn': 'Sign In',
  'auth.signingIn': 'Signing in...',
  'auth.createAccount': 'Create Account',
  'auth.creatingAccount': 'Creating account...',
  'auth.createAccountTitle': 'Create Your Account',
  'auth.createAccountDesc': 'Join Ayurvedic innovators navigating IP & regulations across Bharat',
  'auth.haveAccount': 'Already have an account?',
  'auth.noAccount': "Don't have an account?",
  'auth.loginFailed': 'Login failed. Please check your credentials.',
  'auth.sessionExpired': 'Your session has expired. Please sign in again.',
  'auth.demoAccounts': 'Demo Accounts (1-Click Fill)',
  'auth.quickLogin': 'Click any demo account below to fill credentials:',
  'auth.demoNotice': 'Demo password: ',

  // Cases List
  'cases.title': 'Case Workspace',
  'cases.badge': 'SIH26045 Intelligence Unit',
  'cases.subtitle': 'Manage your Ayurvedic formulations, botanical products, and innovations. Each case synthesizes Formulation DNA, deterministic IP analysis, and regulatory evidence.',
  'cases.newCase': 'New Case',
  'cases.all': 'All Cases',
  'cases.active': 'Active',
  'cases.draft': 'Drafts',
  'cases.demo': 'Demo Cases',
  'cases.searchPlaceholder': 'Search cases by title, ingredient, or description...',
  'cases.emptyTitle': 'No formulation cases yet',
  'cases.emptyDesc': 'Create your first case to analyze product classification, map IP pathways, and assess regulatory compliance.',
  'cases.startFirst': 'Start First Assessment',
  'cases.openDossier': 'Open Dossier',
  'cases.delete': 'Delete Case',
  'cases.updated': 'Updated {time}',
  'cases.caseNumber': 'Case #{id}',
  'cases.ingredients': '{count} Ingredients',
  'cases.jurisdiction': 'Jurisdiction: {target}',
  'cases.loadingWorkspace': 'Loading workspace...',
  'cases.returnToWorkspace': 'Return to Cases Workspace',

  // Formulation Wizard
  'wizard.title': 'Formulation Case Intake',
  'wizard.badge': 'Guided Assessment',
  'wizard.subtitle': 'Complete this structured assessment to generate your Formulation DNA and statutory classification dossier.',
  'wizard.step1': '1. Category',
  'wizard.step2': '2. Ingredients',
  'wizard.step3': '3. Preparation',
  'wizard.step4': '4. Classical Basis',
  'wizard.step5': '5. Intended Use',
  'wizard.step6': '6. Commercial Scope',
  'wizard.step7': '7. Jurisdiction',
  'wizard.step8': '8. Documents',
  
  'wizard.step1.title': 'What are you working with?',
  'wizard.step1.subtitle': 'Define formulation type, classical basis, and biological resources.',
  'wizard.assetTitle': 'Formulation / Asset Title',
  'wizard.assetTitlePlaceholder': 'e.g., Medhya Rasayana Brain Wellness Capsule',
  'wizard.assetDesc': 'Brief Summary / Description',
  'wizard.assetDescPlaceholder': 'Describe the intended function, target consumers, or innovative aspects...',
  'wizard.productType': 'Product Category',
  'wizard.dosageForm': 'Dosage Form',
  'wizard.dosagePlaceholder': 'e.g., Tablet / Vati, Churna, Taila, Capsule, Kwatha',

  'wizard.step2.title': 'Ingredients & Biological Actives',
  'wizard.step2.subtitle': 'List botanical ingredients, their classical references, and sourcing origin.',
  'wizard.addIngredient': '+ Add Botanical Ingredient',
  'wizard.ingName': 'Herb / Common Name',
  'wizard.botanicalName': 'Botanical Taxon',
  'wizard.sanskritName': 'Sanskrit Name',
  'wizard.partUsed': 'Part Used',
  'wizard.percentage': 'Ratio (%)',
  'wizard.sourceType': 'Biological Sourcing (ABS)',
  'wizard.sourceCultivated': 'Cultivated (Farmed)',
  'wizard.sourceWild': 'Wild Harvested (Forest)',
  'wizard.sourceImported': 'Imported',
  'wizard.sourceUnknown': 'Unknown / Not Stated',
  'wizard.originState': 'State of Origin (India)',
  'wizard.remove': 'Remove',

  'wizard.step3.title': 'Preparation & Extraction Method',
  'wizard.step3.subtitle': 'Specify how the ingredients are processed, extracted, or standardized.',
  'wizard.prepMethod': 'Preparation Details',
  'wizard.prepPlaceholder': 'Describe the extraction solvent, temperature, purification (Shodhana), or bio-enhancement...',
  'wizard.prepType': 'Processing Paradigm',
  'wizard.prepClassical': 'Classical Shastra Method (Svarasa, Kwatha, Taila, Bhasma)',
  'wizard.prepExtract': 'Standardized Aqueous / Hydro-Alcoholic Extract',
  'wizard.prepNovel': 'Novel Fractionation / Nanoparticle / Bio-enhancement Process',

  'wizard.step4.title': 'Classical Reference & Ancient Samhitas',
  'wizard.step4.subtitle': 'Select classical treatises from the First Schedule of the Drugs & Cosmetics Act that reference this formula.',
  'wizard.isClassical': 'Is this an exact classical formula cited in ancient texts?',
  'wizard.classicalYes': 'Yes — Exact classical recipe and indication',
  'wizard.classicalNo': 'No — Proprietary modification or novel combination',

  'wizard.step5.title': 'Intended Use & Claims',
  'wizard.step5.subtitle': 'Specify the intended therapeutic, dietary, or cosmetic benefits.',
  'wizard.intendedUse': 'Intended Benefit / Indication',
  'wizard.intendedUsePlaceholder': 'e.g., Cognitive support, anti-inflammatory, digestive wellness...',
  'wizard.claimType': 'Claim Category',

  'wizard.step6.title': 'Commercialization Scope',
  'wizard.step6.subtitle': 'Define the commercial intent, manufacturing scale, and distribution.',
  'wizard.commercialScope': 'Commercial Intent',

  'wizard.step7.title': 'Target Jurisdiction',
  'wizard.step7.subtitle': 'Select the primary legal jurisdiction for IP protection and regulatory licensing.',
  'wizard.jurisdiction': 'Jurisdiction',

  'wizard.step8.title': 'Supporting Documents & Analysis',
  'wizard.step8.subtitle': 'Upload or declare laboratory certificates of analysis, texts, or stability data.',
  'wizard.supportingDocs': 'Declared Supporting Documents',
  'wizard.addDoc': '+ Add Document',
  'wizard.docPlaceholder': 'e.g., Heavy Metals Certificate of Analysis (CoA)',

  'wizard.next': 'Continue to Next Step',
  'wizard.back': 'Previous Step',
  'wizard.saveDraft': 'Save Case Draft',
  'wizard.generateDossier': 'Generate Intelligence Dossier',

  // Search
  'search.title': 'Statutory Search & Evidence Engine',
  'search.subtitle': 'Hybrid BM25 + Vector semantic retrieval grounded in official Indian statutory corpus.',
  'search.placeholder': 'Search formulations, patents, regulations, evidence, ABS, TKDL...',
  'search.suggested': 'Suggested:',
  'search.recent': 'Recent Searches:',
  'search.clear': 'Clear',
  'search.resultsFor': 'Results for "{query}"',
  'search.resultsFound': '{count} statutory records identified',
  'search.noResults': 'No statutory records found matching your query.',
  'search.refineSearch': 'Try searching with statutory terms like Section 3(p), Rule 158B, or botanical names.',
  'search.filters': 'Advanced Filters',
  'search.stream': 'Legal Stream:',
  'search.ipPathways': 'Recommended IP Pathways',
  'search.statutoryEvidence': 'Authoritative Statutory Evidence',
  'search.matchedCases': 'Matching User Cases',
  'search.filterAuthority': 'Authority:',
  'search.filterJurisdiction': 'Jurisdiction:',

  // Assistant
  'assistant.title': 'Statutory Intelligence Assistant',
  'assistant.badge': 'Grounded Decision Support',
  'assistant.subtitle': 'Structured guidance grounded in Indian statutory authorities. Evaluates patentability under Section 3(p), licensing under Rule 158B, and biodiversity compliance under BDA 2002.',
  'assistant.activeCase': 'Active Case Context:',
  'assistant.placeholder': 'Ask about patenting, Rule 158B licensing, or NBA Form III...',
  'assistant.send': 'Send',
  'assistant.thinking': 'Analyzing statutory corpus...',
  'assistant.suggestedQuestions': 'Suggested Questions:',
  'assistant.why': 'Statutory Rationale & Legal Grounding:',
  'assistant.practicalMeaning': 'What This Means Practically:',
  'assistant.missingInfo': 'Missing Information Required:',
  'assistant.nextActions': 'Recommended Action Steps:',
  'assistant.viewEvidence': 'View Statutory Source',
  'assistant.clearChat': 'Clear Chat',

  // Evidence & Corpus
  'evidence.title': 'Official Statutory Corpus',
  'evidence.badge': 'Curated Legal Library',
  'evidence.subtitle': 'Explore authentic Indian statutory authorities, Gazette notifications, AYUSH guidelines, and case law.',
  'evidence.searchPlaceholder': 'Search legal corpus by Act, Section, Rule, or authority...',
  'evidence.view_source': 'View Official Source',
  'evidence.what_source_establishes': 'What This Source Establishes',
  'evidence.what_source_does_not_establish': 'What This Source Does NOT Establish',
  'evidence.why_applies': 'Why This Applies To Your Case',
  'evidence.canonical_notice': 'Authoritative legal text in original Gazette form. Section numbers and Act identifiers are canonical.',
  'evidence.noEvidence': 'No statutory evidence matching current filters.',
  'evidence.filterAuthority': 'Authority:',
  'evidence.filterJurisdiction': 'Jurisdiction:',
  'evidence.filterStatus': 'Status:',
  'evidence.authority': 'Statutory Authority',
  'evidence.version': 'Version',
  'evidence.effectiveDate': 'Effective Date',
  'evidence.hierarchy': 'Legal Hierarchy',
  'evidence.close': 'Close Drawer',
  'evidence.totalRecords': '{count} statutory provisions in active corpus',

  // Dossier & Report
  'label.caseIntelligence': 'Case Intelligence Dossier',
  'label.dna': 'Formulation DNA',
  'label.classification': 'Statutory Classification',
  'label.regimes': 'Applicable Frameworks',
  'label.evidenceChain': 'Interactive Evidence Chain',
  'label.evidenceGaps': 'Evidence Gaps & Missing Data',
  'label.citations': 'Authoritative Citations',
  'label.nextActions': 'Actionable Next Steps',
  'label.whySeeingThis': 'Why am I seeing this?',
  'label.inspectStatute': 'Inspect Statute',

  'report.header': 'Government of India — SIH26045',
  'report.title': 'Case Intelligence & Statutory Assessment Report',
  'report.subtitle': 'Authoritative IP Pathway, Regulatory Framework, and ABS Traceability Dossier',
  'report.ref': 'Dossier Ref:',
  'report.date': 'Date Generated:',
  'report.corpusHash': 'Corpus Hash:',
  'report.returnToCase': 'Return to Case Dossier',
  'report.printSave': 'Print / Save as PDF',
  'report.sec1': '1. Formulation Asset Profile & DNA',
  'report.sec2': '2. Statutory Classification Determination',
  'report.sec3': '3. Signature Evidence Chain (Audit Trail)',
  'report.sec4': '4. Evidence Gaps & Missing Statutory Disclosures',
  'report.sec5': '5. Authoritative Statutory Citations',
  'report.sec6': '6. Prioritized Strategy & Action Plan',
  'report.sec7': '7. Institutional Notice & Mandatory Disclaimers',
  'report.botanicalActives': 'Botanical Actives & Biological Sourcing',
  'report.commonName': 'Common / Trade Name',
  'report.botanicalTaxon': 'Botanical Taxon',
  'report.partUsed': 'Part Used',
  'report.ratio': 'Ratio (%)',
  'report.bioOrigin': 'Biological Origin (ABS)',
  'report.statutoryRationale': 'Statutory Rationale:',

  // Explore
  'explore.title': 'Knowledge Base & Regulatory Explorer',
  'explore.badge': 'Statutory Knowledge Base',
  'explore.subtitle': 'Comprehensive guides to Indian statutory frameworks governing Ayurveda, IPR, AYUSH, and biodiversity.',
  'explore.filterAll': 'All Topics',
  'explore.filterIp': 'Intellectual Property',
  'explore.filterRegulation': 'AYUSH & FSSAI',
  'explore.filterAbs': 'Biodiversity (ABS)',
  'explore.filterTk': 'Traditional Knowledge',
  'explore.keyPoints': 'Key Statutory Points:',
  'explore.action': 'Start Assessment',

  // Footer
  'footer.tagline': 'Multilingual AI-Powered IP & Regulatory Intelligence Platform for Ayurveda.',
  'footer.platform': 'Platform',
  'footer.ipDomains': 'IP Domains',
  'footer.noticeTitle': 'Important Notice',
  'footer.noticeDesc': 'This platform provides information and decision support only. It does not constitute legal advice. Consult a qualified IP or legal professional for legal decisions.',
  'footer.copyright': '© 2026 IP-SAKTI Sahayak. SIH26045.',
  'footer.disclaimer': 'Decision-support intelligence only. Refer to cited official sources for authoritative legal text.',

  // Status & Strength
  'strength.high': 'HIGH EVIDENCE',
  'strength.moderate': 'MODERATE EVIDENCE',
  'strength.limited': 'LIMITED EVIDENCE',
  'strength.insufficient': 'INSUFFICIENT EVIDENCE',

  'sourceStatus.active': 'ACTIVE (In Force)',
  'sourceStatus.superseded': 'SUPERSEDED',
  'sourceStatus.amended': 'AMENDED',
  'sourceStatus.draft': 'DRAFT',

  'intents.patent': 'Patent',
  'intents.abs': 'Access & Benefit Sharing (ABS)',
  'intents.regulation': 'AYUSH Regulation',
  'intents.trademark': 'Trademark',
  'intents.gi': 'Geographical Indication',
  'intents.traditional_knowledge': 'Traditional Knowledge',
  'intents.case': 'Case Innovation',

  // Safe Abstention
  'abstain.title': 'Safe Abstention Safeguard Active',
  'abstain.desc': 'IP-SAKTI does not have sufficient authoritative evidence to evaluate this case reliably without making speculative assumptions.',
  'abstain.missing': 'Missing Parameters Checklist:',
  'abstain.remedy': 'Provide Missing Information',

  // Disclaimers
  'disclaimer.institutional': 'Decision-support intelligence only. Not legal advice.',
  'disclaimer.translation_convenience': 'Translated explanation for convenience. Refer to cited official sources for authoritative legal text.',
  'disclaimer.canonical_notice': 'Section numbers, Act identifiers, and official citations are canonical Gazette texts.',
};
'''
'''
# Build Hindi, Kannada, Tamil, Telugu, Malayalam, Bengali, Marathi, Gujarati, Punjabi, Odia, Assamese, Urdu, Sanskrit
# and mappings for the remaining scheduled languages
'''
'''
'''
