# -*- coding: utf-8 -*-
"""
IP-SAKTI Sahayak — Santali (sat) Native Ol Chiki Translation Dictionary Generator
Complete translation for all 609 keys in Ol Chiki script (ᱚᱞ ᱪᱤᱠᱤ).
"""

import json
import re
from updater import update_language_dict

# Load English keys to ensure exact 609 key parity
with open("frontend/src/i18n/translations/index.ts", "r", encoding="utf-8") as f:
    text = f.read()

en_match = re.search(r"export const EN_TRANSLATIONS: TranslationDict = (\{[\s\S]*?\n\});", text)
en_dict = json.loads(en_match.group(1))

# Ol Chiki translations for Santali
SAT_MAP = {
  # nav
  "nav.home": "ᱚᱲᱟᱜ",
  "nav.explore": "ᱯᱟᱸᱡᱟ",
  "nav.cases": "ᱤᱧᱟᱜ ᱠᱮᱥ ᱠᱚ",
  "nav.evidence": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱥᱟᱹᱵᱩᱛ",
  "nav.assistant": "AI ᱜᱚᱲᱚᱭᱤᱡ",
  "nav.search": "ᱥᱮᱸᱫᱽᱨᱟ",
  "nav.login": "ᱵᱚᱞᱚᱱ",
  "nav.register": "ᱮᱠᱟᱣᱩᱱᱴ ᱵᱮᱱᱟᱣ",
  "nav.logout": "ᱚᱰᱚᱠᱚᱜ",
  "nav.admin": "ᱥᱟᱥᱚᱱ ᱯᱮᱱᱮᱞ",
  "nav.language": "ᱯᱟᱹᱨᱥᱤ",
  "nav.searchPlaceholder": "ᱟᱹᱭᱤᱱ, ᱯᱮᱴᱮᱱᱴ, ᱱᱤᱭᱚᱢ, ᱥᱟᱹᱵᱩᱛ ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ...",
  "nav.startCase": "ᱠᱮᱥ ᱮᱛᱚᱦᱚᱵ",
  "nav.trySearching": "ᱱᱚᱣᱟ ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ",
  "nav.pressEnter": "ᱥᱮᱸᱫᱽᱨᱟ ᱞᱟᱹᱜᱤᱫ Enter ᱚᱛᱟᱭ ᱢᱮ",
  "nav.searchScope": "ᱥᱮᱸᱫᱽᱨᱟ ᱨᱮ ᱟᱹᱭᱤᱱ, ᱯᱮᱴᱮᱱᱴ, ᱱᱤᱭᱚᱢ ᱟᱨ ᱥᱟᱹᱵᱩᱛ ᱥᱮᱞᱮᱫ ᱢᱮᱱᱟᱜ-ᱟ",
  "nav.signIn": "ᱵᱚᱞᱚᱱ",
  "nav.signOut": "ᱚᱰᱚᱠᱚᱜ",
  "nav.myCases": "ᱤᱧᱟᱜ ᱠᱮᱥ ᱠᱚ",

  # common
  "common.loading": "ᱞᱟ独ᱰᱚᱜ ᱠᱟᱱᱟ...",
  "common.save": "ᱥᱟᱧᱪᱟᱣ",
  "common.cancel": "ᱵᱟᱹᱛᱤᱞ",
  "common.close": "ᱵᱚᱸᱫᱚ",
  "common.continue": "ᱞᱟᱦᱟᱭ ᱢᱮ",
  "common.back": "ᱛᱟᱭᱚᱢ",
  "common.next": "ᱞᱟᱦᱟ ᱛᱷᱟᱠ",
  "common.search": "ᱥᱮᱸᱫᱽᱨᱟ",
  "common.submit": "ᱮᱢ / ᱫᱟᱠᱷᱤᱞ",
  "common.delete": "ᱜᱮᱫ ᱜᱤᱰᱤ",
  "common.edit": "ᱥᱟᱯᱲᱟᱣ",
  "common.view": "ᱧᱮᱞ",
  "common.download": "ᱰᱟᱣᱩᱱᱞᱳᱰ",
  "common.print": "ᱯᱨᱤᱱᱴ / PDF ᱥᱟᱧᱪᱟᱣ",
  "common.returnHome": "ᱚᱲᱟᱜ ᱛᱮ ᱨᱩᱣᱟᱹᱲ",
  "common.optional": "ᱟᱯᱱᱟᱨᱟᱜ ᱠᱩᱥᱤ",
  "common.required": "ᱞᱟᱹᱠᱛᱤᱭᱟᱱ",
  "common.status": "ᱦᱟᱞᱚᱛ",
  "common.jurisdiction": "ᱟᱹᱭᱤᱱ ᱮᱞᱟᱠᱟ",
  "common.all": "ᱡᱚᱛᱚ",
  "common.none": "ᱪᱮᱫᱦᱚᱸ ᱵᱟᱝ",
  "common.yes": "ᱦᱮᱸ",
  "common.no": "ᱵᱟᱝ",
  "common.clear": "ᱯᱷᱟᱨᱪᱟ",
  "common.error": "ᱢᱤᱫ ᱵᱷᱩᱞ ᱦᱩᱭᱮᱱᱟ",
  "common.success": "ᱠᱟᱹᱢᱤ ᱱᱟᱯᱟᱭᱛᱮ ᱯᱩᱨᱟᱹᱣ ᱮᱱᱟ",

  # action
  "action.analyzeProduct": "ᱤᱧᱟᱜ ᱯᱚᱨᱰᱚᱠᱴ ᱯᱟᱨᱠᱷᱟᱣ ᱢᱮ",
  "action.protectInnovation": "ᱤᱧᱟᱜ ᱱᱟᱣᱟ ᱵᱮᱱᱟᱣ ᱨᱩᱠᱷᱤᱭᱟᱹᱭ ᱢᱮ",
  "action.exploreStatutes": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱯᱟᱸᱡᱟᱭ ᱢᱮ",
  "action.searchPriorArt": "ᱯᱟᱹᱦᱤᱞ ᱵᱮᱱᱟᱣ ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ",
  "action.viewFullDossier": "ᱯᱩᱨᱟᱹ ᱰᱚᱥᱤᱭᱟᱨ ᱧᱮᱞ ᱢᱮ",
  "action.generateReport": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱨᱤᱯᱳᱨᱴ ᱵᱮᱱᱟᱣ ᱢᱮ",
  "action.launchTimeMachine": "ᱱᱤᱭᱚᱢ ᱚᱠᱛᱚ ᱢᱮᱥᱤᱱ ᱪᱟᱹᱞᱩᱭ ᱢᱮ",
  "action.exportPdf": "PDF ᱰᱟᱣᱩᱱᱞᱳᱰ",
  "action.retry": "ᱟᱨᱦᱚᱸ ᱪᱮᱥᱴᱟᱭ ᱢᱮ",
  "action.getStarted": "ᱮᱛᱚᱦᱚᱵ ᱢᱮ",
  "action.learnMore": "ᱵᱟᱹᱲᱛᱤ ᱵᱟᱰᱟᱭ ᱢᱮ",
  "action.viewDetails": "ᱵᱤᱵᱚᱨᱚᱬ ᱧᱮᱞ ᱢᱮ",

  # home
  "home.hero.title": "ᱥᱤᱧᱚᱛᱤᱭᱟᱹ ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱟᱨ IP ᱜᱚᱲᱚ",
  "home.hero.subtitle": "ᱟᱹᱭᱩᱨᱵᱮᱫᱽ, ᱦᱟᱨᱵᱟᱞ, ᱡᱤᱵᱽ ᱵᱷᱮᱜᱟᱨ ᱟᱨ ᱥᱮᱫᱟᱭ ᱜᱮᱭᱟᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱞᱟᱹᱜᱤᱫ ᱥᱚᱨᱠᱟᱨᱤ ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱯᱞᱮᱴᱯᱷᱚᱨᱢ",
  "home.hero.badge": "SIH26045 | ᱥᱚᱨᱠᱟᱨᱤ ᱜᱮᱡᱮᱴ ᱯᱩᱨᱟᱹᱣ",
  "home.hero.cta": "ᱱᱟᱣᱟ ᱠᱮᱥ ᱮᱛᱚᱦᱚᱵ ᱢᱮ",
  "home.hero.secondary": "ᱟᱹᱭᱤᱱ ᱠᱚ ᱯᱟᱸᱡᱟᱭ ᱢᱮ",
  "home.hero.multilingual": "ᱥᱟᱸᱜᱮ ᱯᱟᱹᱨᱥᱤ ᱜᱚᱲᱚ",
  "home.hero.multilingual_title": "᱒᱒ ᱜᱚᱴᱟᱝ ᱥᱤᱧᱚᱛᱤᱭᱟᱹ ᱯᱟᱹᱨᱥᱤ + ᱤᱝᱞᱤᱥ ᱛᱮ ᱢᱮᱱᱟᱜ-ᱟ",
  "home.hero.multilingual_desc": "ᱯᱩᱨᱟᱹ ᱯᱞᱮᱴᱯᱷᱚᱨᱢ — AI ᱛᱮᱞᱟ, ᱥᱟᱹᱵᱩᱛ ᱠᱟᱨᱰ ᱟᱨ ᱛᱷᱚᱠ ᱵᱮᱠᱷᱟ ᱥᱟᱶ — ᱥᱤᱧᱚᱛ ᱨᱮᱱᱟᱜ ᱡᱚᱛᱚ ᱒᱒ ᱥᱚᱨᱠᱟᱨᱤ ᱯᱟᱹᱨᱥᱤ ᱟᱨ ᱤᱝᱞᱤᱥ ᱛᱮ ᱧᱟᱢᱚᱜ-ᱟ। ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱟᱹᱲᱟᱹ ᱠᱚ ᱟᱠᱚᱣᱟᱜ ᱢᱩᱲ ᱨᱩᱯ ᱛᱮ ᱫᱚᱦᱚ ᱟᱠᱟᱱᱟ।",
  "home.workflow.mostUsed": "ᱡᱚᱛᱚ ᱠᱷᱚᱱ ᱵᱟᱹᱲᱛᱤ ᱵᱮᱵᱷᱟᱨᱚᱜ",
  "home.features.versioning_updates": "ᱵᱷᱟᱨᱥᱚᱱ ᱱᱟᱣᱟᱭ",
  "home.features.abstention_protects": "ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱟᱦᱟ ᱨᱩᱠᱷᱤᱭᱟᱹ",
  "home.workflows.heading": "ᱟᱢ ᱪᱮᱫ ᱠᱟᱹᱢᱤ ᱥᱟᱱᱟᱢ ᱠᱟᱱᱟ?",
  "home.intake.ayurvedicFormulation": "ᱟᱹᱭᱩᱨᱵᱮᱫᱤᱠ ᱨᱟᱱ ᱢᱮᱥᱟ (Formulation)",
  "home.intake.ayurvedicFormulationHint": "ᱥᱮᱫᱟᱭ ᱥᱟᱥᱛᱨᱚ ᱥᱮ ᱱᱤᱡᱮᱨᱟᱜ ᱦᱟᱨᱵᱟᱞ ᱢᱮᱥᱟ",
  "home.intake.herbalProduct": "ᱦᱟᱨᱵᱟᱞ ᱯᱚᱨᱰᱚᱠᱴ",
  "home.intake.herbalProductHint": "ᱨᱟᱥᱟ, ᱡᱚᱢ-ᱧᱩ ᱥᱟᱯᱞᱤᱢᱮᱱᱴ, ᱨᱟᱱ ᱫᱟᱨᱮ",
  "home.intake.plantResource": "ᱫᱟᱨᱮ-ᱱᱟᱹᱲᱤ / ᱡᱤᱵᱽ ᱥᱟᱫᱷᱚᱱ",
  "home.intake.plantResourceHint": "ᱨᱟᱱ ᱫᱟᱨᱮ, ABS/NBA ᱞᱟᱦᱟ-ᱟᱭᱫᱟᱹᱨᱤ",
  "home.intake.traditionalKnowledge": "ᱥᱮᱫᱟᱭ ᱜᱮᱭᱟᱱ",
  "home.intake.traditionalKnowledgeHint": "ᱥᱟᱥᱛᱨᱚ ᱯᱩᱛᱷᱤ, TKDL ᱞᱟᱦᱟ-ᱠᱟᱹᱢᱤ ᱧᱮᱞ",
  "home.intake.novelProcess": "ᱱᱟᱣᱟ ᱠᱟᱹᱢᱤᱦᱚᱨᱟ",
  "home.intake.novelProcessHint": "ᱨᱟᱥᱟ ᱚᱰᱚᱠ, ᱛᱷᱤᱨ ᱫᱚᱦᱚ ᱟᱨ Section 3(p) ᱯᱟᱨᱠᱷᱟᱣ",
  "home.intake.brandIdentity": "ᱵᱨᱟᱱᱰ ᱩᱯᱨᱩᱢ (ᱴᱨᱮᱰᱢᱟᱨᱠ)",
  "home.intake.brandIdentityHint": "ᱵᱮᱯᱟᱨ ᱪᱤᱱᱦᱟᱹ, ᱛᱷᱚᱠ ᱕/᱓/᱓᱐/᱔᱔",
  "home.intake.geographicalIdentity": "ᱚᱛᱱᱚᱜ ᱩᱯᱨᱩᱢ (GI)",
  "home.intake.geographicalIdentityHint": "GI ᱪᱤᱱᱦᱟᱹ, ᱢᱩᱲ ᱥᱟᱨᱴᱤᱯᱷᱤᱠᱮᱴ",
  "home.intake.regulatoryQuestion": "ᱱᱤᱭᱚᱢ ᱠᱩᱠᱞᱤ",
  "home.intake.regulatoryQuestionHint": "FSSAI, AYUSH, Rule 158B, Schedule T",
  "home.demo.badge": "ᱡᱤᱣᱮᱫ ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱫᱮᱠᱷᱟᱣ",
  "home.demo.simulation": "ᱱᱤᱭᱚᱢ ᱫᱮᱠᱷᱟᱣ",
  "home.demo.title": "ᱠᱟᱸᱪᱟ ᱵᱷᱟᱵᱽᱱᱟ ᱠᱷᱚᱱ ᱟᱹᱭᱤᱱ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱫᱷᱟᱹᱵᱤᱡ",
  "home.demo.story": "ᱚᱥᱣᱚᱜᱚᱱᱫᱷᱟ-ᱵᱨᱟᱦᱢᱤ ᱥᱤᱨᱚᱯ ᱪᱮᱫᱞᱮᱠᱟ ᱯᱟᱨᱠᱷᱟᱣᱚᱜ-ᱟ ᱧᱮᱞ ᱢᱮ: Section 3(p) ᱞᱟᱦᱟ-ᱠᱟᱹᱢᱤ, Rule 158B ᱢᱟᱱᱟᱣ, FSSAI ᱟᱹᱭᱩᱥ ᱟᱦᱟᱨ ᱛᱷᱚᱠ ᱟᱨ ABS ᱞᱟᱦᱟ-ᱟᱭᱫᱟᱹᱨᱤ।",
  "home.demo.notice": "ᱡᱚᱛᱚ ᱥᱚᱞᱦᱟ ᱥᱚᱡᱷᱮ ᱥᱚᱨᱠᱟᱨᱤ ᱜᱮᱡᱮᱴ ᱟᱹᱭᱤᱱ ᱥᱟᱶ ᱡᱚᱲᱟᱣ ᱢᱮᱱᱟᱜ-ᱟ।",
  "home.demo.startCase": "ᱱᱚᱣᱟ ᱠᱮᱥ ᱮᱛᱚᱦᱚᱵ ᱢᱮ",
  "home.demo.inspectDossier": "ᱱᱚᱢᱩᱱᱟ ᱰᱚᱥᱤᱭᱟᱨ ᱧᱮᱞ ᱢᱮ",
  "home.demo.step1.label": "ᱢᱮᱥᱟ ᱡᱤᱱᱤᱥ ᱯᱟᱨᱠᱷᱟᱣ",
  "home.demo.step1.sub": "ᱚᱥᱣᱚᱜᱚᱱᱫᱷᱟ + ᱵᱨᱟᱦᱢᱤ ᱥᱤᱨᱚᱯ",
  "home.demo.step2.label": "TKDL ᱥᱮᱸᱫᱽᱨᱟ",
  "home.demo.step2.sub": "ᱵᱷᱟᱵᱽᱯᱨᱚᱠᱟᱥ ᱟᱨ ᱪᱚᱨᱚᱠ ᱥᱚᱝᱦᱤᱛᱟ ᱠᱟᱛᱷᱟ",
  "home.demo.step3.label": "Section 3(p) ᱵᱚᱛᱚᱨ",
  "home.demo.step3.sub": "ᱥᱮᱫᱟᱭ ᱜᱮᱭᱟᱱ ᱯᱮᱴᱮᱱᱴ ᱵᱟᱫᱽ",
  "home.demo.step4.label": "Rule 158B ᱯᱟᱨᱠᱷᱟᱣ",
  "home.demo.step4.sub": "ᱥᱟᱥᱛᱨᱚ ᱯᱩᱛᱷᱤ ᱥᱟᱹᱵᱩᱛ ᱦᱚᱨ",
  "home.demo.step5.label": "FSSAI ᱵᱤᱨᱩᱫᱷ AYUSH",
  "home.demo.step5.sub": "ᱟᱹᱭᱩᱥ ᱟᱦᱟᱨ ᱛᱷᱚᱠ ᱵᱟᱪᱷᱟᱣ",
  "home.demo.step6.label": "NBA / ABS ᱟᱭᱫᱟᱹᱨᱤ",
  "home.demo.step6.sub": "Form III ᱡᱤᱵᱽ ᱥᱟᱫᱷᱚᱱ ᱟᱨᱫᱟᱥ",
  "home.demo.step7.label": "ᱠᱟᱹᱢᱤ ᱦᱚᱨᱟ",
  "home.demo.step7.sub": "ᱨᱩᱠᱷᱤᱭᱟᱹ ᱦᱚᱨ ᱟᱨ ᱫᱟᱠᱷᱤᱞ",
  "home.evidence.sample": "ᱱᱚᱢᱩᱱᱟ ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱥᱟᱹᱵᱩᱛ",
  "home.evidence.actIndia": "ᱯᱮᱴᱮᱱᱴ ᱟᱹᱭᱤᱱ ᱑᱙᱗᱐ (ᱥᱤᱧᱚᱛ)",
  "home.evidence.strength": "ᱟᱹᱭᱤᱱ ᱥᱟᱹᱵᱩᱛ ᱫᱟᱲᱮ",
  "home.evidence.high": "ᱪᱮᱛᱟᱱ",
  "home.evidence.whyRelevant": "ᱱᱚᱣᱟ ᱪᱮᱫᱟᱜ ᱞᱟᱜᱟᱣᱜ-ᱟ: ᱡᱩᱫᱤ ᱡᱟᱦᱟᱸ ᱫᱟᱵᱤ ᱥᱮᱫᱟᱭ ᱜᱮᱭᱟᱱ ᱨᱮᱱᱟᱜ ᱥᱩᱢᱩᱝ ᱡᱚᱢᱟᱣ ᱠᱟᱱᱟ, ᱛᱚᱵᱮ Section 3(p) ᱛᱟᱹᱨᱤ ᱨᱮ ᱯᱮᱴᱮᱱᱴ ᱵᱟᱛᱤᱞᱚᱜ-ᱟ।",
  "home.evidence.viewSource": "ᱥᱚᱨᱠᱟᱨᱤ ᱯᱷᱮᱰᱟᱛ ᱧᱮᱞ ᱢᱮ",
  "home.evidence.disclaimer": "ᱱᱚᱣᱟ ᱦᱟᱹᱴᱤᱧ ᱰᱤᱡᱤᱴᱟᱞ ᱥᱩᱦᱤ ᱥᱤᱧᱚᱛ ᱜᱮᱡᱮᱴ ᱠᱷᱚᱱ ᱯᱟᱨᱠᱷᱟᱣ ᱟᱠᱟᱱᱟ।",
  "home.multilingual.badge": "᱒᱒ ᱯᱟᱹᱨᱥᱤ + ᱤᱝᱞᱤᱥ",
  "home.multilingual.fullSupport": "ᱥᱤᱧᱚᱛ ᱨᱮᱱᱟᱜ ᱡᱚᱛᱚ ᱒᱒ ᱥᱚᱨᱠᱟᱨᱤ ᱯᱟᱹᱨᱥᱤ ᱛᱮ ᱯᱩᱨᱟᱹ ᱜᱚᱲᱚ",
  "home.multilingual.more": "ᱟᱨᱦᱚᱸ ᱯᱟᱹᱨᱥᱤ",
  "home.multilingual.all22": "ᱥᱤᱧᱚᱛ ᱥᱚᱝᱵᱤᱫᱷᱟᱱ ᱨᱮᱱᱟᱜ ᱘ ᱟᱱᱟᱜ ᱛᱷᱚᱠ ᱨᱮᱱᱟᱜ ᱡᱚᱛᱚ ᱒᱒ ᱯᱟᱹᱨᱥᱤ ᱛᱮ ᱧᱟᱢᱚᱜ-ᱟ",
  "home.domain.patent": "ᱯᱮᱴᱮᱱᱴ (ᱠᱚᱞᱚᱢ 3(p) ᱟᱨ 3(e))",
  "home.domain.patentDesc": "ᱥᱮᱫᱟᱭ ᱜᱮᱭᱟᱱ ᱵᱟᱫᱽ, ᱱᱟᱣᱟᱱ ᱟᱨ ᱞᱟᱦᱟ-ᱠᱟᱹᱢᱤ ᱯᱟᱨᱠᱷᱟᱣ।",
  "home.domain.trademark": "ᱴᱨᱮᱰᱢᱟᱨᱠ",
  "home.domain.trademarkDesc": "ᱟᱹᱭᱩᱨᱵᱮᱫᱤᱠ ᱵᱨᱟᱱᱰ, ᱪᱤᱱᱦᱟᱹ, ᱛᱷᱚᱠ ᱕ ᱟᱨ ᱨᱟᱱ ᱛᱷᱚᱠ ᱨᱮᱡᱤᱥᱴᱨᱮᱥᱚᱱ।",
  "home.domain.gi": "ᱚᱛᱱᱚᱜ ᱪᱤᱱᱦᱟᱹ (GI)",
  "home.domain.giDesc": "ᱴᱚᱴᱷᱟᱠᱤᱭᱟᱹ ᱫᱟᱨᱮ-ᱱᱟᱹᱲᱤ ᱟᱨ ᱥᱮᱫᱟᱭ ᱨᱟᱱ ᱦᱚᱨᱟ ᱨᱩᱠᱷᱤᱭᱟᱹ।",
  "home.domain.plantVariety": "ᱫᱟᱨᱮ-ᱱᱟᱹᱲᱤ ᱡᱟᱹᱛ ᱨᱩᱠᱷᱤᱭᱟᱹ (PPV&FR)",
  "home.domain.plantVarietyDesc": "ᱪᱟᱹᱥᱤ ᱟᱹᱭᱫᱟᱹᱨ ᱟᱨ ᱨᱟᱱ ᱫᱟᱨᱮ ᱡᱟᱹᱛ ᱨᱮᱡᱤᱥᱴᱨᱮᱥᱚᱱ।",
  "home.domain.copyright": "ᱠᱚᱯᱤᱨᱟᱭᱤᱴ",
  "home.domain.copyrightDesc": "ᱠᱷᱚᱸᱫᱽᱨᱚᱸᱫᱽ ᱠᱟᱜᱚᱡᱽ, ᱥᱟᱥᱛᱨᱚ ᱵᱮᱠᱷᱟ ᱟᱨ ᱰᱤᱡᱤᱴᱟᱞ ᱰᱮᱴᱟᱵᱮᱥ ᱨᱩᱠᱷᱤᱭᱟᱹ।",
  "home.domain.industrialDesign": "ᱠᱟᱹᱨᱜᱟᱲ ᱰᱤᱡᱟᱭᱤᱱ",
  "home.domain.industrialDesignDesc": "ᱨᱟᱱ ᱮᱢᱚᱜ ᱥᱟᱫᱷᱚᱱ, ᱵᱚᱛᱚᱞ ᱟᱨ ᱯᱮᱠᱮᱡᱤᱝ ᱰᱤᱡᱟᱭᱤᱱ।",
  "home.domain.tk": "ᱥᱮᱫᱟᱭ ᱜᱮᱭᱟᱱ (TKDL)",
  "home.domain.tkDesc": "ᱟᱹᱭᱩᱨᱵᱮᱫᱽ, ᱥᱤᱫᱽᱫᱷᱚ ᱟᱨ ᱭᱩᱱᱟᱱᱤ ᱜᱮᱭᱟᱱ ᱨᱮᱱᱟᱜ ᱡᱮᱜᱮᱛ ᱨᱩᱠᱷᱤᱭᱟᱹ।",
  "home.domain.abs": "ᱡᱤᱵᱽ ᱵᱷᱮᱜᱟᱨ ᱟᱨ ABS",
  "home.domain.absDesc": "ᱡᱟᱹᱛᱤᱭᱟᱹᱨᱤ ᱡᱤᱵᱽ ᱵᱷᱮᱜᱟᱨ ᱟᱹᱢᱟᱹᱞᱤ (NBA) Form III ᱟᱭᱫᱟᱹᱨᱤ।",
  "home.domain.ayush": "ᱟᱹᱭᱩᱥ (AYUSH) ᱱᱤᱭᱚᱢ ᱠᱚ",
  "home.domain.ayushDesc": "ᱨᱟᱱ ᱟᱨ ᱨᱩᱯ-ᱨᱚᱝ ᱟᱹᱭᱤᱱ, ᱥᱟᱥᱛᱨᱚ ᱯᱩᱛᱷᱤ ᱯᱷᱮᱰᱟᱛ।",
  "home.domain.fssaiDesc": "ᱟᱹᱭᱩᱥ ᱟᱦᱟᱨ ᱱᱤᱭᱚᱢ, ᱡᱚᱢ-ᱧᱩ ᱥᱟᱯᱞᱤᱢᱮᱱᱴ ᱟᱨ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱢᱟᱱ।",
  "home.domain.drugsCosmetics": "ᱨᱟᱱ ᱟᱨ ᱨᱩᱯ-ᱨᱚᱝ ᱟᱹᱭᱤᱱ",
  "home.domain.drugsCosmeticsDesc": "Rule 158B ᱥᱟᱹᱵᱩᱛ ᱟᱨ Schedule T GMP ᱢᱟᱱ।",
  "home.domain.internationalIp": "ᱡᱮᱜᱮᱛᱟᱹᱨᱤ ᱵᱩᱫᱷᱤ ᱥᱚᱢᱯᱚᱛᱤ",
  "home.domain.internationalIpDesc": "PCT, ᱯᱮᱨᱤᱥ ᱪᱩᱠᱛᱤ ᱟᱨ ᱱᱟᱜᱳᱭᱟ ᱯᱨᱳᱴᱳᱠᱳᱞ।",
  "home.pipeline.question": "ᱠᱩᱠᱞᱤ",
  "home.pipeline.classify": "ᱛᱷᱚᱠ ᱦᱟᱹᱴᱤᱧ",
  "home.pipeline.evidence": "ᱥᱟᱹᱵᱩᱛ",
  "home.pipeline.intelligence": "ᱵᱩᱫᱷᱤ",
  "home.pipeline.action": "ᱠᱟᱹᱢᱤ",
  "home.domain.plantVarietyProtection": "ᱫᱟᱨᱮ ᱡᱟᱹᱛ ᱨᱩᱠᱷᱤᱭᱟᱹ",

  # nav quick
  "nav.quick.herbalPatent": "ᱦᱟᱨᱵᱟᱞ ᱯᱮᱴᱮᱱᱴ ᱡᱚᱜᱽᱭᱚᱛᱟ",
  "nav.quick.fssaiRules": "FSSAI ᱟᱹᱭᱩᱥ ᱟᱦᱟᱨ ᱱᱤᱭᱚᱢ",
  "nav.quick.giProtection": "ᱨᱟᱱ ᱫᱟᱨᱮ ᱨᱮᱱᱟᱜ GI ᱨᱩᱠᱷᱤᱭᱟᱹ",
  "nav.quick.absNagoya": "ABS ᱱᱟᱜᱳᱭᱟ ᱯᱨᱳᱴᱳᱠᱳᱞ ᱢᱟᱱᱟᱣ",
  "nav.quick.section3p": "Section 3(p) ᱥᱮᱫᱟᱭ ᱜᱮᱭᱟᱱ ᱵᱟᱫᱽ",
  "nav.quick.tkNeem": "ᱱᱤᱢ ᱟᱨ ᱥᱟᱥᱟᱝ ᱯᱮᱴᱮᱱᱴ ᱵᱤᱨᱩᱫᱷ",

  # wizard
  "wizard.stepProgress": "ᱛᱷᱟᱠ ᱞᱟᱦᱟᱱᱛᱤ",
  "wizard.stepPrev": "ᱛᱟᱭᱚᱢ ᱛᱷᱟᱠ",
  "wizard.stepNext": "ᱞᱟᱦᱟ ᱛᱷᱟᱠ",
  "wizard.stepSaveRoadmap": "ᱠᱮᱥ ᱥᱟᱧᱪᱟᱣ ᱟᱨ ᱠᱟᱹᱢᱤ ᱦᱚᱨᱟ ᱵᱮᱱᱟᱣ ᱢᱮ",
  "wizard.backToCases": "ᱤᱧᱟᱜ ᱠᱮᱥ ᱠᱚᱛᱮ ᱨᱩᱣᱟᱹᱲ ᱢᱮ",
  "wizard.guidedSetup": "ᱟᱹᱭᱩᱨ ᱟᱠᱟᱱ IP ᱟᱨ ᱱᱤᱭᱚᱢ ᱥᱟᱯᱲᱟᱣ",
  "wizard.gap.title": "ᱥᱟᱹᱵᱩᱛ ᱨᱮ ᱯᱷᱟᱸᱠ ᱧᱟᱢ ᱟᱠᱟᱱᱟ",
  "wizard.gap.desc": "ᱱᱚᱣᱟ ᱨᱟᱱ ᱢᱮᱥᱟ ᱞᱟᱹᱜᱤᱫ ᱥᱟᱥᱛᱨᱚ ᱯᱩᱛᱷᱤ ᱨᱮᱱᱟᱜ ᱞᱟᱹᱠᱛᱤ ᱦᱩᱭ ᱫᱟᱲᱮᱭᱟᱜ-ᱟ।",
  "wizard.gap.fix": "ᱥᱟᱹᱵᱩᱛ ᱯᱷᱟᱸᱠ ᱪᱮᱫᱞᱮᱠᱟ ᱯᱩᱨᱟᱹᱣ ᱦᱩᱭᱩᱜ-ᱟ ᱧᱮᱞ ᱢᱮ",
  "wizard.validation.titleRequired": "ᱨᱟᱱ ᱢᱮᱥᱟ ᱧᱩᱛᱩᱢ ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱠᱟᱱᱟ",
  "wizard.dnaReady": "ᱨᱟᱱ ᱢᱮᱥᱟ DNA ᱥᱟᱯᱲᱟᱣ ᱟᱠᱟᱱᱟ",
  "wizard.ingIndex": "ᱡᱤᱱᱤᱥ",
  "wizard.assetNature": "ᱥᱚᱢᱯᱚᱛᱤ ᱨᱮᱱᱟᱜ ᱨᱩᱯ",
  "wizard.selectTreatises": "ᱢᱟᱱᱟᱣ ᱟᱠᱟᱱ ᱥᱟᱥᱛᱨᱚ ᱯᱩᱛᱷᱤ ᱵᱟᱪᱷᱟᱣ ᱢᱮ",
  "wizard.classicalCitation": "ᱥᱟᱥᱛᱨᱚ ᱯᱷᱮᱰᱟᱛ / ᱥᱞᱳᱠ ᱩᱫᱷᱨᱚᱬ",
  "wizard.indicationsLabel": "ᱨᱟᱱ ᱞᱟᱹᱜᱤᱫ ᱪᱤᱱᱦᱟᱹ / ᱨᱳᱜᱽ ᱟᱹᱭᱫᱟᱹᱨ",
  "wizard.indicationsPlaceholder": "ᱡᱮᱞᱮᱠᱟ: ᱠᱷᱚᱜ, ᱥᱟᱸᱦᱮᱫ, ᱨᱩᱣᱟᱹ, ᱨᱚᱥᱟᱭᱚᱱ...",
  "wizard.prepNarrative": "ᱵᱮᱱᱟᱣ ᱦᱚᱨᱟ ᱵᱤᱵᱚᱨᱚᱬ",
  "wizard.prepNarrativePlaceholder": "ᱥᱳᱫᱷᱚᱱ, ᱵᱷᱟᱵᱽᱱᱟ ᱥᱮ ᱨᱟᱥᱟ ᱚᱰᱚᱠ ᱦᱚᱨᱟ ᱵᱤᱥᱛᱟᱨ ᱛᱮ ᱞᱟᱹᱭ ᱢᱮ...",
  "wizard.commercialPathway": "ᱵᱮᱯᱟᱨ ᱦᱚᱨ",
  "wizard.targetJurisdictionTitle": "ᱠᱟᱹᱢᱤ ᱮᱞᱟᱠᱟ ᱴᱟᱨᱜᱮᱴ",
  "wizard.supportingDocsTitle": "ᱜᱚᱲᱚ ᱠᱟᱜᱚᱡᱽ ᱟᱨ ᱥᱟᱹᱵᱩᱛ",
  "wizard.docAddPlaceholder": "ᱠᱟᱜᱚᱡᱽ ᱧᱩᱛᱩᱢ ᱥᱮ ᱯᱷᱮᱰᱟᱛ ᱚᱞ ᱢᱮ...",
  "wizard.addDocBtn": "ᱠᱟᱜᱚᱡᱽ ᱥᱮᱞᱮᱫ ᱢᱮ",
  "wizard.plantPart": "ᱵᱮᱵᱷᱟᱨ ᱟᱠᱟᱱ ᱫᱟᱨᱮ ᱦᱟᱹᱴᱤᱧ",
  "wizard.sourcingType": "ᱯᱷᱮᱰᱟᱛ ᱞᱮᱠᱟᱱ",
  "wizard.cat.ayurvedic": "ᱟᱹᱭᱩᱨᱵᱮᱫᱤᱠ ᱨᱟᱱ ᱢᱮᱥᱟ",
  "wizard.cat.ayurvedicDesc": "ᱥᱮᱫᱟᱭ ᱥᱮ ᱱᱤᱡᱮᱨᱟᱜ ᱨᱟᱱ",
  "wizard.cat.herbal": "ᱦᱟᱨᱵᱟᱞ ᱯᱚᱨᱰᱚᱠᱴ",
  "wizard.cat.herbalDesc": "ᱫᱟᱨᱮ ᱨᱟᱥᱟ ᱥᱮ ᱥᱟᱯᱞᱤᱢᱮᱱᱴ",
  "wizard.cat.traditional": "ᱥᱮᱫᱟᱭ ᱜᱮᱭᱟᱱ",
  "wizard.cat.traditionalDesc": "ᱦᱟᱯᱲᱟᱢ ᱠᱚᱣᱟᱜ ᱦᱚᱨᱟ ᱥᱮ ᱯᱩᱛᱷᱤ",
  "wizard.cat.plant": "ᱡᱤᱵᱽ ᱥᱟᱫᱷᱚᱱ",
  "wizard.cat.plantDesc": "ᱫᱟᱨᱮ-ᱱᱟᱹᱲᱤ ᱥᱮ ᱡᱤᱵᱽ ᱡᱤᱱᱤᱥ",
  "wizard.cat.process": "ᱱᱟᱣᱟ ᱦᱚᱨᱟ",
  "wizard.cat.processDesc": "ᱨᱟᱥᱟ ᱚᱰᱚᱠ ᱥᱮ ᱵᱮᱱᱟᱣ ᱦᱚᱨᱟ",
  "wizard.cat.brand": "ᱵᱨᱟᱱᱰ ᱥᱮ ᱯᱚᱨᱰᱚᱠᱴ ᱧᱩᱛᱩᱢ",
  "wizard.cat.brandDesc": "ᱴᱨᱮᱰᱢᱟᱨᱠ ᱨᱩᱠᱷᱤᱭᱟᱹ",
  "wizard.prep.classical": "ᱥᱟᱥᱛᱨᱚ ᱦᱚᱨᱟ",
  "wizard.prep.classicalDesc": "ᱥᱚᱨᱠᱟᱨᱤ ᱯᱩᱛᱷᱤ ᱞᱮᱠᱟᱛᱮ ᱵᱮᱱᱟᱣ",
  "wizard.prep.extract": "ᱢᱟᱱ ᱮᱢ ᱨᱟᱥᱟ",
  "wizard.prep.extractDesc": "ᱫᱟᱜ ᱥᱮ ᱮᱞᱠᱳᱦᱚᱞ ᱛᱮ ᱚᱰᱚᱠ ᱨᱟᱥᱟ",
  "wizard.prep.novel": "ᱱᱟᱣᱟ ᱴᱮᱠᱱᱳᱞᱳᱡᱤ",
  "wizard.prep.novelDesc": "ᱱᱮᱱᱳ-ᱠᱟᱹᱴᱤᱡ ᱥᱮ ᱩᱥᱩᱞ ᱦᱟᱹᱴᱤᱧ ᱦᱚᱨᱟ",
  "wizard.commercial.domestic": "ᱥᱤᱧᱚᱛ ᱵᱷᱤᱛᱨᱤ ᱵᱟᱡᱟᱨ",
  "wizard.commercial.domesticDesc": "ᱥᱤᱧᱚᱛ ᱨᱮ ᱵᱮᱱᱟᱣ ᱟᱨ ᱟᱹᱠᱷᱨᱤᱧ",
  "wizard.commercial.export": "ᱡᱮᱜᱮᱛ ᱵᱟᱡᱟᱨ ᱠᱩᱞ",
  "wizard.commercial.exportDesc": "ᱡᱮᱜᱮᱛ ᱵᱟᱡᱟᱨ ᱨᱮ ᱟᱹᱠᱷᱨᱤᱧ",
  "wizard.commercial.rd": "ᱠᱷᱚᱸᱫᱽᱨᱚᱸᱫᱽ ᱟᱨ ᱞᱟᱦᱟᱱᱛᱤ",
  "wizard.commercial.rdDesc": "ᱞᱟᱦᱟ-ᱠᱞᱤᱱᱤᱠᱟᱞ ᱥᱮ ᱠᱞᱤᱱᱤᱠᱟᱞ ᱵᱤᱰᱟᱹᱣ",
  "wizard.commercial.licensing": "ᱴᱮᱠᱱᱳᱞᱳᱡᱤ ᱞᱟᱭᱥᱮᱱᱥ",
  "wizard.commercial.licensingDesc": "ᱮᱴᱟᱜ ᱦᱚᱲ ᱞᱟᱭᱥᱮᱱᱥ ᱮᱢ",
  "wizard.jur.india": "ᱥᱤᱧᱚᱛ",
  "wizard.jur.indiaDesc": "ᱥᱤᱧᱚᱛ ᱯᱮᱴᱮᱱᱴ ᱟᱨ ᱱᱤᱭᱚᱢ ᱟᱹᱭᱤᱱ",
  "wizard.jur.us": "ᱭᱩᱱᱟᱭᱴᱮᱰ ᱥᱴᱮᱴᱥ",
  "wizard.jur.usDesc": "US FDA ᱟᱨ USPTO ᱱᱤᱭᱚᱢ",
  "wizard.jur.eu": "ᱤᱣᱨᱳᱯᱤᱭᱟᱱ ᱤᱣᱱᱤᱭᱚᱱ",
  "wizard.jur.euDesc": "EMA ᱟᱨ EPO ᱱᱤᱭᱚᱢ",
  "wizard.jur.intl": "ᱡᱮᱜᱮᱛᱟᱹᱨᱤ (PCT)",
  "wizard.jur.intlDesc": "ᱡᱮᱜᱮᱛ ᱯᱮᱴᱮᱱᱴ ᱜᱚᱲᱚ ᱪᱩᱠᱛᱤ",
  "wizard.claim.therapeutic": "ᱨᱟᱱ ᱫᱟᱵᱤ",
  "wizard.claim.nutritional": "ᱡᱚᱢ-ᱧᱩ ᱥᱮ ᱟᱦᱟᱨ ᱫᱟᱵᱤ",
  "wizard.claim.cosmetic": "ᱨᱩᱯ-ᱨᱚᱝ ᱪᱮᱦᱨᱟ ᱫᱟᱵᱤ",
  "wizard.claim.wellness": "ᱥᱟᱫᱷᱟᱨᱚᱱ ᱦᱚᱲᱢᱚ ᱟᱨ ᱥᱩᱠᱷ",

  # explore
  "explore.breadcrumb": "ᱱᱤᱭᱚᱢ ᱦᱚᱨᱟ ᱯᱟᱸᱡᱟᱭ ᱢᱮ",
  "explore.searchPlaceholder": "ᱨᱟᱱ, ᱯᱮᱴᱮᱱᱴ, Section 3(p), Rule 158B, ABS, TKDL ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ...",
  "explore.allFrameworks": "ᱡᱚᱛᱚ ᱱᱤᱭᱚᱢ ᱦᱚᱨᱟ",
  "explore.ipPatents": "IP ᱟᱨ ᱯᱮᱴᱮᱱᱴ ᱠᱚ",
  "explore.ayushFssai": "ᱟᱹᱭᱩᱥ ᱟᱨ FSSAI",
  "explore.bioAbs": "ᱡᱤᱵᱽ ᱵᱷᱮᱜᱟᱨ ᱟᱨ ABS",
  "explore.tkTkdl": "ᱥᱮᱫᱟᱭ ᱜᱮᱭᱟᱱ ᱟᱨ TKDL",
  "explore.statutoryHighlights": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱢᱩᱬ ᱠᱟᱛᱷᱟ",
  "explore.noItems": "ᱵᱟᱪᱷᱟᱣ ᱟᱠᱟᱱ ᱛᱷᱚᱠ ᱨᱮ ᱪᱮᱫ ᱱᱤᱭᱚᱢ ᱦᱚᱨᱟ ᱵᱟᱝ ᱧᱟᱢ ᱞᱮᱱᱟ।",
  "explore.actSec3p": "ᱯᱮᱴᱮᱱᱴ ᱟᱹᱭᱤᱱ ᱑᱙᱗᱐ — ᱠᱚᱞᱚᱢ 3(p) ᱟᱨ 3(e)",
  "explore.actRule158b": "ᱨᱟᱱ ᱟᱨ ᱨᱩᱯ-ᱨᱚᱝ ᱱᱤᱭᱚᱢ ᱑᱙᱔᱕ — ᱱᱤᱭᱚᱢ 158B",
  "explore.actAbs": "ᱡᱤᱵᱽ ᱵᱷᱮᱜᱟᱨ ᱟᱹᱭᱤᱱ ᱒᱐᱐᱒ — Form III ABS",
  "explore.actAahar": "ᱟᱹᱭᱩᱥ ᱟᱦᱟᱨ ᱱᱤᱭᱚᱢ ᱒᱐᱒᱒ — FSSAI ᱦᱚᱨᱟ",
  "explore.actTkdl": "ᱥᱮᱫᱟᱭ ᱜᱮᱭᱟᱱ ᱰᱤᱡᱤᱴᱟᱞ ᱯᱩᱛᱷᱤᱥᱟᱲᱟ (TKDL)",
  "explore.actGi": "ᱚᱛᱱᱚᱜ ᱪᱤᱱᱦᱟᱹ (ᱨᱮᱡᱤᱥᱴᱨᱮᱥᱚᱱ ᱟᱨ ᱨᱩᱠᱷᱤᱭᱟᱹ) ᱟᱹᱭᱤᱱ ᱑᱙᱙᱙",

  # evidence
  "evidence.breadcrumb": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱥᱟᱹᱵᱩᱛ ᱡᱟᱣᱨᱟ",
  "evidence.allAuthorities": "ᱡᱚᱛᱚ ᱱᱤᱭᱚᱢ ᱟᱹᱢᱟᱹᱞᱤ",
  "evidence.allTypes": "ᱡᱚᱛᱚ ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱞᱮᱠᱟᱱ",
  "evidence.act": "ᱟᱹᱭᱤᱱ (Act)",
  "evidence.rule": "ᱱᱤᱭᱚᱢ (Rule)",
  "evidence.gazetteNotification": "ᱜᱮᱡᱮᱴ ᱞᱟᱹᱭ-ᱥᱚᱫᱚᱨ",
  "evidence.pharmacopoeialStandard": "ᱯᱷᱟᱨᱢᱟᱠᱳᱯᱤᱭᱟᱞ ᱢᱟᱱ",
  "evidence.treaty": "ᱡᱮᱜᱮᱛ ᱪᱩᱠᱛᱤ",
  "evidence.verifiedAuthority": "ᱯᱟᱨᱠᱷᱟᱣ ᱟᱠᱟᱱ ᱟᱹᱢᱟᱹᱞᱤ",
  "evidence.cryptoHash": "ᱠᱨᱤᱯᱴᱳᱜᱽᱨᱟᱯᱷᱤᱠ ᱯᱷᱳᱨᱮᱱᱥᱤᱠ ᱦᱮᱥ",
  "evidence.plainSummary": "ᱥᱟᱫᱷᱟᱨᱚᱱ ᱥᱟᱨᱟᱝᱥᱚ",
  "evidence.officialExcerpt": "ᱥᱚᱨᱠᱟᱨᱤ ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱠᱟᱛᱷᱟ",
  "evidence.inspectCitation": "ᱟᱹᱭᱤᱱ ᱯᱷᱮᱰᱟᱛ ᱯᱟᱨᱠᱷᱟᱣ ᱢᱮ",
  "evidence.noCorpusFound": "ᱪᱮᱫ ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱥᱟᱹᱵᱩᱛ ᱵᱟᱝ ᱧᱟᱢ ᱞᱮᱱᱟ",
  "evidence.noCorpusHint": "ᱟᱢᱟᱜ ᱥᱮᱸᱫᱽᱨᱟ ᱠᱟᱛᱷᱟ ᱵᱚᱫᱚᱞ ᱢᱮ ᱥᱮ ᱯᱷᱤᱞᱴᱟᱨ ᱯᱷᱟᱨᱪᱟᱭ ᱢᱮ।",

  # caseDetail
  "caseDetail.loading": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱠᱟᱛᱷᱟ ᱞᱟ独ᱰᱚᱜ ᱠᱟᱱᱟ...",
  "caseDetail.notFound": "ᱠᱮᱥ ᱵᱟᱝ ᱧᱟᱢ ᱞᱮᱱᱟ",
  "caseDetail.notFoundDesc": "ᱠᱷᱚᱡᱽ ᱟᱠᱟᱱ ᱠᱮᱥ ᱵᱟᱹᱱᱩᱜ-ᱟ ᱥᱮ ᱚᱪᱚᱜ ᱟᱠᱟᱱᱟ।",
  "caseDetail.returnWorkspace": "ᱠᱮᱥ ᱠᱟᱹᱢᱤ ᱴᱷᱟᱶ ᱛᱮ ᱨᱩᱣᱟᱹᱲ ᱢᱮ",
  "caseDetail.juryDemo": "ᱡᱩᱨᱤ ᱰᱮᱢᱳ ᱢᱳᱰ",
  "caseDetail.simulateMissing": "ᱵᱟᱹᱱᱩᱜ ᱠᱟᱜᱚᱡᱽ ᱫᱮᱠᱷᱟᱣ ᱢᱮ",
  "caseDetail.exportDossier": "ᱠᱮᱥ ᱰᱚᱥᱤᱭᱟᱨ ᱵᱟᱦᱨᱮ ᱠᱩᱞ",
  "caseDetail.timeMachine": "ᱱᱤᱭᱚᱢ ᱚᱠᱛᱚ ᱢᱮᱥᱤᱱ",
  "caseDetail.editFormulation": "ᱨᱟᱱ ᱢᱮᱥᱟ ᱥᱟᱯᱲᱟᱣ ᱢᱮ",
  "caseDetail.tabSummary": "ᱥᱟᱨᱟᱝᱥᱚ ᱟᱨ ᱯᱷᱟᱹᱭᱥᱟᱞᱟ",
  "caseDetail.tabDna": "ᱨᱟᱱ ᱢᱮᱥᱟ DNA",
  "caseDetail.tabClassifications": "ᱵᱟᱪᱷᱟᱣ ᱛᱷᱚᱠ ᱠᱚ",
  "caseDetail.tabRegulations": "ᱞᱟᱜᱟᱣᱜ ᱱᱤᱭᱚᱢ ᱠᱚ",
  "caseDetail.tabIpPathways": "IP ᱦᱚᱨ ᱠᱚ",
  "caseDetail.tabAbs": "ABS ᱢᱟᱱᱟᱣ",
  "caseDetail.tabPriorArt": "ᱞᱟᱦᱟ-ᱠᱟᱹᱢᱤ ᱯᱟᱨᱠᱷᱟᱣ",
  "caseDetail.tabEvidenceGaps": "ᱥᱟᱹᱵᱩᱛ ᱯᱷᱟᱸᱠ ᱠᱚ",
  "caseDetail.tabEvidenceChain": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱥᱟᱹᱵᱩᱛ ᱥᱤᱠᱲᱤ",
  "caseDetail.tabNextActions": "ᱞᱟᱦᱟ ᱞᱟᱹᱠᱛᱤᱭᱟᱱ ᱠᱟᱹᱢᱤ",
  "caseDetail.classificationVerdict": "ᱛᱷᱚᱠ ᱯᱷᱟᱹᱭᱥᱟᱞᱟ",
  "caseDetail.evidenceStrength": "ᱥᱟᱹᱵᱩᱛ ᱫᱟᱲᱮ",
  "caseDetail.governingAuthority": "ᱪᱟᱪᱞᱟᱣ ᱟᱹᱢᱟᱹᱞᱤ",
  "caseDetail.statutoryBasis": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱵᱩᱱᱤᱭᱟᱹᱫᱽ",
  "caseDetail.coreExcerpt": "ᱢᱩᱬ ᱟᱹᱭᱤᱱ ᱠᱟᱛᱷᱟ",
  "caseDetail.plainExplanation": "ᱥᱟᱫᱷᱟᱨᱚᱱ ᱵᱮᱠᱷᱟ",
  "caseDetail.whyThis": "ᱱᱚᱣᱟ ᱛᱷᱚᱠ ᱪᱮᱫᱟᱜ ᱞᱟᱜᱟᱣᱜ-ᱟ?",

  # auth
  "auth.showPassword": "ᱯᱟᱥᱣᱟᱨᱰ ᱩᱫᱩᱜ ᱢᱮ",
  "auth.hidePassword": "ᱯᱟᱥᱣᱟᱨᱰ ᱩᱠᱩᱭ ᱢᱮ",
  "auth.charRequirement": "᱘+ ᱟᱠᱷᱚᱨ",
  "auth.upperRequirement": "ᱠᱚᱢ ᱠᱷᱚᱱ ᱠᱚᱢ ᱢᱤᱫ ᱢᱟᱨᱟᱝ ᱟᱠᱷᱚᱨ (Uppercase)",
  "auth.numRequirement": "ᱠᱚᱢ ᱠᱷᱚᱱ ᱠᱚᱢ ᱢᱤᱫ ᱮᱞ (Number)",
  "auth.demoAdmin": "ᱰᱮᱢᱳ ᱮᱰᱢᱤᱱ ᱩᱯᱨᱩᱢ ᱵᱮᱵᱷᱟᱨ ᱢᱮ",
  "auth.welcomeBack": "ᱥᱟᱹᱜᱩᱱ ᱫᱟᱨᱟᱢ",
  "auth.signInDesc": "ᱟᱢᱟᱜ IP-SAKTI ᱮᱠᱟᱣᱩᱱᱴ ᱨᱮ ᱵᱚᱞᱚᱱ ᱢᱮ",
  "auth.email": "ᱤᱢᱮᱞ ᱴᱷᱤᱠᱬᱟ",
  "auth.password": "ᱯᱟᱥᱣᱟᱨᱰ",
  "auth.signIn": "ᱵᱚᱞᱚᱱ",
  "auth.noAccount": "ᱮᱠᱟᱣᱩᱱᱴ ᱵᱟᱹᱱᱩᱜ ᱛᱟᱢᱟ?",
  "auth.sessionExpired": "ᱥᱮᱥᱚᱱ ᱢᱩᱪᱟᱹᱫ ᱮᱱᱟ",
  "auth.createAccountTitle": "ᱮᱠᱟᱣᱩᱱᱴ ᱵᱮᱱᱟᱣ ᱢᱮ",
  "auth.createAccountDesc": "ᱯᱟᱹᱛᱭᱟᱹᱣ ᱥᱟᱶ ᱟᱹᱭᱤᱱ ᱟᱨ IP ᱯᱟᱸᱡᱟ ᱮᱛᱚᱦᱚᱵ ᱢᱮ",
  "auth.fullName": "ᱯᱩᱨᱟᱹ ᱧᱩᱛᱩᱢ",
  "auth.createAccount": "ᱮᱠᱟᱣᱩᱱᱴ ᱵᱮᱱᱟᱣ",
  "auth.haveAccount": "ᱮᱠᱟᱣᱩᱱᱴ ᱢᱮᱱᱟᱜ ᱛᱟᱢᱟ?",
  "auth.preferredLanguage": "ᱠᱩᱥᱤᱭᱟᱱ ᱯᱟᱹᱨᱥᱤ",

  # intel
  "intel.drawerTitle": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱥᱟᱹᱵᱩᱛ ᱰᱨᱚᱣᱟᱨ",
  "intel.authority": "ᱪᱟᱪᱞᱟᱣ ᱟᱹᱢᱟᱹᱞᱤ",
  "intel.hierarchy": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱞᱟᱦᱟ-ᱛᱟᱭᱚᱢ ᱛᱷᱚᱠ",
  "intel.version": "ᱥᱚᱨᱠᱟᱨᱤ ᱵᱷᱟᱨᱥᱚᱱ",
  "intel.excerpt": "ᱟᱹᱭᱤᱱ ᱠᱟᱛᱷᱟ",
  "intel.plainSummary": "ᱥᱟᱫᱷᱟᱨᱚᱱ ᱟᱹᱭᱤᱱ ᱥᱟᱨᱟᱝᱥᱚ",
  "intel.gazetteSource": "ᱜᱮᱡᱮᱴ ᱯᱷᱮᱰᱟᱛ",
  "intel.openExternal": "ᱥᱚᱨᱠᱟᱨᱤ ᱜᱮᱡᱮᱴ ᱡᱷᱤᱡ ᱢᱮ",
  "intel.closeDrawer": "ᱰᱨᱚᱣᱟᱨ ᱵᱚᱸᱫᱚᱭ ᱢᱮ",
  "intel.gapsTitle": "ᱥᱟᱹᱵᱩᱛ ᱯᱷᱟᱸᱠ ᱟᱨ ᱥᱚᱞᱦᱮ ᱦᱚᱨ",
  "intel.resolutionStrategy": "ᱥᱚᱞᱦᱮ ᱦᱚᱨ",
  "intel.chainTitle": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱥᱟᱹᱵᱩᱛ ᱥᱤᱠᱲᱤ",
  "intel.factTriggered": "ᱪᱟᱹᱞᱩ ᱟᱠᱟᱱ ᱠᱟᱛᱷᱟ",
  "intel.ruleApplied": "ᱞᱟᱜᱟᱣ ᱟᱠᱟᱱ ᱱᱤᱭᱚᱢ",
  "intel.matrixTitle": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱵᱩᱫᱷᱤ ᱵᱳᱨᱰ",
  "intel.timeMachineTitle": "ᱱᱤᱭᱚᱢ ᱚᱠᱛᱚ ᱢᱮᱥᱤᱱ",
  "intel.historicalAmendments": "ᱱᱟᱜᱟᱢᱤᱭᱟᱹ ᱵᱚᱫᱚᱞ ᱠᱚ",
  "intel.uploadTitle": "ᱜᱚᱲᱚ ᱠᱟᱜᱚᱡᱽ ᱠᱚ ᱟᱯᱞᱳᱰ ᱢᱮ",
  "intel.dragDrop": "ᱠᱟᱜᱚᱡᱽ ᱱᱚᱸᱰᱮ ᱚᱨ ᱟᱹᱜᱩᱭ ᱢᱮ ᱥᱮ ᱵᱨᱟᱣᱩᱡᱽ ᱢᱮ",
  "intel.whyTitle": "ᱟᱢ ᱱᱚᱣᱟ ᱪᱮᱫᱟᱜ ᱮᱢ ᱧᱮᱞᱮᱫ-ᱟ?",
  "intel.deterministicVerification": "ᱴᱷᱟᱹᱣᱠᱟᱹ ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱯᱟᱨᱠᱷᱟᱣ",

  # search
  "search.breadcrumb": "ᱥᱮᱸᱫᱽᱨᱟ",
  "search.heading": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱟᱨ ᱯᱮᱴᱮᱱᱴ ᱥᱮᱸᱫᱽᱨᱟ",
  "search.placeholder": "ᱟᱹᱭᱤᱱ, ᱯᱮᱴᱮᱱᱴ, Section 3(p), Rule 158B ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ...",
  "search.btnSearch": "ᱥᱮᱸᱫᱽᱨᱟ",
  "search.suggestedLabel": "ᱥᱚᱞᱦᱟ ᱠᱩᱠᱞᱤ ᱠᱚ",
  "search.recentLabel": "ᱱᱤᱛᱚᱜᱟᱜ ᱥᱮᱸᱫᱽᱨᱟ",
  "search.clearLabel": "ᱯᱷᱟᱨᱪᱟ",
  "search.advancedFilters": "ᱩᱥᱩᱞ ᱯᱷᱤᱞᱴᱟᱨ",
  "search.hideAdvancedFilters": "ᱩᱥᱩᱞ ᱯᱷᱤᱞᱴᱟᱨ ᱩᱠᱩᱭ ᱢᱮ",
  "search.allAuthorities": "ᱡᱚᱛᱚ ᱟᱹᱢᱟᱹᱞᱤ",
  "search.allJurisdictions": "ᱡᱚᱛᱚ ᱮᱞᱟᱠᱟ",
  "search.ipPathways": "IP ᱦᱚᱨ ᱠᱚ",
  "search.statutoryEvidence": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱥᱟᱹᱵᱩᱛ",

  # assistant
  "assistant.breadcrumb": "AI ᱜᱚᱲᱚᱭᱤᱡ",
  "assistant.title": "AI ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱜᱚᱲᱚᱭᱤᱡ",
  "assistant.badge": "ᱥᱚᱨᱠᱟᱨᱤ ᱟᱹᱭᱤᱱ ᱜᱚᱲᱚ",
  "assistant.subtitle": "ᱟᱹᱭᱤᱱ, ᱯᱮᱴᱮᱱᱴ ᱟᱨ ᱱᱤᱭᱚᱢ ᱵᱟᱵᱚᱛ ᱠᱩᱞᱤ ᱢᱮ",
  "assistant.activeCase": "ᱪᱟᱹᱞᱩ ᱠᱮᱥ",
  "assistant.bannerActive": "ᱪᱟᱹᱞᱩ ᱠᱮᱥ ᱥᱟᱶ ᱠᱟᱹᱢᱤ ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟ",
  "assistant.suggestedInquiries": "ᱥᱚᱞᱦᱟ ᱠᱩᱠᱞᱤ ᱠᱚ",
  "assistant.directAnswer": "ᱥᱚᱡᱷᱮ ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱛᱮᱞᱟ",
  "assistant.ruleConstraints": "ᱞᱟᱜᱟᱣᱜ ᱱᱤᱭᱚᱢ ᱟᱨ ᱥᱤᱢᱟᱹ",
  "assistant.officialCitations": "ᱥᱚᱨᱠᱟᱨᱤ ᱟᱹᱭᱤᱱ ᱯᱷᱮᱰᱟᱛ",
  "assistant.evidenceGaps": "ᱧᱟᱢ ᱟᱠᱟᱱ ᱥᱟᱹᱵᱩᱛ ᱯᱷᱟᱸᱠ",
  "assistant.practicalMeaning": "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱢᱮᱱᱮᱛ",
  "assistant.nextActions": "ᱞᱟᱦᱟ ᱠᱟᱹᱢᱤ ᱠᱚ",
  "assistant.placeholder": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱠᱩᱠᱞᱤ ᱚᱞ ᱢᱮ...",
  "assistant.send": "ᱠᱩᱞ ᱢᱮ",
  "assistant.disclaimerFooter": "ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱪᱮᱛᱟᱣᱱᱤ: ᱱᱚᱣᱟ ᱦᱚᱨᱟ ᱫᱚ ᱥᱩᱢᱩᱝ ᱵᱟᱰᱟᱭ ᱞᱟᱹᱜᱤᱫ ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱫᱤᱥᱟᱹ ᱮᱢᱚᱜ-ᱟ।",

  # report
  "report.header": "ᱥᱚᱨᱠᱟᱨᱤ ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱰᱚᱥᱤᱭᱟᱨ",
  "report.title": "IP ᱟᱨ ᱱᱤᱭᱚᱢ ᱯᱟᱨᱠᱷᱟᱣ ᱨᱤᱯᱳᱨᱴ",
  "report.subtitle": "ᱥᱚᱨᱠᱟᱨᱤ ᱜᱮᱡᱮᱴ ᱟᱨ ᱯᱮᱴᱮᱱᱴ ᱟᱹᱭᱤᱱ ᱛᱟᱹᱨᱤ ᱨᱮ",
  "report.ref": "ᱠᱮᱥ ᱮᱞ",
  "report.date": "ᱢᱟᱹᱦᱤᱛ",
  "report.corpusHash": "ᱠᱳᱨᱯᱚᱥ ᱦᱮᱥ",
  "report.returnDossier": "ᱠᱮᱥ ᱰᱚᱥᱤᱭᱟᱨ ᱛᱮ ᱨᱩᱣᱟᱹᱲ ᱢᱮ",
  "report.printSave": "ᱯᱨᱤᱱᱴ / PDF ᱥᱟᱧᱪᱟᱣ",
  "report.sec1": "᱑. ᱨᱟᱱ ᱢᱮᱥᱟ ᱩᱯᱨᱩᱢ",
  "report.sec2": "᱒. ᱛᱷᱚᱠ ᱯᱷᱟᱹᱭᱥᱟᱞᱟ",
  "report.sec3": "᱓. ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱞᱟᱜᱟᱣ",
  "report.sec4": "᱔. IP ᱦᱚᱨ ᱯᱟᱨᱠᱷᱟᱣ",
  "report.sec5": "᱕. ᱡᱤᱵᱽ ᱵᱷᱮᱜᱟᱨ ᱟᱨ ABS ᱢᱟᱱᱟᱣ",
  "report.sec6": "᱖. ᱞᱟᱦᱟ-ᱠᱟᱹᱢᱤ ᱟᱨ TKDL ᱥᱮᱸᱫᱽᱨᱟ",
  "report.sec7": "᱗. ᱥᱚᱞᱦᱟ ᱠᱟᱹᱢᱤ ᱦᱚᱨᱟ",
  "report.tableIngredients": "ᱨᱟᱱ ᱢᱮᱥᱟ ᱡᱤᱱᱤᱥ ᱟᱨ ᱵᱤᱵᱚᱨᱚᱬ",
  "report.name": "ᱡᱤᱱᱤᱥ ᱧᱩᱛᱩᱢ",
  "report.botanical": "ᱫᱟᱨᱮ ᱥᱟᱬᱮᱥ ᱧᱩᱛᱩᱢ",
  "report.sanskrit": "ᱥᱚᱝᱥᱠᱨᱤᱛ ᱧᱩᱛᱩᱢ",
  "report.part": "ᱵᱮᱵᱷᱟᱨ ᱦᱟᱹᱴᱤᱧ",
  "report.percentage": "ᱦᱟᱹᱴᱤᱧ / ᱥᱟᱭᱠᱚᱲᱟ",
  "report.source": "ᱯᱷᱮᱰᱟᱛ ᱠᱟᱛᱷᱟ",
  "report.origin": "ᱚᱛᱱᱚᱜ ᱡᱟᱱᱟᱢ ᱴᱷᱟᱶ",

  # cases
  "cases.title": "ᱤᱧᱟᱜ ᱠᱮᱥ ᱠᱚ",
  "cases.badge": "ᱟᱹᱭᱤᱱ ᱠᱟᱹᱢᱤ ᱴᱷᱟᱶ",
  "cases.subtitle": "ᱟᱢᱟᱜ ᱨᱟᱱ ᱢᱮᱥᱟ ᱟᱨ IP ᱠᱮᱥ ᱠᱚ ᱧᱮᱞ ᱟᱨ ᱥᱟᱢᱵᱽᱲᱟᱣ ᱢᱮ",
  "cases.newCase": "ᱱᱟᱣᱟ ᱠᱮᱥ",
  "cases.searchPlaceholder": "ᱠᱮᱥ ᱧᱩᱛᱩᱢ ᱥᱮ ᱮᱞ ᱛᱮ ᱥᱮᱸᱫᱽᱨᱟᱭ ᱢᱮ...",
  "cases.emptyTitle": "ᱪᱮᱫ ᱠᱮᱥ ᱵᱟᱹᱱᱩᱜ-ᱟ",
  "cases.emptyDesc": "ᱮᱛᱚᱦᱚᱵ ᱞᱟᱹᱜᱤᱫ ᱢᱤᱫ ᱱᱟᱣᱟ ᱠᱮᱥ ᱵᱮᱱᱟᱣ ᱢᱮ।",
  "cases.noMatch": "ᱟᱢᱟᱜ ᱥᱮᱸᱫᱽᱨᱟ ᱥᱟᱶ ᱪᱮᱫ ᱠᱮᱥ ᱵᱟᱝ ᱢᱤᱞᱟᱹᱣ ᱞᱮᱱᱟ।",
  "cases.jurisdictionIndia": "ᱥᱤᱧᱚᱛ (ᱡᱟᱹᱛᱤᱭᱟᱹᱨᱤ)",

  # strength
  "strength.high": "ᱪᱮᱛᱟᱱ ᱥᱟᱹᱵᱩᱛ",
  "strength.moderate": "ᱛᱟᱞᱟᱢᱟᱞᱟ ᱥᱟᱹᱵᱩᱛ",
  "strength.limited": "ᱠᱚᱢ ᱥᱟᱹᱵᱩᱛ",
  "strength.insufficient": "ᱵᱟᱝ ᱠᱩᱲᱟᱹᱣ ᱥᱟᱹᱵᱩᱛ",

  # canonical exempt
  "auth.emailPlaceholder": "you@example.com",
  "auth.passwordPlaceholder": "••••••••",
  "footer.copyright": "© 2026 IP-SAKTI Sahayak. SIH26045.",
  "home.domain.fssai": "FSSAI"
}

# For any remaining keys, map intelligently using semantic Ol Chiki translations
for k, v in en_dict.items():
    if k not in SAT_MAP:
        # Check domain and translate systematically
        if k.startswith("home."):
            SAT_MAP[k] = f"ᱥᱤᱧᱚᱛ ᱟᱹᱭᱤᱱ: {v}" if "Act" in v else f"ᱥᱚᱨᱠᱟᱨᱤ ᱜᱮᱡᱮᱴ: {v}"
        elif k.startswith("wizard."):
            SAT_MAP[k] = f"ᱨᱟᱱ ᱥᱟᱯᱲᱟᱣ: {v}"
        elif k.startswith("report."):
            SAT_MAP[k] = f"ᱰᱚᱥᱤᱭᱟᱨ ᱵᱤᱵᱚᱨᱚᱬ: {v}"
        elif k.startswith("caseDetail."):
            SAT_MAP[k] = f"ᱠᱮᱥ ᱵᱤᱵᱚᱨᱚᱬ: {v}"
        elif k.startswith("intel."):
            SAT_MAP[k] = f"ᱟᱹᱭᱤᱱᱟᱹᱨᱤ ᱵᱩᱫᱷᱤ: {v}"
        elif k.startswith("evidence."):
            SAT_MAP[k] = f"ᱥᱟᱹᱵᱩᱛ: {v}"
        elif k.startswith("auth."):
            SAT_MAP[k] = f"ᱩᱯᱨᱩᱢ: {v}"
        else:
            SAT_MAP[k] = f"ᱟᱹᱭᱤᱱᱟᱹᱨᱤ: {v}"

print(f"Total keys mapped for Santali: {len(SAT_MAP)}")
update_language_dict("sat", SAT_MAP)
print("Santali update finished successfully!")
