# -*- coding: utf-8 -*-
import json
import re

with open('frontend/src/i18n/translations/index.ts', encoding='utf-8') as f:
    content = f.read()

# Native translations for the 43 newly added keys for each script family:
# 1. Tamil (ta)
# 2. Telugu (te)
# 3. Malayalam (ml)
# 4. Bengali / Assamese / Manipuri (bn, as, mni)
# 5. Gujarati (gu)
# 6. Punjabi (pa)
# 7. Odia (or)
# 8. Urdu / Kashmiri / Sindhi (ur, ks, sd)
# 9. Santali (sat)

INTEL_PER_LANG = {
    'ta': {
        'home.evidence.actName': 'காப்புரிமைச் சட்டம், 1970',
        'home.evidence.sec3pText': 'Section 3(p): "...பாரம்பரிய அறிவாக இருக்கும் அல்லது அறியப்பட்ட கூறுகளின் பண்புகளின் நகலாக இருக்கும் ஒரு கண்டுபிடிப்பு காப்புரிமை பெறத்தக்கது அல்ல."',
        'home.multilingual.activeLanguage': 'தமிழ் (முழு ஆதரவு)',
        'home.multilingual.schedule8': '22 அதிகாரப்பூர்வ மொழிகள்',
        'home.multilingual.isolationTitle': 'தூய மொழி தனிமைப்படுத்தல்',
        'home.multilingual.isolationDesc': 'எந்த மொழி கலப்பும் இல்லாத முழுமையான உள்ளூர்மயமாக்கல்',
        'intel.act': 'சட்டம்',
        'intel.chapter': 'அத்தியாயம்',
        'intel.section': 'பிரிவு',
        'intel.subsection': 'உட்பிரிவு',
        'intel.clause': 'விதிமுறை / உட்பிரிவு',
        'intel.whatSourceEstablishes': 'அதிகாரப்பூர்வ சட்டப்பூர்வ அளவுகோல்கள் மற்றும் ஒழுங்குமுறை ஆணைகளை நிறுவுகிறது.',
        'intel.whatSourceDoesNotEstablish': 'இது வழங்கப்பட்ட காப்புரிமை அல்லது உரிம ஒப்புதல் அல்ல. இந்த விதியின் இருப்பு நிர்வாக வெற்றியை உறுதிப்படுத்தாது.',
        'intel.noGapsTitle': 'முக்கிய சான்றுகள் இடைவெளிகள் எதுவும் கண்டறியப்படவில்லை',
        'intel.noGapsDesc': 'இந்த சூத்திரத்திற்கான அனைத்து முக்கிய சட்டப்பூர்வ அளவுருக்களும் குறிப்பிடப்பட்டுள்ளன.',
        'intel.dynamicallyEvaluated': 'காப்புரிமை மற்றும் ஆயுஷ் விதிகளுக்கு எதிராக மாறும் வகையில் மதிப்பீடு செய்யப்பட்டது',
        'intel.groundingTraceActive': 'அடிப்படை சுவடு செயலில் உள்ளது',
        'intel.groundingTraceDesc': 'AI ஊகங்கள் இல்லாமல் உங்கள் சூத்திர அளவுருக்கள் எவ்வாறு விதிகள் மற்றும் சட்டப்பூர்வ மீட்டெடுப்பு வழியாக பாய்ந்தன என்பதைக் கண்காணிக்கவும்.',
        'intel.attachDocsDesc': 'வழக்கு ஆதாரங்களை வலுப்படுத்த பகுப்பாய்வு சான்றிதழ் (CoA), ஆராய்ச்சி குறிப்புகள் அல்லது கொள்முதல் ரசீதுகளை இணைக்கவும்.',
        'intel.maxFileSize': 'அதிகபட்சம்: 10MB · ஸ்கேன் செய்யப்பட்டு தனிமைப்படுத்தப்பட்டது',
        'intel.supportedFormats': 'PDF, DOCX, TXT, CSV, JSON ஆதரிக்கப்படுகிறது',
        'intel.cleanVerified': 'சுத்தமானது & சரிபார்க்கப்பட்டது',
        'intel.quarantined': 'தனிமைப்படுத்தப்பட்டது',
        'intel.securityPrinciple': 'பாதுகாப்புக் கொள்கை:',
        'intel.securityPrincipleDesc': 'அனைத்து ஆவண உள்ளடக்கங்களும் நம்பத்தகாத சமர்ப்பிப்புகளாகக் கருதப்படுகின்றன. பிரித்தெடுக்கப்பட்ட அளவுருக்கள் சட்ட விதிகளை மீற முடியாது.',
        'intel.provenanceTracer': 'மூல சுவடு காணிப்பான் (Provenance)',
        'intel.timeMachineDesc': 'வரலாற்று திருத்தங்கள், வர்த்தமானி அறிவிப்புகள் மற்றும் சட்ட விதிகளின் பரிணாமத்தை தணிக்கை செய்யவும்.',
        'intel.selectFramework': 'கட்டமைப்பைத் தேர்ந்தெடுக்கவும்:',
        'intel.gazettePdf': 'அதிகாரப்பூர்வ வர்த்தமானி PDF',
        'intel.clauseComparison': 'விதி வாரியான ஒப்பீடு மற்றும் நடைமுறை பகுப்பாய்வு',
        'intel.previousText': 'முந்தைய / அசல் உரை',
        'intel.amendedText': 'திருத்தப்பட்ட / இயற்றப்பட்ட உரை',
        'intel.sec3pBar': 'Section 3(p) தடை',
        'intel.applicable': 'பொருந்தும்',
        'intel.synergyRequired': 'Section 3(p) தடையை வெல்ல ஒருங்கிணைந்த தொழில்நுட்ப தரவு தேவை.',
        'intel.slaGmpRequired': 'மாநில ஆயுஷ் உரிம ஆணையம் Schedule T GMP ஒப்புதல் தேவை.',
        'intel.sbbSec7Mandatory': 'கட்டாய முன் அறிவிப்பு',
        'intel.sbbSec7Exemption': 'விலக்கு மறுஆய்வு',
        'intel.nbaSec6Title': 'காப்புரிமை மானியத்திற்கான முன் Form III ஒப்புதல்',
        'intel.benefitSharingRate': 'தொழிற்சாலை பயன் பகிர்வு விகிதம்: 0.1% முதல் 0.5% வரை.',
        'intel.actionSbb': '1. SBB Form I அறிவிப்பைத் தாக்கல் செய்யவும்',
        'intel.actionCoa': '2. NABL கனரக உலோகங்கள் & நுண்ணுயிர் CoA',
        'intel.actionTm': '3. வர்த்தக முத்திரை Class 5 விண்ணப்பம்',
    },
    'te': {
        'home.evidence.actName': 'పేటెంట్ల చట్టం, 1970',
        'home.evidence.sec3pText': 'Section 3(p): "...సాంప్రదాయ పరిజ్ఞానంగా ఉన్న లేదా తెలిసిన భాగాల లక్షణాల కలయికగా ఉన్న ఆవిష్కరణ పేటెంట్ పొందేందుకు అర్హత లేదు."',
        'home.multilingual.activeLanguage': 'తెలుగు (పూర్తి మద్దతు)',
        'home.multilingual.schedule8': '22 అధికారిక భాషలు',
        'home.multilingual.isolationTitle': 'భాషా వివిక్తత',
        'home.multilingual.isolationDesc': 'ఏ ఇతర భాషా మిశ్రమం లేని పూర్తి స్థానికీకరణ',
        'intel.act': 'చట్టం',
        'intel.chapter': 'అధ్యాయం',
        'intel.section': 'విభాగం',
        'intel.subsection': 'ఉపవిభాగం',
        'intel.clause': 'నిబంధన / క్లాజ్',
        'intel.whatSourceEstablishes': 'అధికారిక చట్టబద్ధమైన ప్రమాణాలు మరియు బైండింగ్ నియంత్రణ ఆదేశాలను ఏర్పాటు చేస్తుంది.',
        'intel.whatSourceDoesNotEstablish': 'ఇది మంజూరు చేయబడిన పేటెంట్ లేదా లైసెన్స్ ఆమోదం కాదు. ఈ నిబంధన ఉండటం పరిపాలనా విజయానికి హామీ ఇవ్వదు.',
        'intel.noGapsTitle': 'ఎటువంటి క్లిష్టమైన సాక్ష్య అంతరాలు కనుగొనబడలేదు',
        'intel.noGapsDesc': 'ఈ ఫార్ములేషన్ కోసం అన్ని ప్రధాన చట్టబద్ధమైన పారామితులు పేర్కొనబడ్డాయి.',
        'intel.dynamicallyEvaluated': 'పేటెంట్ మరియు ఆయుష్ నిబంధనలకు అనుగుణంగా డైనమిక్‌గా మూల్యాంకనం చేయబడింది',
        'intel.groundingTraceActive': 'గ్రౌండింగ్ ట్రేస్ సక్రియంగా ఉంది',
        'intel.groundingTraceDesc': 'AI ఊహాగానాలు లేకుండా మీ ఫార్ములేషన్ పారామితులు నియమాలు మరియు చట్టబద్ధమైన పునరుద్ధరణ ద్వారా ఎలా ప్రవహించాయో ట్రేస్ చేయండి.',
        'intel.attachDocsDesc': 'కేసు సాక్ష్యాన్ని బలపరచడానికి విశ్లేషణ సర్టిఫికేట్ (CoA), పరిశోధన గమనికలు లేదా రసీదులను జత చేయండి.',
        'intel.maxFileSize': 'గరిష్ట పరిమాణం: 10MB · స్కాన్ చేయబడింది మరియు వేరుచేయబడింది',
        'intel.supportedFormats': 'PDF, DOCX, TXT, CSV, JSON మద్దతు ఉంది',
        'intel.cleanVerified': 'శుభ్రం & ధృవీకరించబడింది',
        'intel.quarantined': 'వేరుచేయబడింది (క్వారంటైన్)',
        'intel.securityPrinciple': 'భద్రతా సూత్రం:',
        'intel.securityPrincipleDesc': 'అన్ని పత్ర విషయాలు నమ్మదగని వినియోగదారు సమర్పణలుగా పరిగణించబడతాయి. సంగ్రహించిన పారామితులు చట్టబద్ధమైన నియమాలను అధిగమించలేవు.',
        'intel.provenanceTracer': 'మూల మూలాధార ట్రేసర్ (Provenance)',
        'intel.timeMachineDesc': 'చారిత్రక సవరణలు, గెజిట్ నోటిఫికేషన్లు మరియు చట్టబద్ధమైన నిబంధనల పరిణామాన్ని ఆడిట్ చేయండి.',
        'intel.selectFramework': 'చట్రాన్ని ఎంచుకోండి:',
        'intel.gazettePdf': 'అధికారిక గెజిట్ PDF',
        'intel.clauseComparison': 'క్లాజ్ వారీ పోలిక మరియు ఆచరణాత్మక విశ్లేషణ',
        'intel.previousText': 'మునుపటి / అసలు వచనం',
        'intel.amendedText': 'సవరించిన / అమలు చేయబడిన వచనం',
        'intel.sec3pBar': 'Section 3(p) నిషేధం',
        'intel.applicable': 'వర్తిస్తుంది',
        'intel.synergyRequired': 'Section 3(p) నిషేధాన్ని అధిగమించడానికి సినర్జిస్టిక్ సాంకేతిక డేటా అవసరం.',
        'intel.slaGmpRequired': 'రాష్ట్ర ఆయుష్ లైసెన్సింగ్ అథారిటీ Schedule T GMP ఆమోదం అవసరం.',
        'intel.sbbSec7Mandatory': 'తప్పనిసరి ముందస్తు సమాచారం',
        'intel.sbbSec7Exemption': 'మినహాయింపు సమీక్ష',
        'intel.nbaSec6Title': 'పేటెంట్ మంజూరు కోసం ముందస్తు Form III ఆమోదం',
        'intel.benefitSharingRate': 'ఎక్స్-ఫ్యాక్టరీ ప్రయోజన భాగస్వామ్య రేటు: 0.1% నుండి 0.5%.',
        'intel.actionSbb': '1. SBB Form I సమాచారాన్ని దాఖలు చేయండి',
        'intel.actionCoa': '2. NABL భారీ లోహాలు & సూక్ష్మజీవుల CoA',
        'intel.actionTm': '3. ట్రేడ్‌మార్క్ Class 5 దరఖాస్తు',
    },
    'ml': {
        'home.evidence.actName': 'പേറ്റന്റ് നിയമം, 1970',
        'home.evidence.sec3pText': 'Section 3(p): "...പരമ്പരാഗത അറിവായതോ പരമ്പരാഗതമായി അറിയപ്പെടുന്ന ഘടകങ്ങളുടെ ഗുണങ്ങളുടെ സംയോജനമോ ആയ ഒരു കണ്ടുപിടുത്തത്തിന് പേറ്റന്റ് ലഭ്യമല്ല."',
        'home.multilingual.activeLanguage': 'മലയാളം (പൂർണ്ണ പിന്തുണ)',
        'home.multilingual.schedule8': '22 ഔദ്യോഗിക ഭാഷകൾ',
        'home.multilingual.isolationTitle': 'ശുദ്ധമായ ഭാഷാ ഒറ്റപ്പെടുത്തൽ',
        'home.multilingual.isolationDesc': 'മറ്റ് ഭാഷാ മിശ്രണമില്ലാത്ത സമ്പൂർണ്ണ പ്രാദേശികവൽക്കരണം',
        'intel.act': 'നിയമം',
        'intel.chapter': 'അധ്യായം',
        'intel.section': 'വകുപ്പ്',
        'intel.subsection': 'ഉപവകുപ്പ്',
        'intel.clause': 'ഖണ്ഡിക',
        'intel.whatSourceEstablishes': 'ആധികാരിക നിയമപരമായ മാനദണ്ഡങ്ങളും നിയന്ത്രണ നിർദ്ദേശങ്ങളും സ്ഥാപിക്കുന്നു.',
        'intel.whatSourceDoesNotEstablish': 'ഇത് അനുവദിച്ച പേറ്റന്റോ ലൈസൻസ് അംഗീകാരമോ അല്ല. ഈ നിയമത്തിന്റെ നിലനിൽപ്പ് വിജയത്തിന് ഉറപ്പുനൽകുന്നില്ല.',
        'intel.noGapsTitle': 'ഗുരുതരമായ തെളിവുകളുടെ വിടവുകൾ കണ്ടെത്തിയില്ല',
        'intel.noGapsDesc': 'ഈ ഫോർമുലേഷനായി എല്ലാ പ്രധാന നിയമപരമായ പാരാമീറ്ററുകളും വ്യക്തമാക്കിയിട്ടുണ്ട്.',
        'intel.dynamicallyEvaluated': 'പേറ്റന്റ്, ആയുഷ് നിയമങ്ങൾക്കെതിരെ വിലയിരുത്തി',
        'intel.groundingTraceActive': 'ഗ്രൗണ്ടിംഗ് ട്രെയ്സ് സജീവം',
        'intel.groundingTraceDesc': 'AI ഊഹാപോഹങ്ങളില്ലാതെ ഫോർമുലേഷൻ പാരാമീറ്ററുകൾ എങ്ങനെ നിയമപരമായ വീണ്ടെടുപ്പിലൂടെ കടന്നുപോയി എന്ന് കണ്ടെത്തുക.',
        'intel.attachDocsDesc': 'കേസ് തെളിവുകൾക്കായി വിശകലന സർട്ടിഫിക്കറ്റ് (CoA), ഗവേഷണ കുറിപ്പുകൾ അല്ലെങ്കിൽ രസീതുകൾ അറ്റാച്ചുചെയ്യുക.',
        'intel.maxFileSize': 'പരമാവധി: 10MB · സ്കാൻ ചെയ്ത് ക്വാറന്റൈൻ ചെയ്തു',
        'intel.supportedFormats': 'PDF, DOCX, TXT, CSV, JSON പിന്തുണയ്ക്കുന്നു',
        'intel.cleanVerified': 'ശുദ്ധവും പരിശോധിച്ചതുമാണ്',
        'intel.quarantined': 'ക്വാറന്റൈൻ ചെയ്തു',
        'intel.securityPrinciple': 'സുരക്ഷാ തത്വം:',
        'intel.securityPrincipleDesc': 'എല്ലാ ഡോക്യുമെന്റുകളും അവിശ്വസനീയ സമർപ്പണങ്ങളായി കണക്കാക്കുന്നു. എക്‌സ്‌ട്രാക്റ്റുചെയ്‌ത പാരാമീറ്ററുകൾക്ക് നിയമങ്ങളെ മറികടക്കാൻ കഴിയില്ല.',
        'intel.provenanceTracer': 'ഉറവിട ട്രെയ്സർ (Provenance)',
        'intel.timeMachineDesc': 'ചരിത്രപരമായ ഭേദഗതികളും ഗസറ്റ് വിജ്ഞാപനങ്ങളും ഓഡിറ്റ് ചെയ്യുക.',
        'intel.selectFramework': 'ചട്ടക്കൂട് തിരഞ്ഞെടുക്കുക:',
        'intel.gazettePdf': 'ഔദ്യോഗിക ഗസറ്റ് PDF',
        'intel.clauseComparison': 'ഖണ്ഡികാ തിരിച്ചുള്ള താരതമ്യവും വിശകലനവും',
        'intel.previousText': 'മുമ്പത്തെ / യഥാർത്ഥ വാചകം',
        'intel.amendedText': 'ഭേദഗതി വരുത്തിയ / പ്രാബല്യത്തിലുള്ള വാചകം',
        'intel.sec3pBar': 'Section 3(p) തടസ്സം',
        'intel.applicable': 'ബാധകമാണ്',
        'intel.synergyRequired': 'Section 3(p) മറികടക്കാൻ സിനർജിസ്റ്റിക് ഡാറ്റ ആവശ്യമാണ്.',
        'intel.slaGmpRequired': 'സംസ്ഥാന ആയുഷ് അതോറിറ്റി Schedule T GMP അംഗീകാരം ആവശ്യമാണ്.',
        'intel.sbbSec7Mandatory': 'നിർബന്ധിത മുൻകൂർ അറിയിപ്പ്',
        'intel.sbbSec7Exemption': 'ഒഴിവാക്കൽ അവലോകനം',
        'intel.nbaSec6Title': 'പേറ്റന്റ് ഗ്രാന്റിനുള്ള മുൻകൂർ Form III അംഗീകാരം',
        'intel.benefitSharingRate': 'ഫാക്ടറി ആനുകൂല്യ പങ്കിടൽ നിരക്ക്: 0.1% മുതൽ 0.5% വരെ.',
        'intel.actionSbb': '1. SBB Form I അറിയിപ്പ് ഫയൽ ചെയ്യുക',
        'intel.actionCoa': '2. NABL ഹെവി മെറ്റൽസ് & മൈക്രോബിയൽ CoA',
        'intel.actionTm': '3. ട്രേഡ്മാർക്ക് Class 5 അപേക്ഷ',
    },
    'bn': {
        'home.evidence.actName': 'পেটেন্ট আইন, ১৯৭০',
        'home.evidence.sec3pText': 'Section 3(p): "...একটি উদ্ভাবন যা ঐতিহ্যগত জ্ঞান বা ঐতিহ্যগতভাবে পরিচিত উপাদানগুলির পরিচিত বৈশিষ্ট্যের সমষ্টি তা পেটেন্টযোগ্য নয়।"',
        'home.multilingual.activeLanguage': 'বাংলা (সম্পূর্ণ সমর্থন)',
        'home.multilingual.schedule8': '২২টি সরকারী ভাষা',
        'home.multilingual.isolationTitle': 'বিশুদ্ধ ভাষা পৃথকীকরণ',
        'home.multilingual.isolationDesc': 'কোনো ভাষার মিশ্রণ ছাড়াই সম্পূর্ণ স্থানীয়করণ',
        'intel.act': 'আইন',
        'intel.chapter': 'অধ্যায়',
        'intel.section': 'ধারা',
        'intel.subsection': 'উপধারা',
        'intel.clause': 'দফা',
        'intel.whatSourceEstablishes': 'কর্তৃত্বপূর্ণ সংবিধিবদ্ধ মানদণ্ড এবং বাধ্যতামূলক নিয়ন্ত্রক আদেশ স্থাপন করে।',
        'intel.whatSourceDoesNotEstablish': 'এটি মঞ্জুর করা পেটেন্ট বা লাইসেন্স অনুমোদন নয়। এই বিধির অস্তিত্ব প্রশাসনিক সাফল্যের নিশ্চয়তা দেয় না।',
        'intel.noGapsTitle': 'কোনো গুরুত্বপূর্ণ প্রমাণের ঘাটতি পাওয়া যায়নি',
        'intel.noGapsDesc': 'এই ফর্মুলেশনের জন্য সমস্ত মূল সংবিধিবদ্ধ পরামিতি নির্দিষ্ট করা হয়েছে।',
        'intel.dynamicallyEvaluated': 'পেটেন্ট এবং আয়ুষ বিধিমালার বিরুদ্ধে গতিশীলভাবে মূল্যায়ন করা হয়েছে',
        'intel.groundingTraceActive': 'গ্রাউন্ডিং ট্রেস সক্রিয়',
        'intel.groundingTraceDesc': 'এআই অনুমান ছাড়াই ফর্মুলেশন প্যারামিটারগুলি কীভাবে কার্যকর হয়েছে তা ট্রেস করুন।',
        'intel.attachDocsDesc': 'প্রমাণ শক্তিশালী করতে বিশ্লেষণের শংসাপত্র (CoA) বা রসিদ সংযুক্ত করুন।',
        'intel.maxFileSize': 'সর্বোচ্চ: 10MB · স্ক্যান করা এবং কোয়ারেন্টাইন করা হয়েছে',
        'intel.supportedFormats': 'PDF, DOCX, TXT, CSV, JSON সমর্থিত',
        'intel.cleanVerified': 'পরিষ্কার এবং যাচাইকৃত',
        'intel.quarantined': 'কোয়ারেন্টাইন করা হয়েছে',
        'intel.securityPrinciple': 'নিরাপত্তা নীতি:',
        'intel.securityPrincipleDesc': 'সমস্ত নথির বিষয়বস্তু অবিশ্বাসযোগ্য ব্যবহারকারী জমা হিসাবে গণ্য করা হয়।',
        'intel.provenanceTracer': 'উৎস ট্রেসার (Provenance)',
        'intel.timeMachineDesc': 'ঐতিহাসিক সংশোধনী এবং গেজেট বিজ্ঞপ্তি অডিট করুন।',
        'intel.selectFramework': 'কাঠামো নির্বাচন করুন:',
        'intel.gazettePdf': 'অফিসিয়াল গেজেট PDF',
        'intel.clauseComparison': 'দফা অনুযায়ী তুলনা এবং ব্যবহারিক বিশ্লেষণ',
        'intel.previousText': 'পূর্ববর্তী / মূল পাঠ্য',
        'intel.amendedText': 'সংশোধিত / কার্যকর পাঠ্য',
        'intel.sec3pBar': 'Section 3(p) নিষেধাজ্ঞা',
        'intel.applicable': 'প্রযোজ্য',
        'intel.synergyRequired': 'Section 3(p) কাটিয়ে উঠতে সমন্বিত প্রযুক্তিগত তথ্য প্রয়োজন।',
        'intel.slaGmpRequired': 'রাজ্য আয়ুষ লাইসেন্সিং কর্তৃপক্ষ Schedule T GMP অনুমোদন প্রয়োজন।',
        'intel.sbbSec7Mandatory': 'বাধ্যতামূলক পূর্ব তথ্য',
        'intel.sbbSec7Exemption': 'অব্যাহতি পর্যালোচনা',
        'intel.nbaSec6Title': 'পেটেন্ট অনুদানের জন্য পূর্ববর্তী Form III অনুমোদন',
        'intel.benefitSharingRate': 'কারখানা সুবিধা ভাগাভাগির হার: ০.১% থেকে ০.৫%।',
        'intel.actionSbb': '১. SBB Form I তথ্য দাখিল করুন',
        'intel.actionCoa': '২. NABL ভারী ধাতু ও মাইক্রোবিয়াল CoA',
        'intel.actionTm': '৩. ট্রেডমার্ক Class 5 আবেদন',
    },
    'gu': {
        'home.evidence.actName': 'ધી પેટન્ટ્સ એક્ટ, ૧૯૭૦',
        'home.evidence.sec3pText': 'Section 3(p): "...એવી શોધ જે પરંપરાગત જ્ઞાન છે અથવા પરંપરાગત રીતે જાણીતા ઘટકોના ગુણધર્મોનું માત્ર એકત્રીકરણ છે તે પેટન્ટપાત્ર નથી."',
        'home.multilingual.activeLanguage': 'ગુજરાતી (સંપૂર્ણ સમર્થન)',
        'home.multilingual.schedule8': '૨૨ સત્તાવાર ભાષાઓ',
        'home.multilingual.isolationTitle': 'ચુસ્ત ભાષા અલગતા',
        'home.multilingual.isolationDesc': 'કોઈપણ ભાષાકીય મિશ્રણ વિના સંપૂર્ણ સ્થાનિકીકરણ',
        'intel.act': 'કાયદો',
        'intel.chapter': 'પ્રકરણ',
        'intel.section': 'કલમ',
        'intel.subsection': 'પેટા-કલમ',
        'intel.clause': 'ખંડ',
        'intel.whatSourceEstablishes': 'અધિકૃત વૈધાનિક માપદંડો અને બંધનકર્તા નિયમનકારી આદેશો સ્થાપિત કરે છે.',
        'intel.whatSourceDoesNotEstablish': 'આ કોઈ મંજૂર થયેલ પેટન્ટ અથવા લાયસન્સ નથી. આ નિયમ વહીવટી સફળતાની ખાતરી આપતો નથી.',
        'intel.noGapsTitle': 'પુરાવાની કોઈ ગંભીર ખામી મળી નથી',
        'intel.noGapsDesc': 'આ ફોર્મ્યુલેશન માટે તમામ મુખ્ય વૈધાનિક પરિમાણો નિર્દિષ્ટ છે.',
        'intel.dynamicallyEvaluated': 'પેટન્ટ અને આયુષ નિયમો સામે મૂલ્યાંકન કરેલ',
        'intel.groundingTraceActive': 'ગ્રાઉન્ડિંગ ટ્રેસ સક્રિય',
        'intel.groundingTraceDesc': 'કોઈપણ એઆઈ અનુમાન વિના તમારા પરિમાણોનું પગેરું શોધો.',
        'intel.attachDocsDesc': 'પુરાવા માટે વિશ્લેષણ પ્રમાણપત્ર (CoA) અથવા રસીદો જોડો.',
        'intel.maxFileSize': 'મહત્તમ: 10MB · સ્કેન અને અલગ રાખવામાં આવેલ',
        'intel.supportedFormats': 'PDF, DOCX, TXT, CSV, JSON સમર્થિત',
        'intel.cleanVerified': 'ચકાસાયેલ અને સ્વચ્છ',
        'intel.quarantined': 'ક્વોરેન્ટાઇન કરેલ',
        'intel.securityPrinciple': 'સુરક્ષા સિદ્ધાંત:',
        'intel.securityPrincipleDesc': 'તમામ દસ્તાવેજોને અવિશ્વસનીય સબમિશન ગણવામાં આવે છે.',
        'intel.provenanceTracer': 'મૂળ સ્ત્રોત ટ્રેસર (Provenance)',
        'intel.timeMachineDesc': 'ઐતિહાસિક સુધારાઓ અને ગેઝેટ સૂચનાઓનું ઓડિટ કરો.',
        'intel.selectFramework': 'માળખું પસંદ કરો:',
        'intel.gazettePdf': 'સત્તાવાર ગેઝેટ PDF',
        'intel.clauseComparison': 'કલમવાર સરખામણી અને વિશ્લેષણ',
        'intel.previousText': 'અગાઉનો / મૂળ પાઠ',
        'intel.amendedText': 'સુધારેલ પાઠ',
        'intel.sec3pBar': 'Section 3(p) પ્રતિબંધ',
        'intel.applicable': 'લાગુ પડે છે',
        'intel.synergyRequired': 'Section 3(p) દૂર કરવા માટે સિનર્જિસ્ટિક ટેકનિકલ ડેટા જરૂરી છે.',
        'intel.slaGmpRequired': 'રાજ્ય આયુષ લાયસન્સિંગ ઓથોરિટી Schedule T GMP મંજૂરી જરૂરી છે.',
        'intel.sbbSec7Mandatory': 'ફરજિયાત પૂર્વ માહિતી',
        'intel.sbbSec7Exemption': 'મુક્તિ સમીક્ષા',
        'intel.nbaSec6Title': 'પેટન્ટ અનુદાન માટે પૂર્વ Form III મંજૂરી',
        'intel.benefitSharingRate': 'ફેક્ટરી નિકાસ લાભ વહેંચણી દર: ૦.૧% થી ૦.૫%.',
        'intel.actionSbb': '૧. SBB Form I માહિતી દાખલ કરો',
        'intel.actionCoa': '૨. NABL ભારે ધાતુઓ અને માઇક્રોબાયલ CoA',
        'intel.actionTm': '૩. ટ્રેડમાર્ક Class 5 અરજી',
    },
    'pa': {
        'home.evidence.actName': 'ਪੇਟੈਂਟ ਐਕਟ, 1970',
        'home.evidence.sec3pText': 'Section 3(p): "...ਇੱਕ ਕਾਢ ਜੋ ਰਵਾਇਤੀ ਗਿਆਨ ਹੈ ਜਾਂ ਰਵਾਇਤੀ ਤੌਰ ਤੇ ਜਾਣੇ ਜਾਂਦੇ ਹਿੱਸਿਆਂ ਦੇ ਗੁਣਾਂ ਦਾ ਜੋੜ ਹੈ, ਪੇਟੈਂਟ ਯੋਗ ਨਹੀਂ ਹੈ।"',
        'home.multilingual.activeLanguage': 'ਪੰਜਾਬੀ (ਪੂਰਾ ਸਮਰਥਨ)',
        'home.multilingual.schedule8': '22 ਅਧਿਕਾਰਤ ਭਾਸ਼ਾਵਾਂ',
        'home.multilingual.isolationTitle': 'ਸਖ਼ਤ ਭਾਸ਼ਾ ਵੱਖਰਾਪਣ',
        'home.multilingual.isolationDesc': 'ਬਿਨਾਂ ਕਿਸੇ ਭਾਸ਼ਾਈ ਮਿਸ਼ਰਣ ਦੇ ਪੂਰਾ ਸਥਾਨਕੀਕਰਨ',
        'intel.act': 'ਐਕਟ',
        'intel.chapter': 'ਅਧਿਆਇ',
        'intel.section': 'ਧਾਰਾ',
        'intel.subsection': 'ਉਪ-ਧਾਰਾ',
        'intel.clause': 'ਕਲਾਜ਼',
        'intel.whatSourceEstablishes': 'ਅਧਿਕਾਰਤ ਕਾਨੂੰਨੀ ਮਾਪਦੰਡ ਅਤੇ ਨਿਯਮਤ ਆਦੇਸ਼ ਸਥਾਪਤ ਕਰਦਾ ਹੈ।',
        'intel.whatSourceDoesNotEstablish': 'ਇਹ ਮਨਜ਼ੂਰਸ਼ੁਦਾ ਪੇਟੈਂਟ ਜਾਂ ਲਾਇਸੈਂਸ ਨਹੀਂ ਹੈ।',
        'intel.noGapsTitle': 'ਕੋਈ ਨਾਜ਼ੁਕ ਸਬੂਤ ਅੰਤਰ ਨਹੀਂ ਮਿਲਿਆ',
        'intel.noGapsDesc': 'ਇਸ ਫਾਰਮੂਲੇ ਲਈ ਸਾਰੇ ਮੁੱਖ ਕਾਨੂੰਨੀ ਮਾਪਦੰਡ ਨਿਰਧਾਰਤ ਕੀਤੇ ਗਏ ਹਨ।',
        'intel.dynamicallyEvaluated': 'ਪੇਟੈਂਟ ਅਤੇ ਆਯੁਸ਼ ਨਿਯਮਾਂ ਦੇ ਵਿਰੁੱਧ ਮੁਲਾਂਕਣ ਕੀਤਾ ਗਿਆ',
        'intel.groundingTraceActive': 'ਗਰਾਊਂਡਿੰਗ ਟਰੇਸ ਸਰਗਰਮ',
        'intel.groundingTraceDesc': 'ਟਰੇਸ ਕਰੋ ਕਿ ਤੁਹਾਡੇ ਫਾਰਮੂਲੇਸ਼ਨ ਪੈਰਾਮੀਟਰ ਕਿਵੇਂ ਕੰਮ ਕਰਦੇ ਹਨ।',
        'intel.attachDocsDesc': 'ਸਬੂਤ ਲਈ ਵਿਸ਼ਲੇਸ਼ਣ ਸਰਟੀਫਿਕੇਟ (CoA) ਜਾਂ ਰਸੀਦਾਂ ਨੱਥੀ ਕਰੋ।',
        'intel.maxFileSize': 'ਵੱਧ ਤੋਂ ਵੱਧ: 10MB · ਸਕੈਨ ਅਤੇ ਕੁਆਰੰਟੀਨ ਕੀਤਾ',
        'intel.supportedFormats': 'PDF, DOCX, TXT, CSV, JSON ਸਮਰਥਿਤ',
        'intel.cleanVerified': 'ਸਾਫ਼ ਅਤੇ ਪ੍ਰਮਾਣਿਤ',
        'intel.quarantined': 'ਕੁਆਰੰਟੀਨ ਕੀਤਾ',
        'intel.securityPrinciple': 'ਸੁਰੱਖਿਆ ਸਿਧਾਂਤ:',
        'intel.securityPrincipleDesc': 'ਸਾਰੇ ਦਸਤਾਵੇਜ਼ ਗੈਰ-ਭਰੋਸੇਯੋਗ ਮੰਨੇ ਜਾਂਦੇ ਹਨ।',
        'intel.provenanceTracer': 'ਮੂਲ ਸਰੋਤ ਟਰੇਸਰ (Provenance)',
        'intel.timeMachineDesc': 'ਇਤਿਹਾਸਕ ਸੋਧਾਂ ਦਾ ਆਡਿਟ ਕਰੋ।',
        'intel.selectFramework': 'ਫਰੇਮਵਰਕ ਚੁਣੋ:',
        'intel.gazettePdf': 'ਅਧਿਕਾਰਤ ਗਜ਼ਟ PDF',
        'intel.clauseComparison': 'ਕਲਾਜ਼ ਅਨੁਸਾਰ ਤੁਲਨਾ ਅਤੇ ਵਿਸ਼ਲੇਸ਼ਣ',
        'intel.previousText': 'ਪਿਛਲਾ / ਮੂਲ ਪਾਠ',
        'intel.amendedText': 'ਸੋਧਿਆ ਹੋਇਆ ਪਾਠ',
        'intel.sec3pBar': 'Section 3(p) ਰੋਕ',
        'intel.applicable': 'ਲਾਗੂ',
        'intel.synergyRequired': 'Section 3(p) ਨੂੰ ਦੂਰ ਕਰਨ ਲਈ ਸਿਨਰਜਿਸਟਿਕ ਤਕਨੀਕੀ ਡੇਟਾ ਲੋੜੀਂਦਾ ਹੈ।',
        'intel.slaGmpRequired': 'ਰਾਜ ਆਯੁਸ਼ ਲਾਇਸੈਂਸਿੰਗ ਅਥਾਰਟੀ Schedule T GMP ਪ੍ਰਵਾਨਗੀ ਲੋੜੀਂਦੀ ਹੈ।',
        'intel.sbbSec7Mandatory': 'ਲਾਜ਼ਮੀ ਪੂਰਵ ਸੂਚਨਾ',
        'intel.sbbSec7Exemption': 'ਛੋਟ ਸਮੀਖਿਆ',
        'intel.nbaSec6Title': 'ਪੇਟੈਂਟ ਗ੍ਰਾਂਟ ਲਈ ਪੂਰਵ Form III ਪ੍ਰਵਾਨਗੀ',
        'intel.benefitSharingRate': 'ਲਾਭ ਸਾਂਝਾ ਕਰਨ ਦੀ ਦਰ: 0.1% ਤੋਂ 0.5%।',
        'intel.actionSbb': '1. SBB Form I ਸੂਚਨਾ ਦਾਇਰ ਕਰੋ',
        'intel.actionCoa': '2. NABL ਭਾਰੀ ਧਾਤਾਂ ਅਤੇ ਸੂਖਮ ਜੀਵ CoA',
        'intel.actionTm': '3. ਟਰੇਡਮਾਰਕ Class 5 ਅਰਜ਼ੀ',
    },
    'or': {
        'home.evidence.actName': 'ପେଟେଣ୍ଟ ଆଇନ, ୧୯୭୦',
        'home.evidence.sec3pText': 'Section 3(p): "...ଏକ ଉଦ୍ଭାବନ ଯାହା ପାରମ୍ପରିକ ଜ୍ଞାନ ଅଟେ ତାହା ପେଟେଣ୍ଟ ଯୋଗ୍ୟ ନୁହେଁ।|"',
        'home.multilingual.activeLanguage': 'ଓଡ଼ିଆ (ସମ୍ପୂର୍ଣ୍ଣ ସମର୍ଥନ)',
        'home.multilingual.schedule8': '୨୨ଟି ସରକାରୀ ଭାଷା',
        'home.multilingual.isolationTitle': 'ଶୁଦ୍ଧ ଭାଷା ପୃଥକୀକରଣ',
        'home.multilingual.isolationDesc': 'କୌଣସି ଭାଷା ମିଶ୍ରଣ ବିନା ସମ୍ପୂର୍ଣ୍ଣ ସ୍ଥାନୀୟକରଣ',
        'intel.act': 'ଆଇନ',
        'intel.chapter': 'ଅଧ୍ୟାୟ',
        'intel.section': 'ଧାରା',
        'intel.subsection': 'ଉପ-ଧାରା',
        'intel.clause': 'ଦଫା',
        'intel.whatSourceEstablishes': 'ଅଧିକୃତ ବୈଧାନିକ ମାନଦଣ୍ଡ ସ୍ଥାପନ କରେ।',
        'intel.whatSourceDoesNotEstablish': 'ଏହା ଏକ ମଞ୍ଜୁର ହୋଇଥିବା ପେଟେଣ୍ଟ ନୁହେଁ।',
        'intel.noGapsTitle': 'କୌଣସି ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ପ୍ରମାଣ ଅନ୍ତର ମିଳିଲା ନାହିଁ',
        'intel.noGapsDesc': 'ସମସ୍ତ ମୁଖ୍ୟ ବୈଧାନିକ ପାରାମିଟର ନିର୍ଦ୍ଦିଷ୍ଟ କରାଯାଇଛି।',
        'intel.dynamicallyEvaluated': 'ପେଟେଣ୍ଟ ଏବଂ ଆୟୁଷ ନିୟମ ବିରୁଦ୍ଧରେ ମୂଲ્યાંକନ କରାଯାଇଛି',
        'intel.groundingTraceActive': 'ଗ୍ରାଉଣ୍ଡିଂ ଟ୍ରେସ୍ ସକ୍ରିୟ',
        'intel.groundingTraceDesc': 'ନିୟମ ଏବଂ ପୁନରୁଦ୍ଧାର ମାଧ୍ୟମରେ କିପରି ପ୍ରବାହିତ ହୋଇଛି ଟ୍ରେସ୍ କରନ୍ତୁ।',
        'intel.attachDocsDesc': 'ବିଶ୍ଳେଷଣ ପ୍ରମାଣପତ୍ର (CoA) କିମ୍ବା ରସିଦ ସଂଲଗ୍ନ କରନ୍ତୁ।',
        'intel.maxFileSize': 'ସର୍ବାଧିକ: 10MB · ସ୍କାନ ଏବଂ ପୃଥକ କରାଯାଇଛି',
        'intel.supportedFormats': 'PDF, DOCX, TXT, CSV, JSON ସମର୍ଥିତ',
        'intel.cleanVerified': 'ପରିଷ୍କାର ଏବଂ ଯାଞ୍ଚ ହୋଇଛି',
        'intel.quarantined': 'ପୃଥକ କରାଯାଇଛି',
        'intel.securityPrinciple': 'ସୁରକ୍ଷା ନୀତି:',
        'intel.securityPrincipleDesc': 'ସମସ୍ତ ଦସ୍ତାବିଜକୁ ଅବିଶ୍ୱସ୍ତ ଭାବରେ ଗ୍ରହଣ କରାଯାଏ।',
        'intel.provenanceTracer': 'ମୂଳ ଉତ୍ସ ଟ୍ରେସର (Provenance)',
        'intel.timeMachineDesc': 'ଐତିହାସିକ ସଂଶୋଧନ ଅଡିଟ୍ କରନ୍ତୁ।',
        'intel.selectFramework': 'ଚୟନ କରନ୍ତୁ:',
        'intel.gazettePdf': 'ସରକାରୀ ଗେଜେଟ୍ PDF',
        'intel.clauseComparison': 'ଦଫା ଅନୁସାରେ ତୁଳନା',
        'intel.previousText': 'ପୂର୍ବ ପାଠ',
        'intel.amendedText': 'ସଂଶୋଧିତ ପାଠ',
        'intel.sec3pBar': 'Section 3(p) ରୋକ',
        'intel.applicable': 'ପ୍ରଯୁଜ୍ୟ',
        'intel.synergyRequired': 'Section 3(p) ପାଇଁ ସିନର୍ଜିଷ୍ଟିକ୍ ଡାଟା ଆବଶ୍ୟକ।',
        'intel.slaGmpRequired': 'ରାଜ୍ୟ ଆୟୁଷ Schedule T GMP ଅନୁମୋଦନ ଆବଶ୍ୟକ।',
        'intel.sbbSec7Mandatory': 'ବାଧ୍ୟତାମୂଳକ ପୂର୍ବ ସୂଚନା',
        'intel.sbbSec7Exemption': 'ଛାଡ଼ ସମୀକ୍ଷା',
        'intel.nbaSec6Title': 'ପେଟେଣ୍ଟ ମଞ୍ଜୁରୀ ପାଇଁ ପୂର୍ବ Form III ଅନୁମୋଦନ',
        'intel.benefitSharingRate': 'ଲାଭ ବଣ୍ଟନ ହାର: ୦.୧% ରୁ ୦.୫%।',
        'intel.actionSbb': '୧. SBB Form I ଦାଖଲ କରନ୍ତୁ',
        'intel.actionCoa': '୨. NABL ଭାରୀ ଧାତୁ CoA',
        'intel.actionTm': '୩. ଟ୍ରେଡମାର୍କ Class 5 ଆବେଦନ',
    },
    'ur': {
        'home.evidence.actName': 'دی پیٹنٹس ایکٹ، 1970',
        'home.evidence.sec3pText': 'Section 3(p): "...ایک ایسی ایجاد جو روایتی علم ہے پیٹنٹ کے قابل نہیں ہے۔"',
        'home.multilingual.activeLanguage': 'اردو (مکمل معاونت)',
        'home.multilingual.schedule8': '22 سرکاری زبانیں',
        'home.multilingual.isolationTitle': 'خالص زبان کی تنہائی',
        'home.multilingual.isolationDesc': 'بغیر کسی لسانی ملاوٹ کے مکمل مقامی بنانا',
        'intel.act': 'ایکٹ',
        'intel.chapter': 'باب',
        'intel.section': 'دفعہ',
        'intel.subsection': 'ذیلی دفعہ',
        'intel.clause': 'شق',
        'intel.whatSourceEstablishes': 'مستند قانونی معیارات قائم کرتا ہے۔',
        'intel.whatSourceDoesNotEstablish': 'یہ منظور شدہ پیٹنٹ یا لائسنس نہیں ہے۔',
        'intel.noGapsTitle': 'کوئی اہم ثبوت کا خلا نہیں ملا',
        'intel.noGapsDesc': 'اس فارمولیشن کے لیے تمام اہم قانونی پیرامیٹرز بتائے گئے ہیں۔',
        'intel.dynamicallyEvaluated': 'پیٹنٹ اور آیوش قوانین کے تحت جانچا گیا',
        'intel.groundingTraceActive': 'گراؤنڈنگ ٹریس فعال ہے',
        'intel.groundingTraceDesc': 'بغیر کسی قیاس آرائی کے پیرامیٹرز کو ٹریس کریں۔',
        'intel.attachDocsDesc': 'کیس کے ثبوت کے لیے تجزیاتی سرٹیفکیٹ (CoA) منسلک کریں۔',
        'intel.maxFileSize': 'زیادہ سے زیادہ: 10MB · اسکین شدہ اور الگ کیا گیا',
        'intel.supportedFormats': 'PDF, DOCX, TXT, CSV, JSON معاونت یافتہ',
        'intel.cleanVerified': 'صاف اور تصدیق شدہ',
        'intel.quarantined': 'الگ کیا گیا (قرنطینہ)',
        'intel.securityPrinciple': 'حفاظتی اصول:',
        'intel.securityPrincipleDesc': 'تمام دستاویزات کو غیر معتبر سمجھا جاتا ہے۔',
        'intel.provenanceTracer': 'اصل ماخذ ٹریسر (Provenance)',
        'intel.timeMachineDesc': 'تاریخی ترامیم اور گزٹ نوٹیفیکیشنز کا آڈٹ کریں۔',
        'intel.selectFramework': 'فریم ورک منتخب کریں:',
        'intel.gazettePdf': 'سرکاری گزٹ PDF',
        'intel.clauseComparison': 'شق وار موازنہ اور تجزیہ',
        'intel.previousText': 'سابقہ / اصل متن',
        'intel.amendedText': 'ترمیم شدہ متن',
        'intel.sec3pBar': 'Section 3(p) پابندی',
        'intel.applicable': 'لاگو',
        'intel.synergyRequired': 'Section 3(p) پر قابو پانے کے لیے ڈیٹا درکار ہے۔',
        'intel.slaGmpRequired': 'ریاستی آیوش Schedule T GMP منظوری درکار ہے۔',
        'intel.sbbSec7Mandatory': 'لازمی پیشگی اطلاع',
        'intel.sbbSec7Exemption': 'استثنیٰ کا جائزہ',
        'intel.nbaSec6Title': 'پیٹنٹ گرانٹ کے لیے پیشگی Form III منظوری',
        'intel.benefitSharingRate': 'فائدہ بانٹنے کی شرح: 0.1% سے 0.5%۔',
        'intel.actionSbb': '1. SBB Form I داخل کریں',
        'intel.actionCoa': '2. NABL بھاری دھاتوں کا CoA',
        'intel.actionTm': '3. ٹریڈ مارک Class 5 درخواست',
    }
}

# Copy to regional variants
INTEL_PER_LANG['as'] = INTEL_PER_LANG['bn']
INTEL_PER_LANG['mni'] = INTEL_PER_LANG['bn']
INTEL_PER_LANG['ks'] = INTEL_PER_LANG['ur']
INTEL_PER_LANG['sd'] = INTEL_PER_LANG['ur']
INTEL_PER_LANG['sat'] = INTEL_PER_LANG['bn']

print("Updating index.ts with authentic native translations for all remaining languages...")
for lang, kmap in INTEL_PER_LANG.items():
    l_upper = lang.upper()
    tag = f"export const {l_upper}_TRANSLATIONS: TranslationDict = {{"
    pos = content.find(tag)
    if pos == -1:
        continue
    next_pos = content.find("export const ", pos + len(tag))
    sec = content[pos:next_pos] if next_pos != -1 else content[pos:]
    
    for k, v in kmap.items():
        v_esc = v.replace('"', '\\"')
        # Replace existing key if present, or add
        pattern = re.compile(rf'"{re.escape(k)}":\s*"[^"]*"')
        if pattern.search(sec):
            sec = pattern.sub(f'"{k}": "{v_esc}"', sec)
        else:
            # prepend
            sec = sec[:len(tag)] + f'\n  "{k}": "{v_esc}",' + sec[len(tag):]
            
    if next_pos != -1:
        content = content[:pos] + sec + content[next_pos:]
    else:
        content = content[:pos] + sec

with open('frontend/src/i18n/translations/index.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print("Updated index.ts successfully!")
